### ISSUE TITLE
/opt/YAHM/bin nicht im PATH

### ISSUE THREAD

**Issue by ploebb** [leonsio/YAHM#1]
Nach der Installation (mit -quickinstall) ist der bin-pfad von YAHM scheinbar nicht im PATH.

`sudo: yahm-ctl: Kommando nicht gefunden`

btw: beeindruckende Arbeit bisher! Ich setze mich gleich ans HM-MOD-RPI-PCB, oder läuft das jetzt schon? Sorry, dass ich mich so lang nicht gemeldet habe.
Ich kann auch nicht versprechen, dass ich es heut zum laufen kriege und ab morgen bin ich schon wieder das WE weg.

**Comment by leonsio** [comment]
Hi

hab den Fehler gefunden, es hat ein "export" gefehlt, damit PATH Angaben in der aktuellen Session gültig sind.

HM-MOD-RPI-PCB ist soweit fertig, kannst es gern austesten und bei Problemen beheben ;)

**Comment by ploebb** [comment]
> hab den Fehler gefunden

Top!

> HM-MOD-RPI-PCB ist soweit fertig

Auf den ersten Blick taucht es erst mal nicht unter Geräte auf. Mal schauen.

**Comment by ploebb** [comment]
Ah hab das Readme-Update gesehen

**Comment by leonsio** [comment]
hab ein Bug gefunden werde den schnell fixen

**Comment by ploebb** [comment]
Is es der Pfad zur rfd.conf? Die findet er nämlich grad nicht.

**Comment by leonsio** [comment]
jupp genau das ist das Problem

**Comment by leonsio** [comment]
sollte nun gehen, mach vorher git pull
