### ISSUE TITLE
Disable Homematic IP entfernt auch das RPI Funkmodul FW 2.19.9

### ISSUE THREAD

**Issue by renmet** [leonsio/YAHM#10]
Wenn man bei FW 2.19.9 HMIP deaktivert verschwindet leider auch das Funkmodul aus Homematic (Einstellungen - Systemsteuerung - LAN Modul). Selbst eine Neuinstallation des Modules mit -f bringt das Modul nicht mehr zurück. Dafür dürften aber die Heizungsgruppen mit dem neuen HMIP Server funktionieren. Es erscheint nur eine HMIP Fehlermeldung im Webinterface und der Fehler 'VirtualDevices' ist unter /var/log/messages nicht zu finden.

**Comment by leonsio** [comment]
Habe es auch gerade gemerkt dass das neue HMIPServer nun sich humaner verhält und nicht abbricht wenn ttyS0 nicht vorhanden ist, ich werde den Patch anpassen müssen.

Wobei wie ich bereits geschrieben habe sollte dies keine Auswirkungen haben

Poste bitte deine /etc/config/InterfacesList.xml  Datei

Gruß

Leo

**Comment by renmet** [comment]
Hallo,

hier die gewünschten Informationen

```
<?xml version="1.0" encoding="utf-8" ?> 
<interfaces v="1.0">
    <ipc>
        <name>BidCos-RF</name>
        <url>xmlrpc_bin://127.0.0.1:2001</url> 
        <info>BidCos-RF</info> 
    </ipc>
    <ipc>
        <name>VirtualDevices</name>
        <url>xmlrpc://127.0.0.1:9292/groups</url> 
        <info>Virtual Devices</info> 
    </ipc>
    <ipc>
        <name>HmIP-RF</name>
        <url>xmlrpc://127.0.0.1:2010</url> 
        <info>HmIP-RF</info> 
    </ipc>
    <ipc>
        <name>CUxD</name>
        <url>xmlrpc_bin://127.0.0.1:8701</url> 
        <info>CUxD</info> 
    </ipc>
</interfaces>
```

LG
René

**Comment by leonsio** [comment]
hi
wollte nur Bescheid geben, dass ich das Problem reproduzieren kann und mich auf die Suche mache

Gruß

Leo

**Comment by leonsio** [comment]
Ist nun gefixt
