### ISSUE TITLE
New Firmware 2.27.7 released

### ISSUE THREAD

**Issue by BOFH90** [leonsio/YAHM#100]
Eine Neue Firmware Version ist verfügbar:
https://www.homematic-inside.de/blog/updates/item/ccu-2-firmware-v2-27-7-verfuegbar

**Comment by leonsio** [comment]
Siehe develop branch

**Comment by jp112sdl** [comment]
...wollte ich auch gerade schreiben.

Läuft übrigens stabil bei mir. Oder gibt es deinerseits irgendwelche Bugs zu berichten?

**Comment by BOFH90** [comment]
Perfekt. Dann warte ich mal bis es in der stable branach ist. :)
