### ISSUE TITLE
Warnungen im hmserver.log

### ISSUE THREAD

**Issue by jp112sdl** [leonsio/YAHM#101]
Ich erhalte alle paar Sekunden im hmserver.log folgende Meldung:
de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE:...

In einem anderen Issue #85  habe ich gelesen, dass diese Meldung nicht weg zu bekommen ist.

Ist das aktuell immer noch der Fall?

**Comment by leonsio** [comment]
hat nichts mit YAHM zu tun, die kommen auch auf original CCU2
