### ISSUE TITLE
Funkmodul funktioniert nicht unter CCU2

### ISSUE THREAD

**Issue by renwin** [leonsio/YAHM#102]
Die Lösung im FAQ ist keine Lösung.
Wie soll ich das Problem denn nun beheben können?
Über raspi-config serial auf disable oder wie genau?
Und ich habe ein RS485 USB Stick, welches Modul brauche ich da?

**Comment by leonsio** [comment]
siehe
https://github.com/leonsio/YAHM/wiki/YAHM-Module:-HM-MOD-RPI-PCB
https://github.com/leonsio/YAHM/wiki/Problembehandlung
