### ISSUE TITLE
Automatic installation is failing

### ISSUE THREAD

**Issue by Marty56** [leonsio/YAHM#105]
On the 2nd of April I tried to use 

`wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -`

on a brand newly installed and updated Raspian on a Raspberry 3.
It is failing out of the box.

It seems that this LXC Container is still having this version problem.
As the version conflict 15 vs 16 mentioned in "CLOSED" issues been resolved in the .SH file I am downloading with the command above?
Is there any other workaround?

**Comment by mainkowitsch** [comment]
Yes.
i installed it today successfully.

1. `wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -
`
2. `sudo yahm-lxc -f install`

3. `sudo yahm-network -w create_bridge`

4. `sudo yahm-network attach_bridge`

5. `sudo reboot`

6. `sudo yahm-lxc -f install`

the second time you install the lxc, you could see how he tries to download an old version of the ccu firmware but fail.... then it will download it from git...

**Comment by Marty56** [comment]
@mainkowitsch 
With your instructions the installation went through. Thank you.

Unfortunately in the yahm-ui it state that the CCU is stopped and trying to start CCU does not work.
Nor can I install the Homematic RF interface. This is also failing.

**Comment by Marty56** [comment]
I have now used yahm-ui and installed the CCU2. Also I managed to install the RF Interface.
Now I am getting this RF Protocol error.

**Comment by leonsio** [comment]
Which error messages?



 Von:   Marty56 <notifications@github.com> 
 An:   leonsio/YAHM <YAHM@noreply.github.com> 
 Kopie:   Subscribed <subscribed@noreply.github.com> 
 Gesendet:   03.04.2017 7:07 
 Betreff:   Re: [leonsio/YAHM] Automatic installation is failing (#105) 


I have now used yahm-ui and installed the CCU2. Also I managed to install the RF Interface.
 Now I am getting this RF Protocol error.

**Comment by Marty56** [comment]
Hi leonsio,

Thanks for the reply. I am not able to train any homematic devices.
can you please check the log and determine whether I was able to install the homematic RF Interface?

Sorry for my ignorance:

Update: User (my) Error. I manage to successfully train a device.

The only problem remaining is that my old CCU2 has the version 2.27.7 and the Yahm CCU2 has version 2.25.15, therefore the recovery from a Backup of my old CCU2 is failing.

So I guess I would have two possibilities
1. reset all my actuators and sensors and pair them step by step in the Yahm CCU2.
2. potentially wait until Yahm CCU2 is also supporting 2.27.7.
Will this happen in the near future?

**Comment by leonsio** [comment]
hi 
new yahm version with support for 2.27.8 is now online
just enter yahm-ctl update to update yahm, and yahm-lxc update to update your installation

for import old ccu2 data see https://translate.google.com/translate?hl=en&sl=de&tl=en&u=https%3A%2F%2Fgithub.com%2Fleonsio%2FYAHM%2Fwiki%2FMigration-von-CCU-zu-YAHM%23migration-von-ccu12-zu-yahm

**Comment by Marty56** [comment]
Thanks for the great support
