### ISSUE TITLE
Bidcos-RF will einfach nicht, Homebridge auch nicht

### ISSUE THREAD

**Issue by Larson-Sei180LX** [leonsio/YAHM#106]
Hallo

ich habe eine Frage bezüglich meines kläglichen Versuches, YAHM 1.6. / 2.27.8 auf dem Rasp 3b Jessie Pixel zum Laufen zu bringen. Ich habe jetzt mehrere Tage kläglich versucht, alles nach den Anleitungen etc. zu befolgen.

Bisher kann ich folgende Erfolge verbuchen.

Neues System aufgesetzt. Jessie Pixel installiert.
sudo apt-get update
sudo apt-get upgrade

und danach YAHM mit der UI-Version installiert. Die automatische VErsion scheitert leider.

wget -nv -O- https://raw.githubusercontent.com/leons ... /yahm-init | sudo -E bash -s ui -

Danach unter YAHM-UI die Installation durchgeführt (HM Funk-Module, FW, etc.), Seriennummer eingespielt.

Danach Zusatzmodule unter YAHM-UI(CuX) eingerichtet, erfolgreich.

Dann auf die Weboberfläche und das Update meiner CCU2 eingespielt. Alles angenommen, Geräte erscheinen.

Jetzt kommt ein Fehler: BidCOs-RF funktioniert nicht. Die RF-Geräte werden folglich auch nicht angezeigt.

Ich habe unter Yahm auch festgestellt, dass manchmal die RF-Geräte in der Weboberfläche auftauchen, wenn ich den Container manuell über UI beende und wieder starte. Also müsste das Funkmodul an sich in Ordnung sein. Allerdings ist beim nächsten Neustart des PIs wieder das gleiche Problem. Bin echt am verzweifeln und hoffe, dass mir einer helfen kann.

Homebridge sollte auch dann als Zustatzmodul unter YAHM-UI installiert werden, dies ist zwar erfolgreich installiert worden, jedoch finde ich die Homebridge nicht im Iphone.

Fragen über Fragen..... Danke Euch

**Comment by jp112sdl** [comment]
Hast du an die Besonderheiten beim Raspberry Pi 3 gedacht?

Anpassung Bluetooth (Rpi3)

> Sollte ein Raspberry 3 gefunden werden, muss zusätzlich Bluetooth angepasst werden, da dieser die gleichen GPIO Pins verwendet, wie das Raspberry Funkmodul.
Zur Anpassung des BT Moduls wird ein so genanntes Overlay pi3-miniuart-bt-overlay für Kernel < 4.1 bzw. pi3-miniuart-bt für Kernel > 4.1 in die Datei /boot/config.txt eingetragen, damit beim Start die GPIO Pins des BT Module von Raspberry 3 anders belegt werden und für das Modul zur Verfügung stehen.

https://github.com/leonsio/YAHM/wiki/YAHM-Module:-HM-MOD-RPI-PCB

**Comment by Larson-Sei180LX** [comment]
Ja das habe ich auch schon manuell gemacht. Aber so wie du ja dort schreibst, macht das ja die installation normal automatisch?

**Comment by jp112sdl** [comment]
Eigentlich... :) Ich hatte auf meinem Pi 1 A auch ein paar kleine Macken, die ich manuell bereinigen musste. U.a. auch Ärger mit dem Funkmodul. Bei mir lag es an der rfd.conf
Der 
`Improved Coprocessor Initialization = false`
steht standardmäßig auf true und wird eigentlich durch ein Skript auf false gesetzt. Hat bei mir irgendwie nicht funktioniert.

**Comment by Larson-Sei180LX** [comment]
das ist bei mir leider nicht das Problem. Das steht auf false. Das komische ist ja, am Anfang hat es ja funktioniert. Erst nach dem neustart lief nix mehr

**Comment by jp112sdl** [comment]
Wurde denn das Start-Skript `/etc/init.d/hm-mod-rpi-pcb` angelegt und wird es beim Booten auch ausgeführt? Du kannst es ja sicherheitshalber noch mal manuell starten und danach den YAHM-Container.

Dann schau mal mit `ps -ef|grep rfd` ob der RF-Daemon überhapt läuft

**Comment by Larson-Sei180LX** [comment]
unter dem PFad steht tatsächlich nichts drinnen. Ich kann da allerdings auch nichts abspeichern, wenn ich das Skript dort manuell einfügen will.... keine Schreibrechte ?! Sorry leider kenn ich mich nicht so gut mit der Pi-Materie aus, wenn ich so blöde fragen stelle...

**Comment by Larson-Sei180LX** [comment]
Anpassung /etc/config/rfd.conf    


dort konnte ich auch nichts finden.

Ich öffne diese dateien mit dem Befehl

sudo nano /etc/config/rfd.conf

**Comment by jp112sdl** [comment]
Ok - nichts durcheinander bringen.

Die `/etc/config/rfd.conf` steht im Container - also du musst dich innerhalb der CCU befinden, um an die Datei ranzukommen. "In" die CCU kommst du mit "yahm-ctl join"
- Oder -
Direkt am Pi angemeldet sollte die Datei unter
`/var/lib/lxc/yahm/root/usr/local/etc/config/rfd.conf` zu finden sein.

**Comment by jp112sdl** [comment]
Um dein init-Skript am Pi zu speichern/editieren musst du root sein

**Comment by Larson-Sei180LX** [comment]
Also nochmal zur Verständnis: unter YAHM-UI kann ich mir diese beiden Dateien ja unter Diagnose anzeigen lassen. Da steht das auch alles drinnen... aber ich habe glaube ich die Dateien direkt bearbeitet, also im SSH

**Comment by Larson-Sei180LX** [comment]
und wo liegt das init.d skript ?

**Comment by Larson-Sei180LX** [comment]
Also die Dateien habe ich jetzt ale gefunden, sind alle vorhanden ;(

**Comment by jp112sdl** [comment]
Wobei das reine Vorhandensein des init-Skripts
`/etc/init.d/hm-mod-rpi-pcb` noch nicht beweist,dass es beim Booten auch ausgeführt wird.

Mach doch mal ein `sudo /etc/init.d/hm-mod-rpi-pcb start`, dann ist es in jedem Fall einmal gelaufen und danach startest du nur deinen YAHM-Container, also die CCU, noch mal neu

**Comment by jp112sdl** [comment]
Außerdem könntest du prophylaktisch ein `update-rc.d hm-mod-rpi-pcb enable` machen. Das sorgt dafür, dass das Skript beim Booten ausgeführt wird.

**Comment by leonsio** [comment]
Frage vorweg, hattest du raspberrymatic vorher installiert? falls ja diese flasht die Firmware auf Homematic-IP, dadurch wird es **vorerst** nicht unter YAHM warten (siehe letztes Commit im develop branch)

führe folgendes aus (als root):

     echo 18 > /sys/class/gpio/export
     echo out > /sys/class/gpio/gpio18/direction
     echo 0 > /sys/class/gpio/gpio18/value
     sleep 0.1
     echo 1 > /sys/class/gpio/gpio18/value

Dadurch wird ein Reset durchgeführt (das was `/etc/init.d/hm-mod-rpi-pcb`macht)

dann führe folgendes aus (als root):

    /opt/YAHM/share/tools/hmgw
    ./start-hmlan.sh

Du müsstest die Seriennummer deines Moduls erhalten. Damit ist sichergestellt dass dein Modul in Ordnung ist, bzw. Raspi als solcher richtig konfiguriert wurde

**Comment by Larson-Sei180LX** [comment]
raspberrymatic hatte ich nicht drauf, wobei mein Modul ein gebrauchtes ist. Weiss leider nicht, was der vorbesitzer damit gemacht hat.

**Comment by Larson-Sei180LX** [comment]
Also die Geräte tauchen jetzt auf. Werde mal neu starten um zu sehen, was dann passiert.

**Comment by Larson-Sei180LX** [comment]
SO, wie erwartet ... nach dem Neustart leider wiederdie Geräte weg.....

**Comment by jp112sdl** [comment]
@leonsio Hey cooooool, IP Support experimental. TOP!

P.S.: Ich hab bei mir (wo übrigens alles zufriedenstellend läuft) mal das hmgw-Tool gestartet und erhalte immer "can't get serial number!" :/

**Comment by Larson-Sei180LX** [comment]
ICh habe jetzt nochmal den Befehl
sudo /etc/init.d/hm-mod-rpi-pcb start

ausgeführt, Container beendet und neu gestartet... und siehe da, wieder alle daaaa

**Comment by Larson-Sei180LX** [comment]
also sieht so aus, dass der Befehl beim start nicht ausgeführt wird.....

weisst du, wie wir das lösen können ?

**Comment by jp112sdl** [comment]
@Larson-Sei180LX ja das sieht dann recht eindeutig aus...
Hast du mal `update-rc.d hm-mod-rpi-pcb enable` als root ausgeführt?

**Comment by Larson-Sei180LX** [comment]
ja, das habe ich gemacht

**Comment by jp112sdl** [comment]
Schau mal mit `ls -l /etc/rcS.d` ob es dort etwas namens `Sxxhm-mod-rpi-pcb` gibt.
xx steht für 2 Zahlen

**Comment by Larson-Sei180LX** [comment]
nein, da findet sich nichts dergleichen

**Comment by jp112sdl** [comment]
Dann hat das update-rc.d nicht funktioniert.
Also noch mal etwas verändert:
`sudo update-rc.d hm-mod-rpi-pcb enable S`

Anschließend schaust du noch mal mit `ls -l /etc/rcS.d` ob da jetzt was ist.

**Comment by Larson-Sei180LX** [comment]
ja jetzt sehe ich es

**Comment by jp112sdl** [comment]
Ok - Dann Reboot und viel Glück!

**Comment by Larson-Sei180LX** [comment]
leider wieder nicht ;(((((

**Comment by Larson-Sei180LX** [comment]
Vielleicht sollte ich noch erwähnen, dass das Backup von einer CCU2 ist, selbe FW.

**Comment by jp112sdl** [comment]
Ja das hatte bei mir scheinbar dafür gesorgt, dass die Coprocessor Initialization auf true stand

**Comment by jp112sdl** [comment]
Die rfd.conf ist im Backup mit drin, hab grad mal nachgeschaut.
Also musst du nach dem Einspielen des Backups auch die rfd.conf wieder anpassen.

Nicht nur Improved Coprocessor Initialization = false

sondern auch

[Interface 0]
Type = CCU2
Description = CCU2-Coprocessor
ComPortFile = /dev/mmd_bidcos
AccessFile = /dev/null
ResetFile = /dev/ccu2-ic200

**Comment by Larson-Sei180LX** [comment]
Ja dieses File entspricht meiner rfd.conf

**Comment by jp112sdl** [comment]
Dann bin ich jetzt leider mit meiner Ferndiagnose auch am Ende :/

**Comment by Larson-Sei180LX** [comment]
meinst du ich könnte dir irgenwie zugriff auf den pi geben ?

**Comment by Larson-Sei180LX** [comment]
ich verzweifle langsam schon .. mach schon drei tage dran rum....

**Comment by jp112sdl** [comment]
Hast du Facebook? Schreib mir da mal ne PN 
http://fb.me/jp112sdl

**Comment by Larson-Sei180LX** [comment]
diese seite geht nicht...

**Comment by jp112sdl** [comment]
Ich komme dann auf mein FB-Profil... Sonst such einfach mal bei FB nach jp112sdl

**Comment by Larson-Sei180LX** [comment]
Habe dir dort geschrieben.

**Comment by jp112sdl** [comment]
Erledigt. Kann geschlossen werden.

**Comment by leonsio** [comment]
Woran lag es?

**Comment by jp112sdl** [comment]
Die rfd.conf war nach dem Zurückspielen des Backups der Original-CCU fehlerhaft.

Hab ihm per TeamViewer unkompliziert Support geleistet und die Umgebung soweit eingerichtet, dass auch nach einem Reboot noch alles funktioniert
