### ISSUE TITLE
crond läuft 2x

### ISSUE THREAD

**Issue by jp112sdl** [leonsio/YAHM#107]
Bei der Installation wird 
`/etc/init.d/S00eQ3SystemStart` modifiziert und die ursprüngliche Datei nach `/etc/init.d/S00eQ3SystemStart.orig` gesichert.

Beim Hochfahren des LXC-Containers werden beide Dateien ausgeführt, was wiederum dazu führt, dass der crond doppelt läuft.

Habe mich gewundert, warum mein Backup-Skript immer doppelt läuft...

**Comment by leonsio** [comment]
Eigentlich sollte keine zweite Datei da sein. 
Die wird nur abgelegt, wenn etwas schief gelaufen ist
Ich prüfe das.

**Comment by jp112sdl** [comment]
Vielleicht ist damals bei der Installation tatsächlich was schief gelaufen, was ich von Hand wieder gerade gebogen habe. 
Wenn die .orig standardmäßig gar nicht abgelegt wird, dann kann das Ticket hier eigentlich auch wieder zu. :)

**Comment by leonsio** [comment]
ist im aktuellen develop branch gefixt
