### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by zioalex** [leonsio/YAHM#108]
Hi,
it would be great to have the documentation also, or only, in English. 

For no German native speakers, like me, it would be great :-D

I can help in this if you think is valuable.

Thanks
Alessandro

**Comment by leonsio** [comment]
homematic is mostly active in German speaking regions
you can use google translator to translate the documentation

https://translate.google.com/translate?hl=en&sl=de&tl=en&u=https%3A%2F%2Fgithub.com%2Fleonsio%2FYAHM

the code and the application is in english, actually mostly of users is native German speakers, so I'm not planing to translate the complete documentation
