### ISSUE TITLE
No BidCoS-Interface available

### ISSUE THREAD

**Issue by zioalex** [leonsio/YAHM#109]
Hi @leonsio I followed your suggestion and started using the branch-develop.

I installed everything with yahm-ui and everything was ok.
Then I went into the lxc container and I didn't see the rfd daemon.

I tried to start it manually and I get the follow error:
```
/var/log # /bin/rfd -f /etc/config/rfd.conf -l 0 -c
2017/04/14 21:30:22.914 <Info> BidCoS-Service started
2017/04/14 21:30:22.915 <Info> XmlRpc Server is listening on TCP port 2001
2017/04/14 21:30:22.916 <Warning> opendir(/etc/config/firmware//) failed
2017/04/14 21:30:22.917 <Debug> CCU2CommController::init() - Legacy initialization.
2017/04/14 21:30:24.554  RX SERIAL: fd 00 16 03 06 05 3a 58 
2017/04/14 21:30:24.555  RX SERIAL: 00 36 f7 86 10 4f c2 65 
2017/04/14 21:30:24.556  RX SERIAL: 00 00 00 0a 30 c7 0f 00 
2017/04/14 21:30:24.557  RX SERIAL: 00 dd 53 
2017/04/14 21:30:24.557  RX FRAME: 03 06 05 3a 58 00 36 f7 86 10 4f c2 65 00 00 00 0a 30 c7 0f 00 00 
2017/04/14 21:30:24.557  CCU2CoprocessorCommand::CCU2CoprocessorCommand(): Unknown command type: 03  (hex).
2017/04/14 21:30:24.557 <Debug> () CCU2CommController::handleIncomingSerialFrame(): Command not parseable.
2017/04/14 21:30:27.918 <Debug> () CCU2CommController::startCoprocessorApp(): Trying to start coprocessor application
2017/04/14 21:30:28.418  CCU2CommController::startCoprocessorAppThreadFunction(): Send start command
2017/04/14 21:30:28.418  CCU2CommController::SendSystemCommdand()
2017/04/14 21:30:28.418  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 00 03 18 0a 
2017/04/14 21:30:28.421  RX SERIAL: fd 00 02 ff 00 02 00 
2017/04/14 21:30:28.421  RX FRAME: ff 00 
2017/04/14 21:30:28.421  CCU2CoprocessorCommand::CCU2CoprocessorCommand(): Message too small: 2 bytes.
2017/04/14 21:30:28.421 <Debug> () CCU2CommController::handleIncomingSerialFrame(): Command not parseable.
2017/04/14 21:30:29.419 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.

2017/04/14 21:30:31.419  CCU2CommController::startCoprocessorAppThreadFunction(): Retrying to send start command
2017/04/14 21:30:31.419  CCU2CommController::startCoprocessorAppThreadFunction(): Send start command
2017/04/14 21:30:31.419  CCU2CommController::SendSystemCommdand()
2017/04/14 21:30:31.419  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 01 03 9e 09 
2017/04/14 21:30:31.421  RX SERIAL: fd 00 02 ff 01 82 05 
2017/04/14 21:30:31.422  RX FRAME: ff 01 
2017/04/14 21:30:31.422  CCU2CoprocessorCommand::CCU2CoprocessorCommand(): Message too small: 2 bytes.
2017/04/14 21:30:31.422 <Debug> () CCU2CommController::handleIncomingSerialFrame(): Command not parseable.
2017/04/14 21:30:32.420 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.

2017/04/14 21:30:32.919 <Fatal error> CCU2CommController::init(): Init failed. Cannot start coprocessor application.
2017/04/14 21:30:32.919  CCU2CommController::SendSystemCommdand()
2017/04/14 21:30:32.920  CCU2CommController::SendSystemCommdand() sending: fd 00 04 00 02 0a 00 3d 10 
2017/04/14 21:30:32.922  RX SERIAL: fd 00 02 ff 02 82 0f 
2017/04/14 21:30:32.923  RX FRAME: ff 02 
2017/04/14 21:30:32.923  CCU2CoprocessorCommand::CCU2CoprocessorCommand(): Message too small: 2 bytes.
2017/04/14 21:30:32.923 <Debug> () CCU2CommController::handleIncomingSerialFrame(): Command not parseable.
2017/04/14 21:30:33.921 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.

2017/04/14 21:30:33.921 <Error> () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
2017/04/14 21:30:33.922 <Error> No BidCoS-Interface available
2017/04/14 21:30:33.923 <Warning> Error initializing interfaces
```

The script /etc/init.d/hm-mod-rpi-pcb status is executed correctly at the start time:
```
● hm-mod-rpi-pcb.service - LSB: Enables GPIO 18 as reset Interface for HM RF Module for Raspberry
   Loaded: loaded (/etc/init.d/hm-mod-rpi-pcb)
   Active: active (exited) since Fri 2017-04-14 23:27:18 CEST; 6min ago
  Process: 270 ExecStart=/etc/init.d/hm-mod-rpi-pcb start (code=exited, status=0/SUCCESS)

Apr 14 23:27:18 raspberrypi systemd[1]: Starting LSB: Enables GPIO 18 as reset Interface for HM RF Module for Raspberry...
Apr 14 23:27:18 raspberrypi hm-mod-rpi-pcb[270]: Enables GPIO 18 as Reset Interface for Homematic RF wireless module: Enables GPIO 18 as Re...-UART...
Apr 14 23:27:18 raspberrypi hm-mod-rpi-pcb[270]: Preparing GPIO for HM-MOD-UART done!Reseting PCB.
Apr 14 23:27:18 raspberrypi systemd[1]: Started LSB: Enables GPIO 18 as reset Interface for HM RF Module for Raspberry.
```

Any idea?

**Comment by zioalex** [comment]
And in the /var/log/hmserver.log file in the container:
```
Apr 14 23:48:53 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Timer-1] Could not register BidCos-RF_java
Apr 14 23:48:57 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: long-lasting deployment, check deployment configuration - currently deployed 15 out of 17
Apr 14 23:48:57 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-6] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open])
Apr 14 23:48:57 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-2] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [connector.open])
Apr 14 23:48:58 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Timer-1] Could not register BidCos-RF_java
Apr 14 23:49:03 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Timer-1] Could not register BidCos-RF_java 
Apr 14 23:49:04 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-6] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
Apr 14 23:49:04 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-2] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [connector.open]) 
```

While the homematic gui is accesible but with no BidCos-RF.

**Comment by leonsio** [comment]
You are coming from raspberrymatic? It flashes dualcoprocessor firmware. Enable homematic ip module or reflash the firmware

**Comment by leonsio** [comment]
If you installed homematic ip module take a look at /dev/mmd_bidcos and /dev/ttyS0 they should be present on host and inside lxc. 
Maybe you must enable this devices for lxc

            lxc-device -n yahm  add /dev/mmd_bidcos
            lxc-device -n yahm  add /dev/ttyS0

This is my first release with homematic ip. It contains some bugs ;)

**Comment by zioalex** [comment]
Hi @leonsio yes I came from Raspberrymatic. What does it mean that I have to reflash the firmware? Do you mean the Funkmodul FW?

However I tried as you suggested and checked the device files.
The only missed was the /dev/ttyS0 while the other were already present:
```
lrwxrwxrwx    1 root     root             7 Apr 14 21:24 /dev/mmd_bidcos -> ttyAMA0
crw-------    1 root     root      204,  64 Apr 14 21:27 /dev/ttyAMA0
```

I also tried to install the homematic-ip module but it fails after downloading the kernel source but I cannot find any log regarding the failure. However the rfd daemon, still, fails to start.

I am trying to understand how to flash the FW and which FW :-D

**Comment by zioalex** [comment]
So I tried with the eq3configcmd command from inside the container:
```
/opt # eq3configcmd update-coprocessor -p /dev/ttyS0  -c -se -d /firmware/
2017/04/15 14:07:17.332 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2017/04/15 14:07:17.332 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2017/04/15 14:07:19.333 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2017/04/15 14:07:19.333 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2017/04/15 14:07:21.333 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2017/04/15 14:07:21.333 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2017/04/15 14:07:22.333 <Error> CoprocessorUpdate::startApplication():Could not start Coprocessor application.
```

or
```
/opt # eq3configcmd update-coprocessor -p /dev/ttyS0  -c -u -d /firmware/
2017/04/15 14:09:00.877 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2017/04/15 14:09:00.877 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2017/04/15 14:09:02.886 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2017/04/15 14:09:02.886 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2017/04/15 14:09:04.886 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2017/04/15 14:09:04.886 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2017/04/15 14:09:05.886 <Error> CoprocessorUpdate::startApplication():Could not start Coprocessor application.

2017/04/15 14:09:05.886 <Error> Could not start Application, maybe no application on device, do update with dummy Version: 0.0.0

2017/04/15 14:09:05.886 <Info> Update necessary, installed: 0.0.0, avaiable 2.8.3

2017/04/15 14:09:06.886 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
2017/04/15 14:09:06.886 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2017/04/15 14:09:09.387 <Info> CCU2CommControllerMod::sendSystemCommand(): failed
```
No way. I think the module is not correctly initialized at the host level.

**Comment by leonsio** [comment]
I have some bugs in my script. Remove all if $? -eq 0 checks and let the script run (or replace 0 with 1 )

This should compile the kernel an build all modules. I will fix this in the next commit

**Comment by leonsio** [comment]
so I have updated my script
try to run it with 

    yahm-module -m homematic-ip -f -v enable

the script is building ne kernel based on actual configuration but with PL011 shared module
after it, eq3_char_loop and bcm2835_raw_uart modules will be compiled and installed.

only with this modules you will be able to use your rpi-hm module (Funkmodul) with homematic. I think it is not possible to downgrade the firmware of the Funkmodul without this modules. so you can install raspberrymatic and manually downgrade the firmware, or you can try to run my script, with new kernel and modules installed, all should be run with homematic-ip support.

try to compile a new kernel without PL011 support, other steps are trivial

if you wish I can help you with teamweaver session

**Comment by zioalex** [comment]
@leonsio thank you very much for your support. I really appreciate it.
I am trying now with the latest patch. Now the kernel is building. Let's see.

At the moment..just Frohe Ostern :-)

**Comment by zioalex** [comment]
Oky we have now something better to see :-)
```
/firmware/HM-MOD-UART # eq3configcmd update-coprocessor -p /dev/ttyAMA0    -c -u  -d /firmware/HM-MOD-UART/
2017/04/16 06:43:17.725 <Info> Version: 2.2.1

2017/04/16 06:43:17.725 <Info> Update necessary, installed: 2.2.1, avaiable 2.8.4

2017/04/16 06:43:44.174 <Info> Firmwareupdate successfull

/firmware/HM-MOD-UART # eq3configcmd update-coprocessor -p /dev/ttyAMA0    -c -v  -d /firmware/HM-MOD-UART/
2017/04/16 06:43:52.700 <Info> Version: 2.8.4

# eq3configcmd update-coprocessor -p /dev/ttyAMA0    -c -se
2017/04/16 07:53:15.585 <Info> SerialNumber: NEQ1331777

```

But still the rfd daemon doesn't run properly!
```
2017/04/16 07:49:07.027 <Debug> () CCU2CommController::startCoprocessorApp(): Trying to start coprocessor application
2017/04/16 07:49:07.528  CCU2CommController::startCoprocessorAppThreadFunction(): Send start command
2017/04/16 07:49:07.528  CCU2CommController::SendSystemCommdand()
2017/04/16 07:49:07.528  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 00 03 18 0a 
2017/04/16 07:49:07.530  RX SERIAL: fd 00 02 ff 00 02 00 
2017/04/16 07:49:07.531  RX FRAME: ff 00 
2017/04/16 07:49:07.531  CCU2CoprocessorCommand::CCU2CoprocessorCommand(): Message too small: 2 bytes.
2017/04/16 07:49:07.531 <Debug> () CCU2CommController::handleIncomingSerialFrame(): Command not parseable.
2017/04/16 07:49:08.529 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
```
I retried also with a clean LXC container but the result in the same.

**Comment by leonsio** [comment]
Please post output from ls -al /dev from LXC AND Host (raspberry)

Check if pl011 module is shared.

**Comment by leonsio** [comment]
I will try to explain you, why your setup is not working

With the normal firmware 

Rfd communicate with /dev/ttyAMA0

With homematic-ip firmware your have 2 kernel modules:

1. bcm2835-raw-uart
2. eq3_char_loop

First of all you need to start multimacd daemon, this will load eq3_char_loop module (/dev/eq3loop) and create two dev devices 

/dev/mmd_bidcos		used for homematic communication. (rfd)
/dev/ttyS0		used for homematic-ip. (hmipserver.jar)


Dmesg output

[90355.127728] eq3loop: created slave ttyS0
[90355.130855] eq3loop: created slave mmd_bidcos
[96140.107958] eq3loop: eq3loop_open_slave() mmd_bidcos

In the configuration without homematic-ip, you can find a symlink from /ttyAMA0 to /dev/mmd_bidcos, with homematic-ip this should be native device.

That you have to do is

On host
1. Check if pl011 module is shared: modinfo amba_pl011
2. check if bcm2835-raw-uart and eq3_char_loop are loaded -> /dev/bcm2835-raw-uart and /dev/eq3loop are present
3. Take a look on multimacd.conf /etc/config in LXC and /etc/init.d/S60multimacd . (Coprocessor Device Path = /dev/bcm2835-raw-uart replace uart device if needed)
4. Start /etc/init.d/S60multimacd inside LXC, you must find some messages in dmesg (like above)
5. Remove symlink from /dev/mmd_bidcos
6. In host system you will find /dev/mmd_bidcos and /dev/ttyS0
7. Pass throw the devices to container

lxc-attach -n yahm -- rm -rf /dev/ttyS0
lxc-attach -n yahm -- rm -rf /dev/mmd_bidcos
8 start rfd

**Comment by leonsio** [comment]
Hi i have uploaded some bugfixes
In you have recompiled your Kernel without pl011 Module. Everything Else should run without Problems

Von meinem iPad gesendet

**Comment by leonsio** [comment]
i have found anther "bug", after you have recompiled the kernel, you must remove pl011 module

    mv /lib/modules/4.4.50-v7+/kernel/drivers/tty/serial/amba-pl011.ko /root && depmod -a

after it, reload eq3loop and bcm2835-raw-uart modules and restart multimacd, you will find mmd_bidcos module under /dev

**Comment by zioalex** [comment]
HI @leonsio Finally it's working :-D Thanks for you explanation.

I read the previous comment just now and I didn't do it but the mmd_bidcos was there.

The multimacd daemon is running in the LXC while the device file /dev/eq3loop  was not present in the LXC container. I had to update the coprocessor dev file in the /etc/config/multimacd.conf to point zo /dev/bcm2835-raw-uart .

Debugging the multimacd with 
```
/bin/multimacd -f /etc/config/multimacd.conf -l 0 -c
```
I found out that also  the  /dev/bcm2835-raw-uart device was not present in the container

So in additional to the step you suggested
```
lxc-device -n yahm  add /dev/mmd_bidcos
```
I had to do also the following:
```
lxc-device -n yahm  add /dev/bcm2835-raw-uart
lxc-device -n yahm  add /dev/eq3loop
```

Now is working and I am re-adding my components.
I learned a lot on how it is working although It is not completely clear all the daemon's relationship. Please can you point to the right documentation...if any.

Thanks a lot.
