### ISSUE TITLE
Zentralen-Wartung ausgegraut

### ISSUE THREAD

**Issue by renmet** [leonsio/YAHM#11]
Hallo,

mit der neuersten Release von yahm funktioniert der Punkt **Zentralen-Wartung** in der Systemsteuerung wieder nicht (tested @ 2.17.16 & 2.19.9). Grund dafür dürfte wieder die fehlende Datei /var/ids sein

http://homematic-forum.de/forum/viewtopic.php?f=26&t=30674&start=100#p281735

LG
Rene

**Comment by Homekowsky** [comment]
Kann ich bestätigen: das Anlegen der Datei /var/ids innerhalb des Containers aktiviert den Menüpunkt - allerdings nur bis zu nächsten Neustart, dabei wird die Datei gelöscht.

Gruß
Ed

**Comment by leonsio** [comment]
Ist nun hoffentlich gefixt
