### ISSUE TITLE
CUL as main rf interface

### ISSUE THREAD

**Issue by jmtatsch** [leonsio/YAHM#110]
Hi,

could YAHM work with a Busware CUL as main interface?

Back on the lxcci homepage it said:

> CUL Stick mit der LXCCU verwenden:
> Seit der LXCCU Version 1.6 sind alle USB Geräte auch in den LXC Container verfügbar, deshalb funktioniert der CUL Stick seither ohne weiteres.

I don't understand if the CUL is just used as additional rf-interface for old fs20 devices or as main rf interface? and if that support still exist in YAHM?

**Comment by leonsio** [comment]
all usb devices are available inside YAHM.
take a look on http://culfw.de/culfw.html Step 2. 
you must configure the ttyACM0 device inside rfd.conf as main rf interface

**Comment by jmtatsch** [comment]
Hi leonsio,

I added my CUL to my yahm container with:
`lxc-device -n yahm  add /dev/ttyACM0`

created a link for mmd_bidcos:
`ln -s /dev/ttyACM0 /dev/mmd_bidcos`

the devices look ok:
```
total 20
drwxr-xr-x    6 root     root          4096 Jun 13 02:22 .
drwxr-xr-x   20 root     root          4096 Jun 13 02:22 ..
drwxr-xr-x    2 root     root          4096 Jun 13 01:43 char
crw-------    1 root     tty       136,   1 Jun 13 02:23 console
lrwxrwxrwx    1 root     root            13 Jun 13 02:22 fd -> /proc/self/fd
lrwxrwxrwx    1 root     root             7 Jun 13 02:22 kmsg -> console
lrwxrwxrwx    1 root     root            10 Jun 10 07:50 log -> ../tmp/log
lrwxrwxrwx    1 root     root            12 Jun 13 01:52 mmd_bidcos -> /dev/ttyACM0
crw-rw-rw-    1 root     root        1,   3 Jun 13 02:22 null
lrwxrwxrwx    1 root     root            13 Jun 10 07:51 ptmx -> /dev/pts/ptmx
drwxr-xr-x    2 root     root             0 Jun 13 02:22 pts
crw-rw-rw-    1 root     root        1,   8 Jun 13 02:22 random
drwxr-xr-x    4 root     root          4096 Jun 13 01:43 serial
drwxr-xr-x    2 root     root          4096 Jun 10 07:51 shm
lrwxrwxrwx    1 root     root            15 Jun 13 02:22 stderr -> /proc/self/fd/2
lrwxrwxrwx    1 root     root            15 Jun 13 02:22 stdin -> /proc/self/fd/0
lrwxrwxrwx    1 root     root            15 Jun 13 02:22 stdout -> /proc/self/fd/1
crw-rw-rw-    1 root     tty         5,   0 Jun 13 02:22 tty
crw--w----    1 root     tty         4,   0 Jun 13 02:22 tty0
crw--w----    1 root     root      136,   0 Jun 13 02:23 tty1
crw-------    1 root     root      166,   0 Jun 13 02:23 ttyACM0
crw-rw-rw-    1 root     root        4,  64 Jun 10 07:51 ttyS0
crw-rw-rw-    1 root     root        1,   9 Jun 13 02:22 urandom
crw-rw-rw-    1 root     root        1,   5 Jun 13 02:22 zero
```

and in /usr/local/etc/config/rfd.conf the interface is defined as follows:
```
[Interface 0]
Type = CCU2
ComPortFile = /dev/mmd_bidcos
#ComPortFile = /dev/ttyACM0
AccessFile = /dev/null
ResetFile = /dev/ccu2-ic200
```
But what would be the corresponding reset device for the CUL?

After restarting the container, it tries to get the rfd interface up 
```
Starting rfd: 
Waiting for rfd to get ready.sh: 352: unknown operand
.sh: 352: unknown operand
.sh: 352: unknown operand
.rfd is ready now.
```
But the BidCos-RF interface doesn't seem to be working:
`BidCos-RF Anlernmodus konnte nicht aktiviert werden.`

Do you have some hints for me please?

**Comment by jmtatsch** [comment]
Bump?

**Comment by jmtatsch** [comment]
switched to homegear
