### ISSUE TITLE
Activate homematic-ip module: noch nicht fertig

### ISSUE THREAD

**Issue by NCC1701M** [leonsio/YAHM#111]
Ich kann das Homematic- IP module nicht aktivieren. Es erscheint immer nur der Hinweis: noch nicht fertig

```
pi@homepi:~ $ sudo yahm-module -m homematic-ip -f -v enable
Executing homematic-ip module_install()
noch nicht fertig
pi@homepi:~ $
```

Anders kann ich das Funk-Modul aber nicht zu laufen bringen, wie [hier](https://github.com/leonsio/YAHM/wiki/Problembehandlung#nach-einer-neuinstallation-wird-mein-funkmodul-nicht-erkannt) beschrieben.

**Comment by leonsio** [comment]
ist auch noch nicht freigegeben

**Comment by NCC1701M** [comment]
@leonsio Dann sollte es auch noch nicht in der Doku erscheinen!
Wann ist die Fertigstellung geplant?

**Comment by leonsio** [comment]
da steht auch nix davon, dass es geht, auf der Readme in der ersten Seite steht eigentlich dass die Unterstützung noch nicht realisiert wurde..

falls du aber auf den develop brunch wechselst, da sind die Schritte beschrieben und du kannst die Unterstützung aktivieren..

**Comment by NCC1701M** [comment]
Aber in der Problembeschreibung steht was zu machen ist

![image](https://cloud.githubusercontent.com/assets/7260053/26238708/85762530-3c7a-11e7-8d08-244fa38d9d66.png)

**Comment by jp112sdl** [comment]
Das bezieht sich aber auf die FW des Funkmoduls. 
Die kann entweder von RaspberryMatic geflasht worden sein oder auch von YAHM mit aktiviertem HmIP-Support.
Diesen gibt es momentan aber nur im develop-Branch, wie @leonsio auch bereits erwähnt hat.

Also Einsatz auf eigene Gefahr.
