### ISSUE TITLE
Wiki page for manual installation of YAHM Module HM MOD RPI PCB contains an error

### ISSUE THREAD

**Issue by pkugler** [leonsio/YAHM#112]
The wiki page for the YAHM Module: HM MOD RPI PCB contains the listing of the init script, however it is an older version which keeps the reset line active, causing failure of the RF module (until manually started).

PS:
I had to use these instructions as the module script (main branch) did not work on my Pi (v1) with Jessie.

**Comment by leonsio** [comment]
the init scipt is actual and working on debian 8, you must run

```bash
insserv nameofyourscript.sh
````
to create systemd entries
