### ISSUE TITLE
wie kann man ein Gerät wieder entfernen

### ISSUE THREAD

**Issue by frankol** [leonsio/YAHM#113]
Hallo,

ich habe ein Gerät /dev/ttyUSB0 an yahm weitergegeben und möchte die Verbindung wieder trennen. Einen expliziten Befehl zum Entfernen habe ich nicht gefunden. Auch das Löschen der Datei im Container klappt nicht, da es neu angelegt wird. In der config Datei sind keine Einträge dazu zu finden.

Danke!

**Comment by leonsio** [comment]
Einfach rausziehen und das Ding verschwindet mit der Zeit

**Comment by frankol** [comment]
:-) danke. 
Ich meinte aber, ich will das Gerät am Host weiterverwenden, jedoch im Container nicht mehr haben..

**Comment by leonsio** [comment]
schau dir dazu manpage von lxc-device an https://linuxcontainers.org/lxc/manpages/man1/lxc-device.1.html
