### ISSUE TITLE
armhwinfo: Raspberri Pi 3 $HARDWARE changed 

### ISSUE THREAD

**Issue by heweiser** [leonsio/YAHM#114]
Hi,

looks like on my newly bought Raspberry Pie the Hardware ID has been changed to BCM2835.

Adapted it in /opt/YAHM/share/tools/arm-board-detect/armhwinfo.sh

    elif [ "$ARCH" = "armv7l" ]; then
        case $HARDWARE in
            # Raspberry Pi
            BCM2709|BCM2835)

Br,
Heiko

**Comment by leonsio** [comment]
is fixen now
