### ISSUE TITLE
Failed to stop dhcpcd.service: Unit dhcpcd.service not loaded.

### ISSUE THREAD

**Issue by strike1205** [leonsio/YAHM#115]
System:
Rapsberry Pi3 mit openHABianPi  7.05.170509 
Ip = 192.168.1.20 static
Release = Raspbian GNU/Linux 8 (jessie)
Kernel = Linux 4.9.0-2-rpi2

 wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quicnstall -
[sudo] password for openhabian: 2017-06-11 21:35:06 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-"1]

Found ARM based distribution
Disable new dhcpcd on Raspbian Jessie
Failed to stop dhcpcd.service: Unit dhcpcd.service not loaded.
An error occurred while processing quickinstall mode. Pleasy try manually installation

Netzwerkkonfiguration Raspi3
### # Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d
auto lo
iface lo inet loopback

auto eth0
allow-hotplug eth0
iface eth0 inet static
address 192.168.1.20
netmask 255.255.255.0
gateway 192.168.1.1
dns-nameservers 192.168.1.1 8.8.8.8 8.8.4.4

Keine Logfiles von YAHM vorhanden

**Comment by leonsio** [comment]
Danke schau es mir die Tage an

**Comment by c-klinger** [comment]
Ich hatte gerade das gleiche Problem. Habe das Script jetzt einfach mal lokal kopiert und testweise mal Zeile 160 `systemctl stop dhcpcd.service` auskommentieren. Installation lief danach problemlos.

Ohne jetzt ein Experte in Bash Scripting zu sein, `systemctl stop dhcpcd.service || true
` sollte das Problem mit dem ggf. nicht geladenen Service aus der Welt schaffen.

**Comment by leonsio** [comment]
Hast du manuelle Installation probiert?
die Logs findest du unter /var/log/yahm zu jedem Befehl gibt es da Log-Output
