### ISSUE TITLE
Automatische Installation von YAHM bricht ab

### ISSUE THREAD

**Issue by romlos** [leonsio/YAHM#116]
Hallo, bei mir bricht die automatische Installation von YAHM wiederholt an der gleichen Stelle ab: Bei "Creating Bridge for networking" friert der RasbPi ein und reagiert nicht mehr. Dieses Verhalten ist reproduzierbar. Hier das komplette Log:

wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
2017-07-07 01:56:10 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
Disable new dhcpcd on Raspbian Jessie
Synchronizing state for dhcpcd.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d dhcpcd defaults
Executing /usr/sbin/update-rc.d dhcpcd disable
insserv: warning: current start runlevel(s) (empty) of script `dhcpcd' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `dhcpcd' overrides LSB defaults (0 1 6).
Updating sources
Installing dependencies
install sendmail
Die E-Mail-Oberfläche benötigt ein installiertes »sendmail«, verwende Pager
bash-completion is installed
wget is installed
install dos2unix
python is installed
git is installed
install lxc
install liblzo2-dev
install bridge-utils
install python-lzo
patch is installed
gzip is installed
openssl is installed
Clean up YAHM directory (removing old versions)
done
Downloading actual version from git repository
Including YAHM into PATH
Installing bash command completion
Done

	Enter quick install mode

	Installing LXC container
	YAHM LXC container was installed successfully

	Creating Bridge for networking

**Comment by jp112sdl** [comment]
Hat dein Pi eine statische oder eine dynamische IP?
Und bist du direkt am Pi mit der Tastatur dran, oder führst du die YAHM-Installation über SSH aus?

**Comment by romlos** [comment]
Der Pi bekommt immer die gleiche IP vom Router zugewiesen. Die YAHM-Installationsversuche habe ich immer über SSH ausgeführt.

**Comment by jp112sdl** [comment]
Hmm, also ich habe es bisher auch immer über SSH gemacht. Allerdings mit statischer IP (direkt in der /etc/network/interfaces)

Die Vermutung liegt nahe, dass beim Erstellen der Bridge durch das Neustarten des DHCP Clients die Netzwerkkonnektivität und somit die SSH Session verloren geht. 
Kannst du dem Pi vorübergehend eine statische IP verpassen?

**Comment by romlos** [comment]
Kann ich bestimmt, wenn ich wüsste wie ;-). Wo und wie soll ich dem Pi denn eine statische IP vergeben?

**Comment by jp112sdl** [comment]
Du editierst die Datei /etc/network/interfaces und machst aus 
`iface eth0 inet dhcp`
ein
`iface eth0 inet static`
`address 192.168.1.10`
`netmask 255.255.255.0`
`gateway 192.168.1.1`
wobei du die IP-Adressen address und gateway aus deinem Netz entsprechend eintragen musst

**Comment by romlos** [comment]
Okay, werde das nach meinem Urlaub angehen. Vielen Dank für die Tipps.

**Comment by BuZZy1337** [comment]
Komischerweise stand bei meinem frisch installierten Raspbian Jessie Light das eth0 Interface immer auf "manual".

Habe
iface eth0 inet manual

geändert auf:
iface eth0 inet dhcp

und keine Probleme bei der manuellen Installation mit "sudo yahm-lxc -f -b 2.27.8 install" gehabt.
(Danke nochmals an @jp112sdl für den Tipp eine ältere Version zu nehmen).
Dann noch die bridge erstellt und bridge angehängt.
Habe zu keiner Zeit die Verbindung verloren.

Habe beobachtet dass wenn ich vorher das eth0 Interface nicht auf "DHCP" setze, dann wird die Bridge auch mit "manual" eingetragen. Und dann gabs Probleme..

**Comment by leonsio** [comment]
Nach den aktuellen Änderungen wird die Bridge erst nach einem Reboot aktiv, da viele Probleme mit der Konnektivität hatten.
Ob du mit -b XXXX oder ohne installierst, macht an der Routine was das Netzwerk angeht keinen Unterschied

**Comment by romlos** [comment]
Hallo, ich habe es letzte Woche dann doch hinbekommen, aber nicht per SSH/WLAN, sondern durch eine Kabelverbindung. Dann lief die Installation problemlos durch. Ärgerlich ist nur, dass nach erfolgreicher Installation von YAHM der RPI die WLAN-Verbindung verliert und es mir nicht mehr gelungen ist, WLAN wieder zu aktivieren.

**Comment by jp112sdl** [comment]
Reicht es nicht, wenn du in der _/etc/network/interface_ beim 
`iface yahmbr0 ...`

aus `bridge_ports eth0` ein `bridge_ports wlan0` machst?
