### ISSUE TITLE
hm-mod-rpi-pcb not working anymore after test with raspberrymatic

### ISSUE THREAD

**Issue by gsternagl** [leonsio/YAHM#117]
I have two YAHM deployments. Both have been working quite well as secondary CCUs. Great work! Recently I've tried out raspberrymatic on one of them and this seems to have flashed my hm-mod-rpi-pcb RFD module with newer firmware. After booting with my YAHM SDcard the module doesn't seem to be recognized anymore and I am getting BidCos errors when trying to pair new homematic devices. It looks like the hm-mod-rpi-pcb firmware was updated by raspberrymatic. I've tried to flash the hm-mod-rpi-pcb firmware with the methods described here: 

http://heinz-otto.blogspot.co.at/2016/07/raspberry-pi-homematic-modul.html

I couldn't get the FHEM flash method to work (or at least I wasn't able to see any difference afterwards). So I tried the flashmoduart method and after several attempts it finally flashed my module. I used this firmware: 

https://raw.githubusercontent.com/eq-3/occu/ee68faf77e42ed5e3641790b43a710a3301cea7e/firmware/HM-MOD-UART/coprocessor_update.eq3

This seems to be v1.4.1 but I am not sure. Anyway the module still doesn't work.

Any hints on which firmware actually works 100% with YAHM and which firmware update method works best ? I think others might also run into this issue more and more so a short description in the Wiki on the firmware would be good.

**Comment by gsternagl** [comment]
ok some more tests with eq3configcmd:

On the system which currently runs raspberrymatic I discovered I have FW-version: 2.8.5
(discovered via "eq3configcmd update-coprocessor -p /dev/mmd_bidcos  -v -c -l 1 -t HM-MOD-UART")

On the system which runs yahm I have firmware version: 1.4.1
(eq3configcmd update-coprocessor -p /dev/ttyAMA0 -v -c -l 1 -t HM-MOD-UART)

Will try to downgrade firmware to version 1.4.1. It would still be great if we can discover why yahm won't work with this newer firmware as I am pretty sure that EQ3 haven't just upgraded it to lock us yahm users out ;-)

**Comment by jp112sdl** [comment]
It's a known issue and has to do with the fact, that the stable YAHM branch does not support HomeMatic IP.

Once you have used RaspberryMatic, it flashes a HomeMaticIP-firmware on the HM-MOD-UART which is not supported by YAHM at the moment.

Please have a look at:
Issue [#94](https://github.com/leonsio/YAHM/issues/94)
Issue [#109](https://github.com/leonsio/YAHM/issues/109)
Issue [#111](https://github.com/leonsio/YAHM/issues/111)

Downgrading the firmware should resolve your problem.

**Comment by gsternagl** [comment]
thanks for the references. I think it would be good to add some information in the Wiki HM-MOD-UART Module section until the issue is fixed by having full Homematic-IP support in YAHM. It might not be obvious for users how to actually do the FW downgrade, with which version and where to get it from.

**Comment by leonsio** [comment]
Just install hm-mod-rpi-pcb and homematic-ip module (with force switch).
after first reboot (new kernel) your should be able to see your module.

alternative, boot inside raspberrymatic und downgrade the firmware to 1.4.x

**Comment by dersimn** [comment]
Trying to downgrade with plain Raspbian, using [Disabling Linux's use of console UART](https://www.raspberrypi.org/documentation/configuration/uart.md) and:

	sudo su
	apt update
	apt install git
	git clone -b b_2_29 https://github.com/eq-3/occu.git
	cd occu
	cp -r firmware /firmware
	cp -r arm-gnueabihf/packages-eQ-3/LinuxBasis/lib/* /lib/.
	cp -r arm-gnueabihf/packages-eQ-3/LinuxBasis/bin/* /bin/.
	cp -r arm-gnueabihf/packages-eQ-3/RFD/lib/* /lib/.
	eq3configcmd update-coprocessor -c -p /dev/ttyAMA0 -d /firmware/HM-MOD-UART -u

Output should be something like:

	root@raspberrypi:/firmware/HM-MOD-UART# eq3configcmd update-coprocessor -c -p /dev/ttyAMA0 -d /firmware/HM-MOD-UART -u
	2017/10/22 14:51:26.322 <Info> Version: 2.8.5

	2017/10/22 14:51:26.325 <Info> Update necessary, installed: 2.8.5, avaiable 1.4.1

	2017/10/22 14:51:50.048 <Info> Firmwareupdate successfull

	root@raspberrypi:/firmware/HM-MOD-UART#

**Comment by leonsio** [comment]
You must install homematic IP module. 
Raspberrymatic updates the firmware to version 2.x with IP support.

**Comment by dersimn** [comment]
Is it possible to downgrade the firmware? My instructions are working so far. Now I'm able to use the module with YAHM (without hmip) again.
