### ISSUE TITLE
hm-mod-rpi-pcb module_install

### ISSUE THREAD

**Issue by hail0** [leonsio/YAHM#118]
Hi zusammen,

die Installation von YAHM an sich hat gut funktioniert.
Wenn ich nun versuche das Modul zu aktivieren, bekommen ich folgende Meldung:

pi@raspberrypi:~ $ sudo yahm-module -m hm-mod-rpi-pcb enable
Executing hm-mod-rpi-pcb module_install()
See Wiki for manual installation
ERROR: This module is for Raspberry Pi only, use -f flag to overwrite this check

Woher kommt der Error in der letzten Zeile?

Danke für die Hilfe,
Hail0

**Comment by jp112sdl** [comment]
Welches Pi-Modell setzt du ein?

**Comment by hail0** [comment]
Hi,

sry hab ich total vergessen oben zu posten.
Habe einen Raspberry Pi 3 Model B im Einsatz.

MFG

**Comment by leonsio** [comment]
Welche raspbian Bzw. Kernel Version?

**Comment by hail0** [comment]
Hi,

anbei die Info´s:
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

MfG

**Comment by leonsio** [comment]
Neuinstallation oder Upgrade?
Hast du homematic-ip Modul installiert?
Du kannst die installation mit -f erzwingen

**Comment by hail0** [comment]
Hi leonsio,

ich hab´s grad auf einer sauberen Neuinstallation nochmals getestet.
Gleiches Spiel. Ich habe bisher noch gar keine Geräte bzw. Software installiert .
Nur Yahm und habe versucht das Modul zu "enablen".
Leider ohne Erfolg. Hat das Modul einen Schuss?

Edit: Mit -f hat die Aktivierung nun funktioniert. Morgen bekomm ich meinen ersten Dimmer zum Testen.
       Ich bin gespannt, ob es dann funktioniert. Ich melde mich morgen wieder.

Mfg

**Comment by leonsio** [comment]
Nein es ist ein problem beim identifizieren der hardware
Wie gesagt einfach mit -f die checks überspringen

**Comment by jp112sdl** [comment]
Was wird denn hinter

```Executing hm-mod-rpi-pcb module_install()```
```Found hardware:```

ausgegeben, wenn du das Modul mit -f aktivierst?

**Comment by hail0** [comment]
Hi jp112sdl,

anbei das Log:

pi@raspberrypi:~ $ sudo yahm-module -m hm-mod-rpi-pcb -f enable
Executing hm-mod-rpi-pcb module_install()
Found hardware:
Trying to disable serial console
Serial already disabled
Preparing devices inside LXC container
Preparing modification rfd.conf...
[Interface 0] block found in rfd.conf checking it...
Modification rfd.conf done.
HM-MOD-RPI-PCB was installed successfully, please restart YAHM to apply changes
Trying to start service
Synchronizing state for hm-mod-rpi-pcb.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d hm-mod-rpi-pcb defaults
Executing /usr/sbin/update-rc.d hm-mod-rpi-pcb enable
STATUS: Module hm-mod-rpi-pcb was successfully installed


MfG

**Comment by leonsio** [comment]
Scheint ohne Fehler durchzulaufen 
Wegen Fehler werde ich morgen schauen

**Comment by jp112sdl** [comment]
Ja, irgendwie fehlt die Ausgabe des gefundenen Modells von "Found Hardware: "...

Gibts vielleicht vom Pi3 B ne neue Rev.?

**Comment by hail0** [comment]
Hi zusammen,

ich habe inzwischen versucht ein erstes Gerät an meiner CCU2 anzulernen.
Leider bekomme ich immer wieder die gleiche Fehlermeldung:
BidCos-RF Anlernmodus konnte nicht aktiviert werden.

Schaut man sich das Log der CCU2 an kommt folgender Eintrag:
Jul 18 16:59:35 homematic-ccu2 user.err rfd: No BidCoS-Interface available

D.h. ja, dass das Modul nicht erkannt wurde.
Hängt das mit der oberen Thematik zusammen?

MfG

**Comment by jp112sdl** [comment]
Hattest du vorher schon mal RaspberryMatic mit dem Funkmodul zu laufen?

**Comment by hail0** [comment]
Nein, habs bisher nur mit YAHM versucht.

**Comment by jp112sdl** [comment]
Dann scheint es Probleme bei der Anpassung der UART-Schnittstelle gegeben zu haben.
Da gibts ja beim Pi 3 noch zusätzliche Anpassungen (je nach Kernel-Version).

Siehe Anpassung Bluetooth (Rpi3):
[UART Anpassungen](https://github.com/leonsio/YAHM/wiki/YAHM-Module:-HM-MOD-RPI-PCB)

**Comment by hail0** [comment]
Hi jp112sdl,

ich habe nun die "pi3-miniuart-bt für Kernel > 4.1 in die Datei /boot/config.txt" eingefügt.
Leider keine Änderung.
Hast noch einen Einfall, den ich testen könnte?
Würde dir das Log aus der CCU weiterhelfen?

Edit: Ich habe gerade Raspberrymatic das Modul zum Laufen bekommen. Irgendwie blöd :-)


MfG und Danke für die Hilfe

**Comment by jp112sdl** [comment]
Hmm... Aber schau mal bei [#124](https://github.com/leonsio/YAHM/issues/124)

Er hatte auch das Problem. Vielleicht kann er dir weiterhelfen, wenn du noch mal dort kommentierst?

Habe leider selbst (noch) keinen Pi3.

Aber wenn es unter RaspberryMatic jetzt läuft, dann musst du in jedem Fall noch mal ein FW-Downgrade machen, falls du wieder zu YAHM wechseln solltest

**Comment by BuZZy1337** [comment]
Hatte gestern genau das gleiche Problem... In der /boot/config.txt muss der Eintrag 
"overlay=pi3-miniuart-bt"
gesetzt werden (ohne Anführungszeichen). Dann komplett den Pi rebooten. Sieht der Eintrag so aus bei dir? Oder hast du vielleicht das overlay= vergessen?

**Comment by BuZZy1337** [comment]
/boot/config.txt meinte ich natürlich... Guten Morgen! :D

**Comment by hail0** [comment]
Hi zusammen bzw. guten Morgen :-)

@jp112sdl: Gibt es irgendwo ein Tut/Guide zum Downgrade vom Funkmodul?
   Stimmt es, dass ich eig. nur eine alte Raspberrymatic Version mit alter Funkmodul Version
   "drüberziehen" müsste für den Downgrade?

@BuZZY1337: Denn Tipp hat mir jp112sdl auch schon gegeben. Trotzdem Danke :-)

Ich versuch heute nach der Arbeit alles erneut zu testen :-)
Mal schauen was dabei rauskommt.

MfG und Danke.

**Comment by leonsio** [comment]
Du musst kein downgrade machen. Installierte einfach das homematic ip Modul Ggf mit Force Switch (-f)

**Comment by BuZZy1337** [comment]
@hail0 ich weiß, wollte nur sicher gehen dass der Eintrag korrekt bei dir drin steht in der Datei.

Habe nämlich schon gelesen das manche Leute einfach nur "pi3-miniuart-bt" (ohne overlay= davor) in die /boot/config.txt geschrieben haben.

Der Eintrag lautet korrekt aber "overlay=pi3-miniuart-bt"

**Comment by jp112sdl** [comment]
@BuZZy1337 muss es ```overlay=``` oder ```dtoverlay=``` heißen?

Wenn ich nach ```pi3-miniuart-bt``` bei Google suche, finde ich nur ```dtoverlay=...```

**Comment by BuZZy1337** [comment]
dtoverlay= natürlich! -.- Meine Güte was ist bloß mit meinem Gedächtnis los.. Sorry!

**Comment by hail0** [comment]
Hi zusammen,

Ich gebs glaub langsam auf :-(
Nach gefühlten 15 Versuchen bekomme ich immer wieder diesen dummen "BidCos-RF Anlernmodus"-Quatsch auf meinem RPI3.

Kurze Übersicht was ich da immer so treibe:

1.)	Raspbian Jessie frisch installiert.
2.)	SSH aktiviert + PW geändert.
3.)	sudo nano /etc/dhcpcd.conf (Statische IP festlegen)
	interface eth0
	static ip_address=192.168.0.XXX/24
	static routers=192.168.0.1
	static domain_name_servers=192.168.0.1
4.)	reboot
5.)	Sudo apt-get update && Sudo apt-get upgrade
6.)	wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E bash -
7.)	sudo yahm-ctl update
8.)	sudo yahm-lxc -f -b 2.27.8 install
9.)	sudo yahm-network -w create_bridge
10.)	 sudo yahm-network attach_bridge
11.)	 sudo yahm-ctl start
12.)	 Sudo yahm-module -m hm-mod-rpi-pcb -f enable
13.)	 sudo yahm-module -f -m homematic-ip disable     (da vorher Raspberrymatic verwendet wurde)
14.)	 /boot/config.txt  -> dtoverlay=pi3-miniuart-bt
15.)	 reboot

Gibts an meiner Vorgehensweise irgendwas zu meckern
oder bin ich einfach nur unfähig :-)

Gruß und vorab ein schönes WE!

**Comment by jp112sdl** [comment]
Ich hab noch eine Idee... Melde ich heut am späten Abend noch mal

**Comment by jp112sdl** [comment]
@hail0 
Eine Idee noch, um erstmal das Funkmodul und die interne Kommunikation zu testen.
Bitte mal den YAHM-LXC-Container stoppen, so dass nur der reine Pi läuft.

Lade dir mal folgendes auf den Pi:
```
git clone git://git.zerfleddert.de/hmcfgusb
cd hmcfgusb/
make
```
Falls ```make``` fehlschlägt, musst du evtl noch die libusb dev installieren:
```
apt-get install libusb-1.0-0-dev
```

anschließend noch die Firmware runterladen:
```
wget https://raw.githubusercontent.com/eq-3/occu/ee68faf77e42ed5e3641790b43a710a3301cea7e/firmware/HM-MOD-UART/coprocessor_update.eq3
```

Und nun kannst du manuell die Firmware auf das Funkmodul flashen:
```
./flash-hmmoduart -U /dev/ttyAMA0 coprocessor_update.eq3
```

Klappt manchmal nicht beim ersten Mal. Ich musste es gerade eben 2 mal versuchen.
Dann kommt eine Ausgabe wie diese hier:

```
root@pi3:~/hmcfgusb# ./flash-hmmoduart -U /dev/ttyAMA0 ~/coprocessor_update.eq3
HM-MOD-UART flasher version 0.103-git

Reading firmware from /root/coprocessor_update.eq3...
Firmware with 43 blocks successfully read.

Initializing HM-MOD-UART...
Invalid checksum received!

ERR> 0x0000: fd 00 00 0d 00                                    .....
calculated: ae27
^C
```
**Versuch fehlgeschlagen, mit Ctrl+C abbrechen... 2. Versuch:**
```
root@pi3:~/hmcfgusb# ./flash-hmmoduart -U /dev/ttyAMA0 ~/coprocessor_update.eq3
HM-MOD-UART flasher version 0.103-git

Reading firmware from /root/coprocessor_update.eq3...
Firmware with 43 blocks successfully read.

Initializing HM-MOD-UART...
HM-MOD-UART opened.

Flashing 43 blocks: |

Firmware update successfull!
```

**Wenn das schon nicht klappt, ist irgendwas mit der Kommunikation Pi<>Funkmodul noch faul (oder overlay bt etc.)**

**Comment by hail0** [comment]
Hi jp112sdl,

ich würde mal behaupten: JACKPOT :-)
Das Flashen hat tatsächlich geholfen. Nun funktioniert alles ohne Probleme.
Vielen Dank für deine/eure Hilfe hier im "Forum".

MfG Hail0
