### ISSUE TITLE
Aufruf von Systemsteuerung - Zentralen-Wartung nicht möglich

### ISSUE THREAD

**Issue by Homekowsky** [leonsio/YAHM#12]
Hard/Software
ODROID XU4 mit Ubuntu 16.04,
CCU2 Firmware Version 2.19.9
HomeMatic RF-LAN Gateway
Backup von YAHM 2.17.16 eingespielt

Fehler trat sofort auf. Danach versucht:
- CuxD Version 1.6 installiert
- meinehomatic - Module enabled
- meine-homematic - Key neu eingespielt
- /var/lib/lxc/yahm/config erweitert um 
  Eintraglxc.hook.autodev = sh -c "modprobe tun; cd ${LXC_ROOTFS_MOUNT}/dev; mkdir net; mknod net/tun c 10 200; chmod 0666 net/tun" 

Fehler ist auf Testsystem (vorher auch 2.17.16) ohne Einspielen eines Backup nachvollziehbar.

**Comment by starfish1107** [comment]
dasselbe Problem hier bei einer Neuinstallation auf Odroid C1 / Debian Jessie / CCU 2.19.9 - Zentralenwartung  graut aus, dann blockiert. (es sind aber offensichtlich nicht nur Odroid betroffen)

**Comment by leonsio** [comment]
ist gefixt, siehe #11
