### ISSUE TITLE
Installation schlägt fehl

### ISSUE THREAD

**Issue by BuZZy1337** [leonsio/YAHM#124]
Hallo Zusammen,

kriege ums verrecken YAHM nicht auf meinem Raspberry 3 installiert.. Weder automatisch noch manuell. :(
Manuell gehe ich so vor:
wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E bash -

sudo yahm-lxc -f install

dann kommt 
sh: 0: Can't open /opt/YAHM/share/scripts/2.29.18.sh

Wo liegt hier das Problem?

Viele Grüße

**Comment by jp112sdl** [comment]
Moin.

1.) Mach mal ein ```sudo yahm-ctl update```
Du hast noch die Skript-Datei mit dem falschen Symlink

2.) 2.29.18 funzt derzeit noch nicht.
Deshalb probier bitte mal ```sudo yahm-lxc -f -b 2.27.8 install```

**Comment by BuZZy1337** [comment]
Danke dafür schonmal! :)

Ist es korrekt, dass nach dem create-bridge command die Interface datei
bei eth0 "manual" eingetragen ist und bei der yahmbr0 "dhcp"?

**Comment by jp112sdl** [comment]
Jap, ist richtig. Es sei denn, du möchtest kein DHCP...

In der Definition von yahmbr0 steht ganz unten (sollte zumindest ;) )
```bridge_ports eth0```
Die Brücke nutzt also das physische Interface eth0 (welches dann keine IP-Konfiguration mehr haben sollte)

**Comment by BuZZy1337** [comment]
Sehr schön, vielen Dank für deine Hilfe. Komme jetzt aufs Webinterface.. Allerdings beim Anlernen kommt die Fehlermeldung "BodCos-RF Anlernmodus konnte nicht aktiviert werden." .. :( Modul ist aktiviert und reboot habe ich mehrfach versucht. ....... Ahhhh Da kein RPI3 automatisch erkannt wurde beim aktivieren vom Modul musste ich noch manuell das bt Overlay in die /boot/config.txt eintragen. Jetzt läuft es!!! DANKE!!! :)
