### ISSUE TITLE
Firmware 2.29.18 Firmware Fenster im WEB GUI leer

### ISSUE THREAD

**Issue by hliebscher** [leonsio/YAHM#126]
Hallo,

nach dem Update kann keine Firmware hochgeladen werden
Fenster im GUI leer
nach Downgrade auf alte Version OK
mfg
Heiko

**Comment by jp112sdl** [comment]
Die Ansicht "Einstellungen"->"Gruppen" dürfte auch leer gewesen sein?

Zum jetzigen Zeitpunkt geht die 2.29.18 nur, wenn das homematic-ip Modul aus dem develop-Branch aktiviert ist (auch wenn man selbst kein HmIP nutzt).

**Comment by hliebscher** [comment]
Ja war so 
Danke

**Comment by leonsio** [comment]
sollte mit aktuellen FW-Version und aktivierten HM-IP gehen
