### ISSUE TITLE
Frage zum HmIP-Modul

### ISSUE THREAD

**Issue by jp112sdl** [leonsio/YAHM#127]
Hi @leonsio 

Eine kurze Frage: Warum wird beim Aktivieren des homematic-ip Moduls der Kernel komplett neu kompiliert, was einige Stunden in Anspruch nimmt?

Bei diesem Kommentar hat jemand lediglich die beiden Kernel-Module kompiliert, was auch zu einem funktionierenden Ergebnis führte.
[tty-Treiber 2.17 HmIP/multimacd für Raspbian Jessie](https://github.com/eq-3/occu/issues/33#issuecomment-274336985)
Wäre es so nicht wesentlich komfortabler?
Oder kannst du kurz erklären, worin der Unterschied besteht?

Danke & Grüße!

**Comment by leonsio** [comment]
Liegt an dem uart/raw Modul er greif auf Schnittstelle zu welches von pl011 Modul belegt ist. Deswegen muss Kernel umgebaut werden

**Comment by dontobi** [comment]
Wie wäre es denn, wenn man eine Paket Quelle anlegt und einen Kernel dort hinterlegt? Dann müsste der Kernel nicht kompiliert werden, sondern müsste nur installiert werden.

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by leonsio** [comment]
Falls du dich bereit erklärst jeweils aktuellen Kernel als deb Paket zur Verfügung stellen und für die Aktualität sorgen, kann ich dies gern einbinden. ich habe dazu weder zeit noch lust.
wer eine out of the box Lösung möchte, greife doch bitte zu Rapsberrymatic.
YAHM ist dazu gedacht auf einem bestehenden Debian/Raspberry PI in einer abgeschotteten Umgebung CCU zum laufen zu bringen. Ich habe auf meinem Rapsi noch diverse andere Sachen laufen. Bei Raspberrymatic hast du dein Raspi dediziert für OCCU abgestellt, da reicht es aus Kernel ein Mal im Jahr zu aktualisieren

**Comment by jp112sdl** [comment]
@leonsio 
Ja, das kann ich nachvollziehen.

Wäre es nicht auch möglich, wie zu Anfang geschrieben, nur die beiden Module (eq3_char_loop und bcm2835_raw_uart) zu kompilieren und das pl011 Modul zur Laufzeit / beim Booten zu entladen?

Der Workaround aus dem Link von oben funktionierte bei mir, auch ohne Neukompilieren des Kernels.

Ich hatte auch nichts von pl011 mit lsmod gesehen.
Vielleicht weil ich mit `dtoverlay=pi 3-disable-bt` Bluetooth komplett deaktiviert habe?

**Comment by leonsio** [comment]
Genau das ist ja das Problem pl011 ist fest in das Raspberry Kernel einkompiliert, den weg zu bekommen geht nur durch das neubacken des kernels.
somit nutzt es wenig die Module von eq3 zu kompilieren, die werden nicht laufen so lange pl011 läuft
alternative wäre eventuell device tree, ich habe aber keine Zeit mich damit auseinander zu setzen

lsmod zeigt nur shared modules, also das was als .ko datei vorliegt und dynamisch nachgeladen werden kann, festeinkompilierte Module werden auf diese Weise nicht angezeigt.

entweder
```
zcat /proc/config.gz | grep CONFIG_SERIAL_AMBA_PL011
```

oder 

```
dmesg | grep -i uart
```

Da siehst du ob pl011 geladen wurde und es hat auch nix mit BT/Wifi zu tun, es ist etwas andere Baustelle
