### ISSUE TITLE
Installation auf Cubietruck bleibt hängen

### ISSUE THREAD

**Issue by coyote1** [leonsio/YAHM#13]
- Cubietruck 3
- Armbian_5.10_Cubietruck_Debian_jessie_4.5.2 

Die Installation von YAHM bleibt hängen bei "Creating Bridge for Networking", läuft aber anscheinend trotzdem durch, denn die CCU2 Software ist erreichbar.

Nach reboot des Cubietrucks ist jedoch keine ssh Verbindung mehr möglich.
![yahm](https://cloud.githubusercontent.com/assets/19485543/15419513/abe8fd92-1e66-11e6-9390-2d33bcbd96de.png)

**Comment by leonsio** [comment]
Hi da musst du glaube ich manuell ran
1. yahm-lxc install
2. yahm-network create_bridge (WICHTIG ohne -w)
   Dessen Ausgabe brauche ich.
   zusätzlich brauche ich Ausgabe von /etc/network/interfaces 

Diese ist die Netzwerk Konfig vor und nach dem Bearbeiten, ich nehme an, Cubie beschwert sich dass da **auto eth0** noch drin steht.

Du kommst leider nicht mehr auf Host drauf, entweder neuinstall oder die SD Karte am Rechner Mounten und aus /etc/network/interfaces  -> auto eth0 entfernen

(ist nur eine Vermutung)

Gruß

Leo

**Comment by starfish1107** [comment]
hier zeigt sich genau dasselbe Problem, allerdings mit odroid c1. Der Host ist nicht mehr erreichbar aber  CCU2 läuft.
Ich habe die SD-karte auf meinem Hauptrechner gemounted und interfaces angeschaut. 
Da steht nichts von auto eth0   aber auto yahmbr0 (oder ähnl.)  soll ich diese Zeile löschen?

**Comment by leonsio** [comment]
zeig mal die Datei (Interfaces)
welches Betriebssystem verwendest du wahrscheinlich Armbian? lässt sich irgendwo die Version bestimmen? 

```
cat /etc/*-release
```

dann kann ich dafür ein fix einbauen

**Comment by leonsio** [comment]
Probiert mal ob es nun geht

**Comment by coyote1** [comment]
Problem besteht bei mir weiterhin

**Comment by leonsio** [comment]
hast du vorher yahm-ctl update aufgerufen?

bitte vor der Installation **cat /etc/network/interfaces** und die Ausgabe hier posten
danach bitte eine manuelle installation auswählen und führe **yahm-network create_bridge** aus. poste bitte davon die Ausgabe

**Comment by coyote1** [comment]
Nein, habe nicht yahm-ctl update aufgerufen. Ich habe komplett neu installiert. SD Karte nochmal neu aufgesetzt und dann das Automatik Script von YAHM durchlaufen lassen.

Ok. Mache alles nochmal neu und poste die Ausgaben

**Comment by leonsio** [comment]
Hab vor ner Stunde Update gemacht, falls du es davor installiert hast hattest du die Änderungen nicht drin

Bzr. ich schau ob die Datei /etc/armbian.txt existiert, kannst du dies bitte prüfen und zusätzlich die Ausgabe von 

```
cat /etc/*-release
uname -a
cat /proc/version 
```

posten

**Comment by coyote1** [comment]
Hatte die Installation erst nach deinem Post "Probiert mal ob es nun geht" gemacht.

Auf ein neues....

Vor der Installation:

```
### root@cubietruck:~#` cat /etc/network/interfaces
# Wired adapter #1
auto eth0
        iface eth0 inet dhcp
#       hwaddress ether # if you want to set MAC manually
#       pre-up /sbin/ifconfig eth0 mtu 3838 # setting MTU for DHCP, static just: mtu 3838
#
# Wired adapter #2
#auto eth1
#       iface eth1 inet dhcp
#       hwaddress ether # if you want to set MAC manually
#       pre-up /sbin/ifconfig eth0 mtu 3838 # setting MTU for DHCP, static just: mtu 3838
#
# Wireless adapter #1
#auto wlan0
#       iface wlan0 inet dhcp
#       wpa-ssid SSID
#       wpa-psk xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# to generate proper encrypted key: wpa_passphrase yourSSID yourpassword
#
# Local loopback
auto lo
        iface lo inet loopback

```

Werde jetzt manuell probieren

**Comment by leonsio** [comment]
wenn du **yahm-network create_bridge** Achtung OHNE -w aufrufst sollte die neue Interfaces Datei erscheinen

P.S. damit es als Code erkannt wird ``` davor und danach verwenden

**Comment by coyote1** [comment]
root@cubietruck:~# yahm-network create_bridge
Trying to create new bridge yahmbr0 with physical interface eth0
ATTENTION: No changes will be made. Use -d to test or -w flag to write changes
No bridge with choosen name found, continue...
Interface eth0 is physical and valid, continue...
Found dhcp interface configuration on eth0
Preparing network interfaces file
Creating new interface yahmbr0
Please review new network configuration

```
# Wired adapter #1
auto eth0
        iface eth0 inet dhcp
#       hwaddress ether # if you want to set MAC manually
#       pre-up /sbin/ifconfig eth0 mtu 3838 # setting MTU for DHCP, static just: mtu 3838
#
# Wired adapter #2
#auto eth1
#       iface eth1 inet dhcp
#       hwaddress ether # if you want to set MAC manually
#       pre-up /sbin/ifconfig eth0 mtu 3838 # setting MTU for DHCP, static just: mtu 3838
#
# Wireless adapter #1
#auto wlan0
#       iface wlan0 inet dhcp
#       wpa-ssid SSID
#       wpa-psk xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# to generate proper encrypted key: wpa_passphrase yourSSID yourpassword
#
# Local loopback
auto lo
        iface lo inet loopback

auto yahmbr0
iface yahmbr0 inet dhcp
    bridge_ports eth0

```

Your system is not changed, if thesse changes appearing correctly please run this script with -w flag
Clean up

Als Code anzeigen funktioniert irgendwie nicht, zumindest bekomme ich es nicht hin wegen den # Zeichen. Habe sie jetzt durch // ersetzt

Und nun? Wie soll ich weiter machen? yahm-network create_bridge mit -w?

**Comment by leonsio** [comment]
also in dem "code" block hast du nun das generierte Code von yahm-network
mach ein Test, speichere den als /etc/network/interfaces und lösche die Zeile **auto eth0**
dann **service networking restart** sollte alles ohne Probleme gehen

**Comment by leonsio** [comment]
ACHTUNG zurück # setzen !!!!

**Comment by coyote1** [comment]
Was meinst du?
Ich habe die **auto eth0** gelöscht und **service networking restart** gemacht

Und nun?
Muss ich noch was installieren?

Muss ich das noch ausführen?

sudo yahm-network -w create_bridge
sudo yahm-network attach_bridge
 sudo yahm-ctl start

**Comment by leonsio** [comment]
falls dein system danach noch lebt \* g *

sudo yahm-network attach_bridge
sudo yahm-ctl start

und zusätzlich würde ich empfehlen

sudo yahm-module -f -m homematic-ip disable

damit hättest du YAHM am laufen

**Comment by coyote1** [comment]
Na geht doch ;-)

Läuft, CCU2 Software ist da und der Cubie läuft auch noch :-)

Ich hatte jetzt in der Interfaces Datei vor auto eth0 eine # gesetzt. War das jetzt korrekt so?

**Comment by leonsio** [comment]
Ja passt schicke mir noch die notwendigen Daten. Dann kann ich die Änderung für alle veröffentlichten

**Comment by coyote1** [comment]
Ja, gehen gleich raus

**Comment by starfish1107** [comment]
habs gerade wie oben beschrieben durchgespielt - host und ccu laufen nach Entfernen von auto eth0

hier meine Angaben zu 

### odroid c1

das OS-image nennt sich ODROBIAN-Jessie-2.0-vanilla-s805  [http://oph.mdrjr.net/odrobian/#README](url)

```
root@odroid:~# cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

vielleicht etwas aussagekräftiger:

```
root@odroid:~# cat /proc/version
Linux version 3.10.80-20-odrobian (odroid@odroidc1-001e06310984) (gcc version 49.2 (Debian 4.9.2-10) ) #1 SMP PREEMPT Sat Feb 13 10:26:56 AST 2016
root@odroid:~# uname -a
Linux odroid 3.10.80-20-odrobian #1 SMP PREEMPT Sat Feb 13 10:26:56 AST 2016 armv7l GNU/Linux
```

interfaces original

```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp**

```

 interfaces von yahm-network create_bridge

```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto yahmbr0
iface yahmbr0 inet dhcp 
bridge_ports eth0

```

**Comment by leonsio** [comment]
so nun sollte alles gehen, hatte einen Teil vergessen
