### ISSUE TITLE
enabling homematic-ip failed

### ISSUE THREAD

**Issue by Pinkui** [leonsio/YAHM#134]
Hi,

habe einen neuen Raspberry 3 und das Raspian Jessie installiert. Darauf habe ich nun YAHM installiert und ich habe gelesen das für das letzte Firmware 2.29.18 homematic-ip enabled sein muss, auch wenn ich es nicht verwende. Ich habe auf develop-branch umgestellt bekomme aber immer wieder diese Fehlermeldung:

pi@raspberrypi:~ $ sudo yahm-module -f -m homematic-ip enable

!!! You are using develop branch, this branch is unstable. Using at your own risk !!!!

Executing homematic-ip module_install()
Something is wrong, loaded kernel 4.9.35 is newer then last rpi-update () or dpkg () installed versions, own kernel buils are not supported
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
pi@raspberrypi:~ $

Frage: Welche Kernel werden für homematic-ip unterstützt?

**Comment by Pinkui** [comment]
Frage: Welche Kernel werden für homematic-ip unterstützt?

**Comment by leonsio** [comment]
eigentlich "jeder" sofern das System dazu passende source finden kann, führe einfach rpi-update aus, danach sollte es gehen.

aus irgend einem Grund hat das System weder die version über rpi-update, noch über packetmanager rausbekommen

**Comment by Pinkui** [comment]
Mit der 4.9.44 hat es nun geklappt! Danke!
