### ISSUE TITLE
Debian Stretch

### ISSUE THREAD

**Issue by dr-apple** [leonsio/YAHM#135]
Hi ist YAHM schon bereit für Debian Stretch?

**Comment by leonsio** [comment]
Noch nicht 
Bin dran

**Comment by mepi0011** [comment]
Gibt es bereits einen Termin für das Release?
Wie ich in folgendem Chat sehe, bist du bereits fleißig am Umsetzen.

**Comment by leonsio** [comment]
Wahrscheinlich bis Ende kommenden Woche 
Ab dann bin ich für zwei Wochen auf Dienstreise

**Comment by leonsio** [comment]
habe nun bei mir daheim auf debian stretch umgestellt und dabei eine frische Installation vorgenommen
im develop branch sind nun alle Anpassungen dazu vorhanden.

Wichtig, ich habe mit der September Version von Stretch getestet, da gab es ein Paar Änderungen im Netzerk-Interface Bereich

Es funktioniert nun alles, inkl homematic-ip. falls beim ersten Durchlauf irgendwas nicht klappt, einfach das jeweilige Skript erneut ausführen
