### ISSUE TITLE
Wechsel von YAHM zu RaspberryMatic/CCU2

### ISSUE THREAD

**Issue by Hypnos3** [leonsio/YAHM#136]
Aktuell ist es in RaspberryMatic nicht ohne weiteres möglich ein Backup von YAHM einzuspielen. Auch beim einspielen des Backup von YAHM auf eine CCU2 kann es irgendwann zu Problemen kommen.

YAHM passt die Datei /etc/config/no-coprocessor-update und rfd.conf an.

Idee von Jens:
Es sollte die Datei /etc/config/no-coprocessor-update NICHT beim erstellen eines Backups mit speichern sondern (wenn denn gar kein coprocessor update erwünscht ist von YAHM) komplett den Script der das coprocessor firmware update macht überspringen. Des Weiteren sollten die Anpassungen in rfd.conf kompatibel zur CCU2 bzw. RaspberryMatic umgesetzt werden weil das ja Probleme macht.

Von mir aus kann auch eine alternative Methode geschaffen werden. Beispielsweise eine Möglichkeit ein Backup ohne diese beiden Dateien von der Kommandozeile aus erstellen.

Danke

Querverweise:
- Diskussion im Forum:
  - https://homematic-forum.de/forum/viewtopic.php?f=65&t=38513
  - https://homematic-forum.de/forum/viewtopic.php?f=67&t=38409
- unter RasperryMatic https://github.com/jens-maus/RaspberryMatic/issues/131

**Comment by leonsio** [comment]
Hi

ein Wechsel von YAHM zu CCU2 ist ohne weiteres möglich, die Aussage von Jens ist an der Stelle nicht ganz korrekt.

1. die rfd.conf wird NICHT verändert, die Einstellungen sind 100% kompatibel zu CCU2, somit ist an der Stelle kein Handlungsbedarf. Bzgl. "Improved Coprocessor Initialization" muss ich schauen ob dies in den Aktuellen FW-Versionen noch notwendig ist. Bei mir kommt Homematic-IP ohne Probleme hoch, auch nach Rückspielen des Backups auf eine CCU2
2. bzgl. no-coprocessor-update: die Datei ist "harmlos", die bewirkt nur, dass die FW des Moduls nicht automatisch aktualisiert wird und funktioniert ohne Probleme auf CCU2. Somit macht dies aus technischer Sicht keinerlei Probleme auf einer CCU2.

Generell würde ich persönlich empfehlen die FW nicht automatisch zu aktualisieren, gibt genug Fälle wo mit einem FW-Update alles verschlimmbessert wird. Somit sollte ein FW-Update nur durchgeführt werden, wenn dies notwendig ist. 

Ich will möglichst 100% Kompatibilität zu CCU2 gewährleisten und die original-FW nur an den Stellen ändern, wo es zwingend notwendig ist. Somit werde ich an der Backup/Restore Routine von YAHM keine Änderungen vornehmen, ob man die Datei no-coprocessor-update generell anlegt oder nicht, das soll Community entscheiden, ist mir im Prinzip egal. Die kann jeder auch selbständig löschen. 

Und nochmal, ich orientiere mich an der Kompatibilität zu CCU2 und nicht zu RaspberryMatic. Auch werde ich keine Anpassungen vornehmen für Backups von RaspberryMatic auf YAHM bzw. umgekehrt.

Beide Projekte verfolgen an sich das gleiche Ziel, Homematic auf RaspberryPi & Co zum laufen zu bringen, aber haben unterschiedliche Ansätze und auch verschiedene Sourcen.

Sorry aber ich finde keinen Sinn zwischen CCU2/YAHM und RM hin und her zu springen, man solle sich doch bitte für ein System entscheiden YAHM oder RM. beide haben mehr oder weniger Kompatibilität zum Original. 

Für 0815 User ist RaspberryMatic eventuell das einfachere System, will jemand etwas mehr mit dem RaspberryPi anfangen und parallel Homematic betreiben, ist YAHM das passendere System. 

Eine 100% Kompatibilität zwischen dem jeweiligen Alternativen zur CCU2 wird es nicht geben, ihr müsst mit leben, oder einfach beim Original bleiben.

**Comment by Hypnos3** [comment]
Es wäre hinreichend, wenn eine kleine Doku im Wiki vorhanden ist, welche beschreibt, was bei einem Wechsel zu beachten ist.

Danke

**Comment by leonsio** [comment]
ab version 1.9 werden keine YAHM spezifische Änderungen mehr an der RFD Konfiguration vorgenommen, somit ist das Problem aus meiner Sicht gefixt
