### ISSUE TITLE
yahm-ui develop branch abbruch

### ISSUE THREAD

**Issue by ernie76** [leonsio/YAHM#137]
habe gerade yahm geupdatet und jetzt kommt wenn ich die yahm-ui aufrufen will dieser fehler.

/opt/YAHM/share/include.sh: Zeile 48: -is: Kommando nicht gefunden.

es liegt daran das in der include.sh nicht die variable LSB_RELEASE gesetzt wird.
ein 
LSB_RELEASE="/usr/bin/lsb_release"
in der zeile hilft dann.

mfg 
 sven
  scholz

**Comment by Hypnos3** [comment]
gleiches Problem:
![image](https://user-images.githubusercontent.com/12692680/29686787-8db530aa-891a-11e7-8930-6ceacace48dd.png)

Danke für den Fix-Hinweis!

**Comment by leonsio** [comment]
gefixt

**Comment by Hypnos3** [comment]
zur Info:
Falls jemand die Datei angepasst hat muss er jetzt folgendes machen, sonst meckert das update die angepasste Datei an:
`git reset --hard
git pull`
