### ISSUE TITLE
Modul homematic-ip remove

### ISSUE THREAD

**Issue by mnemo70** [leonsio/YAHM#138]
Ich habe Fehler im Modulskript homematic-ip in _module_remove() festgestellt.

Bei Aufruf auf einem frischen Jessie mit neu erzeugten LXC-Container (ohne homematic-ip) passiert nach Aufruf von "sudo yahm-module -f -v -m homematic-ip disable":
...
Extracting jre-7u10
tar: /var/lib/lxc/yahm/root/opt: Not found in archive
...

Im Skript heißt es:
```
progress "Extracting jre-7u10"
tar $VERBOSE -xzf /tmp/ejre-7u10.tgz -C tar ${LXC_ROOT_FS}/opt/
```
Das "tar" hinter -C ist zuviel.

Desweiteren folgt der Fehler:
Downloading old HMServer.jar
curl: (23) Failed writing body (0 != 2759)

In der folgenden Zeile muss bei der Option -o eine Datei angegeben werden, ein Verzeichnis reicht nicht aus. Damit kann man sich dann auch die Option -O sparen.

`curl -sS -o ${LXC_ROOT_FS}/opt/HMServer/ -O -L https://github.com/eq-3/occu/raw/ff030ca119f2597d16a90b01b61dddb2147b6841/HMserver/opt/HMServer/HMServer.jar`

Also:
`... -o ${LXC_ROOT_FS}/opt/HMServer/HMServer.jar -L ...`

Warum wird am Ende noch die Datei /etc/init.d/S62HMServer umbenannt, aber dann eine 61HMServer angelegt? Diese wird dann von init direkt zusammen mit S61rfd ausgeführt. Ist das so beabsichtigt oder sollten beide Versionen mit S62 beginnen?

Ich hoffe, der Fehlerbericht ist so verständlich.

**Comment by leonsio** [comment]
Danke ich schau es mir nochmal an.

**Comment by leonsio** [comment]
hi ich habe nochmal bei mir getestet
das Problem mit "tar" liegt nicht am -C es gibt den Ordner an wo die Dateien entpackt werden sollen
bei dir fehlt anscheinend /var/lib/lxc/yahm/root/opt Verzeichnis, hast du YAHM anders benannt (-n ...)?
bzgl. curl hast du recht, werde ich anpassen

**Comment by mnemo70** [comment]
Hallo, das -C habe ich auch nicht gemeint, sondern das "tar" direkt davor, dass nochmal als Parameter auftaucht. Dadurch stimmt die Syntax nicht.

**Comment by leonsio** [comment]
ah stimmt, habe übersehen
