### ISSUE TITLE
Neuinstallation auf Raspbian Jessie scheitert auf diverse Arten

### ISSUE THREAD

**Issue by sgaechter** [leonsio/YAHM#139]
Hallo zusammen.

Nachdem bei LXCCU schon lange nix mehr gegangen ist bin ich auf YAHM aufmerksam geworden. Doch ich kriege YAHM nicht ans Laufen. Egal was ich versuche, ständig erscheint eine FM.:

`pi@YAHM:~ $ wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
2017-09-04 19:24:16 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5411/5411] -> "-" [1]
Found ARM based distribution
Disable new dhcpcd on Raspbian Jessie
Synchronizing state for dhcpcd.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d dhcpcd defaults
insserv: warning: current start runlevel(s) (empty) of script `dhcpcd' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `dhcpcd' overrides LSB defaults (0 1 6).
Executing /usr/sbin/update-rc.d dhcpcd disable
insserv: warning: current start runlevel(s) (empty) of script `dhcpcd' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `dhcpcd' overrides LSB defaults (0 1 6).
Updating sources (can take some time)
Installing dependencies
sendmail is installed
bash-completion is installed
wget is installed
dos2unix is installed
python is installed
git is installed
lxc is installed
liblzo2-dev is installed
bridge-utils is installed
python-lzo is installed
patch is installed
gzip is installed
openssl is installed
Clean up YAHM directory (removing old versions)
done
Downloading actual version from git repository
Including YAHM into PATH
Installing bash command completion
Done

        Enter quick install mode

        Installing LXC container
An error occurred while processing quickinstall mode. Pleasy try manually installation
pi@YAHM:~ $ sudo  /opt/YAHM/bin/yahm-lxc install
ERROR: We dont have any patches for this version, please call 'yahm-ctl update' and try again
pi@YAHM:~ $ lxc-stop -k -n yahm
yahm is not running
pi@YAHM:~ $ sudo lxc-start -n yahm
lxc-start: Executing '/sbin/init' with no configuration file may crash the host
pi@YAHM:~ $ sudo lxc-info -n yahm
yahm doesn't exist
pi@YAHM:~ $ cd  /var/lib/yahm/
pi@YAHM:/var/lib/yahm $ ls
fw.list  systeminfo
pi@YAHM:/var/lib/yahm $ sudo yahm-lxc remove
ERROR: No container installed
pi@YAHM:/var/lib/yahm $ sudo yahm-lxc -n yahm remove
ERROR: No container installed
pi@YAHM:/var/lib/yahm $ sudo yahm-lxc install
ERROR: We dont have any patches for this version, please call 'yahm-ctl update' and try again
pi@YAHM:/var/lib/yahm $
`

Was genau mache ich falsch?

**Comment by mcb** [comment]
👍 having the same issues

**Comment by leonsio** [comment]
für die aktuelle Version sind im master branch keine Patches verfügbar, bitte develop version verwenden
