### ISSUE TITLE
Anleitung korregieren

### ISSUE THREAD

**Issue by Blackei** [leonsio/YAHM#14]
Hi,
in der Anleitung fürden Umstieg von LXCCU ist der Befehl für das stoppen des alten Dienstes 

lxc-stop -n lxccu 

der Befehl in der Anleitung funktioniert nicht.

**Comment by leonsio** [comment]
lxc-stop -k -n lxccu probiert?  (-k) für Kill oder funktioniert grundsätzlich etwas nicht?

**Comment by coyote1** [comment]
Da muss ich Blackei recht geben. Mit -k funktioniert es nicht. Ohne -k geht.

**Comment by leonsio** [comment]
da ich kein wheezy mehr habe, könnt ihr eventuell etwas beschrieben was da passiert oder fehlt dieser switch beim wheezy-lxc ?

Gruß

Leo

**Comment by coyote1** [comment]
Kann ich jetzt leider auch nicht mehr sagen, da ich den Cubie auf dem wheezy lief gerade plattgemacht habe und auf Jessie nochmal YAHM installiere.
Jedenfalls ging der Befehl nicht mit -k, kann aber nicht mehr sagen, ob da ein Fehler kam.

**Comment by leonsio** [comment]
Habe die Anleitung angepasst
