### ISSUE TITLE
Typo auf der Wiki-Seite zum Homematic IP Module

### ISSUE THREAD

**Issue by patrickhempel** [leonsio/YAHM#141]
Unter [Wiederherstellung HMServer.jar](https://github.com/leonsio/YAHM/wiki/YAHM-Module:-Homematic-IP#wiederherstellung-hmserverjar) steht _Firnware_ statt _Firmware_

> ### Wiederherstellung HMServer.jar
>
> **HINWEIS** Für Firnware zwischen 2.15.5 und 2.17.16

**Comment by leonsio** [comment]
Danke geändert
