### ISSUE TITLE
Homebridge Autostart bleibt hängen und stürzt ab mit Timeout

### ISSUE THREAD

**Issue by mainkowitsch** [leonsio/YAHM#142]
Habe es jetzt schon 2x versucht mit kompletter Neuinstallation.
in dem Autostart-script wird darauf gewartet, dass Rega anwortet.

`else
        echo "Wait for Rega ... zzzZZZ"
        until pids=$(pidof ReGaHss)
        do   
          sleep 1
        done
        echo "Rega is Alive"
        echo "Starting $name"`

Sehe ich das richtig, dass auf einen lokalen Start gewartet wird und da der Prozess in einer virtuellen Maschine startet, er nicht erkannt werden kann?

Habe es erst einmal mit einer 60sek pause mit einer anschließenden Abfrage auf ein Lebenszeichen an meine CCU2 IP-Adresse gelöst. Läuft aber finde das nicht elegant...

**Comment by pi112** [comment]
Hallo mainkowitsch,

würdest du bitte näher erläutern, wie du das gemacht hast? Soweit reichen  leider meine Kenntnisse nicht :-( . Habe zwar was gefunden unter etc/init.d/*homebridge . Glaube aber nicht das du das meinst? 
Vielen Dank für dein Mühe im Voraus.

**Comment by DarthSpawn** [comment]
Ja bitte. Ich hab hier auch immer das selbe Problem. 
Ich konnte das bisher nur durch manuelles Setup des Autostarts lösen, das Autostart Script bei der Modul-Installation über YAHM funktioniert leider nicht. Siehe hier:

https://timleland.com/setup-homebridge-to-start-on-bootup/

**Comment by mainkowitsch** [comment]
hi..

das habe ich im startscript unter /etc/init.d/homebridge geändert/hinzugefügt/bearbeitet
```
case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Wait for YAHM to be started"
        until 
          echo "nur noch 60 Sekunden bis zur Pingüberprüfung"
          sleep 60
          ping -c1 192.168.178.52
        do
          sleep 1
        done

        echo "Rega is Alive"
        echo "Starting $name"
        cd "$dir"
```

ein unschöner workaround aber er funktioniert... es wird halt erst nach 60sek geprüft ob der ping zur VM erfolgreich ist und fertig... ansonsten könnte man auch nur die 60sek pause ohne Prüfung rein machen... geht auch..

**Comment by DarthSpawn** [comment]
@mainkowitsch 
1000x Dank! Ehrlich, was hat mich das in der Vergangenheit geärgert, dass es immer zu einem Timeout kam und ich dann den Spaß von Hand starten musste oder der Status der Komponenten nicht geupdatet wurde.
