### ISSUE TITLE
Fehler bei der automatisierten Installation

### ISSUE THREAD

**Issue by 3PO** [leonsio/YAHM#143]
Die automatische Installation mit Commit https://github.com/leonsio/YAHM/commit/051bc380c2a3ac2e301feb1eab2813827e038daa endet mit der Fehlermeldung:

`An error occurred while processing quickinstall mode. Pleasy try manually installation`

Installlog: https://paste.pound-python.org/show/I5pnhLBNvvMw4hSHuIG6/

Der letzte Eintrag ist in der **"/var/log/yahm/module.log"**

`InterfacesList.xml can not be found, please start yahm first`

module.log: https://paste.pound-python.org/show/0dqWRsAhzxBZ3clyYBC7/

**Comment by leonsio** [comment]
Danke, es fehlt wohl ein Schritt um LXC Container zu starten, damit die Interfaces Datei angelegt wird.

**Comment by leonsio** [comment]
ist nun behoben (develop)
