### ISSUE TITLE
Inhalt der virtuellen SD-Karte geht bei Update verloren

### ISSUE THREAD

**Issue by beamsi** [leonsio/YAHM#147]
Während des updates scheint der Inhalt von /var/lib/lxc/yahm/sd-mmcblk0 nicht gerettet zu werden. Dadurch verliert mach die Historie von allen Diagrammen

**Comment by leonsio** [comment]
werde ich mir ansehen.
aktuell wird die SD Karte bei jedem update "neu" initalisiert, ich sehe zu dass ich die Daten in den backup aufnehme

**Comment by leonsio** [comment]
hi
ab Version 1.9 wird SD Karte nicht mehr beim update/reinstall entfernt, die Daten werden beim neuen System mit dem gleichen Namen angehängt

Inhalt der SD-Karte ist unter /var/lib/yahm/SDcard zu finden

Ich schau ob ih das in das Backup von Homematic aufnehmen kann

**Comment by beamsi** [comment]
Klasse und Danke!
