### ISSUE TITLE
Gruppen - Einstellen Fehler

### ISSUE THREAD

**Issue by neogola** [leonsio/YAHM#148]
Hallo,
ich habe einen raspi3 mit den ELV Funkmodul und aktuellen YAHM mittels quick install installiert und das Funkmodul danach aktiviert. Habe zwei Thermostate (HM-CC-RT-DN) im Wohnzimmer die zusammen geregelt werden sollen und bin wie folgt vorgegangen.
- Thermostate montiert und justieren lassen
- in der ccu2 (yahm) angelernt
- eindeutig benannt 
- gruppe erstellt und beide Thermostate in eine Gruppe

Problem:
- klicke ich Gruppen und auf Bedienen sehe ich keine Infos außer ich klicke auf die einzelnen Thermostate 
[Bild](https://picload.org/view/droiawow/001.png.html)
- unter Gruppen und auf Einstellen erscheint unten eine Fehlermeldung "**An internal error was detected in the service software. The diagnostics are being emailed to the service system administrator (root).**"
[Bild](https://picload.org/view/droiawlr/002.png.html)

Raspian und yahm und ccu2 fw ist alles aktuell und frisch installiert

**Comment by Thias66** [comment]
Hallo zusammen,

selbigen Fehler habe ich seit dem Upgraden auf 2.29.23 bei allen Heizungsgruppen. Vorher waren die Gruppeneinstellung aufrufbar.
Yahm ist aktuell.
Ich habe außer Mail keine Zusatzprogramme installiert Homematic IP ist nicht aktiviert.
Darüber Hinas nutze ich noch pocket control HM.

Vielen Dank im Voraus für eure Hilfe!

**Comment by neogola** [comment]
Hallo Thias66,

danke für die Info dann kann ich mir das neuinstallieren ja schenken und muss einfach abwarten oder kann man einfach auf die Version zuvor downgraden? 
Bin neu hier und außer die zwei Thermostate angelernt hab ich noch nichts gemacht.

Grüße und Danke

**Comment by kurtwithslc** [comment]
Hallo zusammen, 
downgrade auf 2.27.8 half bei mir

**Comment by neogola** [comment]
@kurtwithslc 
hast du dazu eine Anleitung bzw kurzes Howto? Hab im Wiki dazu nichts gefunden.

**Comment by kurtwithslc** [comment]
Hallo neogola,

als Erstes ein homematic backup machen (homematic Einstellungen > Sicherheit > Backup erstellen)

dann via ssh auf dem raspberry einloggen und das update / den downgrade starten mit

sudo yahm-lxc -n yahm -f -v -b 2.27.8 update

Wenn das durchgelaufen ist, sollte homematic mit Version 2.27.8 laufen

Weitere Tipps dazu im Wiki unter https://github.com/leonsio/YAHM/wiki/YAHM-LXC#update

LG Kurt

**Comment by Thias66** [comment]
Ich habe heute auf eine zweitem Raspi RaspberryMatic installiert. Das ist die selbe CCU Version, dort tritt der Fehler nicht auf.
LG
Matthias

**Comment by ghost** [comment]
Gibt es hier schon was Neues?
Habe das gleiche Problem in meiner YAHM 2.29.23 Installation.
Vielen Dank für eure Hilfe!

**Comment by leonsio** [comment]
siehe folgenden Thread
https://homematic-forum.de/forum/viewtopic.php?f=67&t=40604
dort steht eine Lösung, falls nicht hilft melde dich ncohmal

**Comment by no01n** [comment]
Hallo Danke für den Hinweis auf den Thread.
Ich bin auch dem Thread viewtopic.php?f=67&t=40212
<https://homematic-forum.de/forum/viewtopic.php?f=67&t=40212> gefolgt
leider
hänge ich jetzt bei folgenden Problem:
Bei
yahm-module -f -m pivccu-driver enable

Bekomme ich den folgenden Fehler bei Bau der eq3 Module:
Building eq3 kernel modules
make -C /lib/modules/4.9.67-v7+/build M=/tmp/tmp.7B2HTmQpj9/kernel modules
make[1]: *** /lib/modules/4.9.67-v7+/build: No such file or directory.
Stop.
Makefile:16: recipe for target 'all' failed
make: *** [all] Error 2
cp: cannot stat ‘*.ko’: No such file or directory

Rpi-update etc hab ich schon durchgeführt. Auch habe ich schon yahm
komplett neu geladen. (Devel) Beim Bau des Moduls kommt aber immer wieder
der Fehler.

Vielen Dank für die Hilfe.




Am 7. Dezember 2017 um 10:10 schrieb Leonid Kogan <notifications@github.com>
:

**Comment by ghost** [comment]
Vielen Dank für den Tipp. 
Mit einem neuen Raspbian Stretch Image hat die "pivccu-driver" Installation funktioniert.
Allerdings funktionieren die Gruppen leider immer noch nicht.
