### ISSUE TITLE
YAHM-Instanz stoppen (z.B. mit crontab)

### ISSUE THREAD

**Issue by Sschhsd** [leonsio/YAHM#150]
Guten Tag zusammen,

ich nutze seit längerer Zeit RaspiBackup, um einen Snapshot von meiner kompletten SD auf meinem Raspberry Pi 3 anzulegen. Im RaspiBackup können die laufenden Service konfiguriert werden, sodass diese vor dem Backup gestoppt und nach dem Backup wieder gestartet werden. Jedoch kann RaspiBackup den Service der CCU2-Instanz (YAHM) mit dem folgende Befehl **sudo yahm-ctl stop** nicht stoppen.

`??? RBK0028E: Befehl service apache2 stop && service mysql stop && service samba stop && sudo yahm-ctl stop hat einen Fehler bekommen.`
`??? RBK0048E: Ein Fehler trat beim Beenden von Services auf. RC 1.`

Deshalb hatte ich die Idee die CCU-Instanz über **crontab** zurvor zu stoppen. Leider auch ohne Erfolg:

`pi@raspberrypi:~ $ tail -f /var/log/syslog | grep CRON`
`Nov 17 17:48:01 raspberrypi CRON[29606]: (pi) CMD (sudo yahm-ctl stop)`

Im Log wird der Befehl zwar angezeigt, aber die CCU2-Instanz (YAHM) läuft weiter.

Wie kann die CCU2-Instanz über crontab oder raspiBackup gestoppt werden?
Gibt es einen echten Service der gestoppt werden kann (alternative zum Befehl sudo yahm-ctl stop).

Es gibt noch die Möglichkeit den Container über **lxc-stop -n yahm** zu stoppen, aber wird die CCU2-Instanz dabei sauber heruntergefahren oder der Prozess einfach gekillt?

**Comment by leonsio** [comment]
hi

yahm-ctl stop macht nichts anderes als LXC Befehl auszuführen, somit kannst du den Befehl nutzen
Wird yahm gestoppt wenn du den Befehl einzeln ausführst und nicht die komplette kette mit apache2/mysql usw? ggf. liegt das Problem wo anders

**Comment by Sschhsd** [comment]
Hallo leonsio,

ne, leider funktioniert der Befehl **sudo yahm-ctl stop** mit raspiBackup nicht.

Ich lasse nun die Services per Skript zuvor stoppen (YAHM mit **sudo lxc-stop -n yahm**).

Der Prozess wird mit diesem Befehl (**sudo lxc-stop -n yahm**) aber sauber heruntergefahren (Hinweis: Regadom), oder :)?
