### ISSUE TITLE
Internes Netzwerk

### ISSUE THREAD

**Issue by Doccos** [leonsio/YAHM#152]
Ist es möglich auf dem Raspberry ein internes Netzwerk für Yahm zu erstellen ?
und von außen per IPTables an den Container zu NATen ?

ich habe versucht ein virtuelles netzkwer zu erstellen aber es hat leider nicht funktioniert.

versuch mit 
auto vmbr1
iface vmbr1 inet static
        address 192.168.30.1
        netmask 255.255.255.0

jedoch startet das interface nicht

**Comment by leonsio** [comment]
also du kannst schon internes Netzwerk anlegen
kannst du von raspi aus auf die CCU zugreifen und pingen?

**Comment by Doccos** [comment]
///edit 
jetzt hab ich nur mehr das problem der CCU eine Ip zu geben, im Virt Network läuft ja kein dhcp
//edit

hab an die /var/lib/lxc/yahm/config.network  folgendes noch angefügt:
`lxc.network.ipv4 = 192.168.30.10/24`

und in folgender datei: /var/lib/lxc/yahm/root/usr/local/etc/config/netconfig 
ip adressen angepasst

```

/etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp


auto yahmbr0
iface yahmbr0 inet static
  address 192.168.30.1
  netmask 255.255.255.0
  bridge_ports none
  post-up /opt/bridgeup
```

/opt/bridgeup

```
#!/bin/sh
braddr=192.168.30.1
iptables -A FORWARD -i yahmbr0 -s ${braddr}/24 -m conntrack --ctstate NEW -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A POSTROUTING -t nat -j MASQUERADE
iptables -t nat -A PREROUTING -p tcp --dport 8080 -i eth0  -j DNAT --to 192.168.30.10:80
```


ich glaub nun funktioniert es, hoffe nur bei einem Update wird nicht alles überschrieben
`

**Comment by leonsio** [comment]
Wenn die Eigenständig weiter laufen sollen. Gib denen einfach eine feste IP im gleichen Subnet ;)

Von meinem iPhone gesendet
