### ISSUE TITLE
Fehlermeldungen bei der graphischen Installation ?

### ISSUE THREAD

**Issue by dr-apple** [leonsio/YAHM#154]
pi@raspberrypi:~ $ wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s ui -
2017-12-23 16:52:38 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [6272/6272] -> "-" [1]
Found ARM based distribution
Updating sources (can take some time)
Installing dependencies
sendmail is installed
bash-completion is installed
wget is installed
dos2unix is installed
python is installed
git is installed
lxc is installed
liblzo2-dev is installed
bridge-utils is installed
python-lzo is installed
patch is installed
gzip is installed
openssl is installed
Clean up YAHM directory (removing old versions)
done
Downloading actual version from git repository
Including YAHM into PATH
Installing bash command completion
Done

	Enter UI mode

/opt/YAHM/share/tools/arm-board-detect/armhwinfo.sh: Zeile 219: Warnung: command substitution: ignored null byte in input
cat: /var/lib/lxc/yahm/root/boot/VERSION: Datei oder Verzeichnis nicht gefunden
Welcome to YAHM-UI

**Comment by dr-apple** [comment]
Sind die letzten Meldungen normal ?

**Comment by leonsio** [comment]
Warnungen sind normal ich versuche es zu fixen

Von meinem iPhone gesendet

**Comment by leonsio** [comment]
fixed
