### ISSUE TITLE
etliche Servicemeldungen/ kein Gerät mehr erreichbar

### ISSUE THREAD

**Issue by raintausdu** [leonsio/YAHM#156]
Hallo -

ich habe auf der CCU Servicemeldungen von allen Geräten. Kein Gerät ist mehr über die Weboberfläche zu steuern. 

Ich habe vor gut 2 Stunden deshalb alles auf einer ersatz SD Karte neuinstalliert und das CCU2 Backup eingepielt - nach knapp 60 Minuten kamen die Servicemeldungen wieder. 

Was kann ich tun?
Danke schon mal

**Comment by leonsio** [comment]
Hi

Du musst die logs beachten. Ggf Duty Cycle Problem. 
Läuft alles in den ersten 60 Minuten?
An YAHM an sich kann es nicht liegen, wenn überhaupt ist es Funkmodul Problem. 

Gruß

Leo

Von meinem iPhone gesendet

**Comment by raintausdu** [comment]
Hi
Danke für die schnelle Antwort.
Kann ich das irgendwie testen?
Gruß



-------- Ursprüngliche Nachricht --------Von: Leonid Kogan <notifications@github.com> Datum: 06.01.18  15:25  (GMT+01:00) An: leonsio/YAHM <YAHM@noreply.github.com> Cc: raintausdu <ubastian@human-recycling-industry.de>, Author <author@noreply.github.com> Betreff: Re: [leonsio/YAHM] etliche Servicemeldungen/ kein Gerät mehr erreichbar (#156) 
Hi





Du musst die logs beachten. Ggf Duty Cycle Problem. 


Läuft alles in den ersten 60 Minuten?


An YAHM an sich kann es nicht liegen, wenn überhaupt ist es Funkmodul Problem. 





Gruß





Leo





Von meinem iPhone gesendet





> Am 06.01.2018 um 14:34 schrieb raintausdu <notifications@github.com>:


> 


> Hallo -


> 


> ich habe auf der CCU Servicemeldungen von allen Geräten. Kein Gerät ist mehr über die Weboberfläche zu steuern.


> 


> Ich habe vor gut 2 Stunden deshalb alles auf einer ersatz SD Karte neuinstalliert und das CCU2 Backup eingepielt - nach knapp 60 Minuten kamen die Servicemeldungen wieder.


> 


> Was kann ich tun?


> Danke schon mal


> 


> —


> You are receiving this because you are subscribed to this thread.


> Reply to this email directly, view it on GitHub, or mute the thread.


> 




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/leonsio/YAHM","title":"leonsio/YAHM","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/leonsio/YAHM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@leonsio in #156: Hi\r\n\r\nDu musst die logs beachten. Ggf Duty Cycle Problem. \r\nLäuft alles in den ersten 60 Minuten?\r\nAn YAHM an sich kann es nicht liegen, wenn überhaupt ist es Funkmodul Problem. \r\n\r\nGruß\r\n\r\nLeo\r\n\r\nVon meinem iPhone gesendet\r\n\r\n\u003e Am 06.01.2018 um 14:34 schrieb raintausdu \u003cnotifications@github.com\u003e:\r\n\u003e \r\n\u003e Hallo -\r\n\u003e \r\n\u003e ich habe auf der CCU Servicemeldungen von allen Geräten. Kein Gerät ist mehr über die Weboberfläche zu steuern.\r\n\u003e \r\n\u003e Ich habe vor gut 2 Stunden deshalb alles auf einer ersatz SD Karte neuinstalliert und das CCU2 Backup eingepielt - nach knapp 60 Minuten kamen die Servicemeldungen wieder.\r\n\u003e \r\n\u003e Was kann ich tun?\r\n\u003e Danke schon mal\r\n\u003e \r\n\u003e —\r\n\u003e You are receiving this because you are subscribed to this thread.\r\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\r\n\u003e \r\n"}],"action":{"name":"View Issue","url":"https://github.com/leonsio/YAHM/issues/156#issuecomment-355750141"}}}

**Comment by leonsio** [comment]
Hi

Siehe innerhalb von YAHM unter /var/log/messages

Gruß 

Leo

Von meinem iPhone gesendet

**Comment by raintausdu** [comment]
Ok danke


Von unterwegs gesendet...
-------- Ursprüngliche Nachricht --------Von: Leonid Kogan <notifications@github.com> Datum: 06.01.18  16:05  (GMT+01:00) An: leonsio/YAHM <YAHM@noreply.github.com> Cc: raintausdu <ubastian@human-recycling-industry.de>, Author <author@noreply.github.com> Betreff: Re: [leonsio/YAHM] etliche Servicemeldungen/ kein Gerät mehr erreichbar (#156) 
Hi





Siehe innerhalb von YAHM unter /var/log/messages





Gruß 





Leo





Von meinem iPhone gesendet





> Am 06.01.2018 um 16:03 schrieb raintausdu <notifications@github.com>:


> 


> Hi


> Danke für die schnelle Antwort.


> Kann ich das irgendwie testen?


> Gruß


> 


> 


> 


> -------- Ursprüngliche Nachricht --------Von: Leonid Kogan <notifications@github.com> Datum: 06.01.18 15:25 (GMT+01:00) An: leonsio/YAHM <YAHM@noreply.github.com> Cc: raintausdu <ubastian@human-recycling-industry.de>, Author <author@noreply.github.com> Betreff: Re: [leonsio/YAHM] etliche Servicemeldungen/ kein Gerät mehr erreichbar (#156) 


> Hi


> 


> 


> 


> 


> 


> Du musst die logs beachten. Ggf Duty Cycle Problem. 


> 


> 


> Läuft alles in den ersten 60 Minuten?


> 


> 


> An YAHM an sich kann es nicht liegen, wenn überhaupt ist es Funkmodul Problem. 


> 


> 


> 


> 


> 


> Gruß


> 


> 


> 


> 


> 


> Leo


> 


> 


> 


> 


> 


> Von meinem iPhone gesendet


> 


> 


> 


> 


> 


> > Am 06.01.2018 um 14:34 schrieb raintausdu <notifications@github.com>:


> 


> 


> > 


> 


> 


> > Hallo -


> 


> 


> > 


> 


> 


> > ich habe auf der CCU Servicemeldungen von allen Geräten. Kein Gerät ist mehr über die Weboberfläche zu steuern.


> 


> 


> > 


> 


> 


> > Ich habe vor gut 2 Stunden deshalb alles auf einer ersatz SD Karte neuinstalliert und das CCU2 Backup eingepielt - nach knapp 60 Minuten kamen die Servicemeldungen wieder.


> 


> 


> > 


> 


> 


> > Was kann ich tun?


> 


> 


> > Danke schon mal


> 


> 


> > 


> 


> 


> > —


> 


> 


> > You are receiving this because you are subscribed to this thread.


> 


> 


> > Reply to this email directly, view it on GitHub, or mute the thread.


> 


> 


> > 


> 


> 


> 


> 


> —


> You are receiving this because you authored the thread.


> Reply to this email directly, view it on GitHub, or mute the thread.


> 


> 


> 


> 


> 


> 


> 


> 


> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/leonsio/YAHM","title":"leonsio/YAHM","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/leonsio/YAHM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@leonsio in #156: Hi\r\n\r\nDu musst die logs beachten. Ggf Duty Cycle Problem. \r\nLäuft alles in den ersten 60 Minuten?\r\nAn YAHM an sich kann es nicht liegen, wenn überhaupt ist es Funkmodul Problem. \r\n\r\nGruß\r\n\r\nLeo\r\n\r\nVon meinem iPhone gesendet\r\n\r\n\u003e Am 06.01.2018 um 14:34 schrieb raintausdu \u003cnotifications@github.com\u003e:\r\n\u003e \r\n\u003e Hallo -\r\n\u003e \r\n\u003e ich habe auf der CCU Servicemeldungen von allen Geräten. Kein Gerät ist mehr über die Weboberfläche zu steuern.\r\n\u003e \r\n\u003e Ich habe vor gut 2 Stunden deshalb alles auf einer ersatz SD Karte neuinstalliert und das CCU2 Backup eingepielt - nach knapp 60 Minuten kamen die Servicemeldungen wieder.\r\n\u003e \r\n\u003e Was kann ich tun?\r\n\u003e Danke schon mal\r\n\u003e \r\n\u003e —\r\n\u003e You are receiving this because you are subscribed to this thread.\r\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\r\n\u003e \r\n"}],"action":{"name":"View Issue","url":"https://github.com/leonsio/YAHM/issues/156#issuecomment-355750141"}}}


> —


> You are receiving this because you commented.


> Reply to this email directly, view it on GitHub, or mute the thread.


> 




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/leonsio/YAHM","title":"leonsio/YAHM","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/leonsio/YAHM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@leonsio in #156: Hi\r\n\r\nSiehe innerhalb von YAHM unter /var/log/messages\r\n\r\nGruß \r\n\r\nLeo\r\n\r\nVon meinem iPhone gesendet\r\n\r\n\u003e Am 06.01.2018 um 16:03 schrieb raintausdu \u003cnotifications@github.com\u003e:\r\n\u003e \r\n\u003e Hi\r\n\u003e Danke für die schnelle Antwort.\r\n\u003e Kann ich das irgendwie testen?\r\n\u003e Gruß\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e -------- Ursprüngliche Nachricht --------Von: Leonid Kogan \u003cnotifications@github.com\u003e Datum: 06.01.18 15:25 (GMT+01:00) An: leonsio/YAHM \u003cYAHM@noreply.github.com\u003e Cc: raintausdu \u003cubastian@human-recycling-industry.de\u003e, Author \u003cauthor@noreply.github.com\u003e Betreff: Re: [leonsio/YAHM] etliche Servicemeldungen/ kein Gerät mehr erreichbar (#156) \r\n\u003e Hi\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e Du musst die logs beachten. Ggf Duty Cycle Problem. \r\n\u003e \r\n\u003e \r\n\u003e Läuft alles in den ersten 60 Minuten?\r\n\u003e \r\n\u003e \r\n\u003e An YAHM an sich kann es nicht liegen, wenn überhaupt ist es Funkmodul Problem. \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e Gruß\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e Leo\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e Von meinem iPhone gesendet\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e Am 06.01.2018 um 14:34 schrieb raintausdu \u003cnotifications@github.com\u003e:\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e Hallo -\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e ich habe auf der CCU Servicemeldungen von allen Geräten. Kein Gerät ist mehr über die Weboberfläche zu steuern.\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e Ich habe vor gut 2 Stunden deshalb alles auf einer ersatz SD Karte neuinstalliert und das CCU2 Backup eingepielt - nach knapp 60 Minuten kamen die Servicemeldungen wieder.\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e Was kann ich tun?\r\n\u003e \r\n\u003e \r\n\u003e \u003e Danke schon mal\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e —\r\n\u003e \r\n\u003e \r\n\u003e \u003e You are receiving this because you are subscribed to this thread.\r\n\u003e \r\n\u003e \r\n\u003e \u003e Reply to this email directly, view it on GitHub, or mute the thread.\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e —\r\n\u003e You are receiving this because you authored the thread.\r\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e {\"api_version\":\"1.0\",\"publisher\":{\"api_key\":\"05dde50f1d1a384dd78767c55493e4bb\",\"name\":\"GitHub\"},\"entity\":{\"external_key\":\"github/leonsio/YAHM\",\"title\":\"leonsio/YAHM\",\"subtitle\":\"GitHub repository\",\"main_image_url\":\"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png\",\"avatar_image_url\":\"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png\",\"action\":{\"name\":\"Open in GitHub\",\"url\":\"https://github.com/leonsio/YAHM\"}},\"updates\":{\"snippets\":[{\"icon\":\"PERSON\",\"message\":\"@leonsio in #156: Hi\\r\\n\\r\\nDu musst die logs beachten. Ggf Duty Cycle Problem. \\r\\nLäuft alles in den ersten 60 Minuten?\\r\\nAn YAHM an sich kann es nicht liegen, wenn überhaupt ist es Funkmodul Problem. \\r\\n\\r\\nGruß\\r\\n\\r\\nLeo\\r\\n\\r\\nVon meinem iPhone gesendet\\r\\n\\r\\n\\u003e Am 06.01.2018 um 14:34 schrieb raintausdu \\u003cnotifications@github.com\\u003e:\\r\\n\\u003e \\r\\n\\u003e Hallo -\\r\\n\\u003e \\r\\n\\u003e ich habe auf der CCU Servicemeldungen von allen Geräten. Kein Gerät ist mehr über die Weboberfläche zu steuern.\\r\\n\\u003e \\r\\n\\u003e Ich habe vor gut 2 Stunden deshalb alles auf einer ersatz SD Karte neuinstalliert und das CCU2 Backup eingepielt - nach knapp 60 Minuten kamen die Servicemeldungen wieder.\\r\\n\\u003e \\r\\n\\u003e Was kann ich tun?\\r\\n\\u003e Danke schon mal\\r\\n\\u003e \\r\\n\\u003e —\\r\\n\\u003e You are receiving this because you are subscribed to this thread.\\r\\n\\u003e Reply to this email directly, view it on GitHub, or mute the thread.\\r\\n\\u003e \\r\\n\"}],\"action\":{\"name\":\"View Issue\",\"url\":\"https://github.com/leonsio/YAHM/issues/156#issuecomment-355750141\"}}}\r\n\u003e —\r\n\u003e You are receiving this because you commented.\r\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\r\n\u003e \r\n"}],"action":{"name":"View Issue","url":"https://github.com/leonsio/YAHM/issues/156#issuecomment-355752718"}}}

**Comment by raintausdu** [comment]
Hi
ich wollte eine kurze rückinfo geben.
Der duty cycle war das Problem.Nach einiger Zeit sind die Systemmeldungen verschwunden und nicht wieder aufgetaucht.
Danke für die hilfe

Gruß
-------- Ursprüngliche Nachricht --------Von: Leonid Kogan <notifications@github.com> Datum: 06.01.18  16:05  (GMT+01:00) An: leonsio/YAHM <YAHM@noreply.github.com> Cc: raintausdu <ubastian@human-recycling-industry.de>, Author <author@noreply.github.com> Betreff: Re: [leonsio/YAHM] etliche Servicemeldungen/ kein Gerät mehr erreichbar (#156) 
Hi





Siehe innerhalb von YAHM unter /var/log/messages





Gruß 





Leo





Von meinem iPhone gesendet





> Am 06.01.2018 um 16:03 schrieb raintausdu <notifications@github.com>:


> 


> Hi


> Danke für die schnelle Antwort.


> Kann ich das irgendwie testen?


> Gruß


> 


> 


> 


> -------- Ursprüngliche Nachricht --------Von: Leonid Kogan <notifications@github.com> Datum: 06.01.18 15:25 (GMT+01:00) An: leonsio/YAHM <YAHM@noreply.github.com> Cc: raintausdu <ubastian@human-recycling-industry.de>, Author <author@noreply.github.com> Betreff: Re: [leonsio/YAHM] etliche Servicemeldungen/ kein Gerät mehr erreichbar (#156) 


> Hi


> 


> 


> 


> 


> 


> Du musst die logs beachten. Ggf Duty Cycle Problem. 


> 


> 


> Läuft alles in den ersten 60 Minuten?


> 


> 


> An YAHM an sich kann es nicht liegen, wenn überhaupt ist es Funkmodul Problem. 


> 


> 


> 


> 


> 


> Gruß


> 


> 


> 


> 


> 


> Leo


> 


> 


> 


> 


> 


> Von meinem iPhone gesendet


> 


> 


> 


> 


> 


> > Am 06.01.2018 um 14:34 schrieb raintausdu <notifications@github.com>:


> 


> 


> > 


> 


> 


> > Hallo -


> 


> 


> > 


> 


> 


> > ich habe auf der CCU Servicemeldungen von allen Geräten. Kein Gerät ist mehr über die Weboberfläche zu steuern.


> 


> 


> > 


> 


> 


> > Ich habe vor gut 2 Stunden deshalb alles auf einer ersatz SD Karte neuinstalliert und das CCU2 Backup eingepielt - nach knapp 60 Minuten kamen die Servicemeldungen wieder.


> 


> 


> > 


> 


> 


> > Was kann ich tun?


> 


> 


> > Danke schon mal


> 


> 


> > 


> 


> 


> > —


> 


> 


> > You are receiving this because you are subscribed to this thread.


> 


> 


> > Reply to this email directly, view it on GitHub, or mute the thread.


> 


> 


> > 


> 


> 


> 


> 


> —


> You are receiving this because you authored the thread.


> Reply to this email directly, view it on GitHub, or mute the thread.


> 


> 


> 


> 


> 


> 


> 


> 


> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/leonsio/YAHM","title":"leonsio/YAHM","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/leonsio/YAHM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@leonsio in #156: Hi\r\n\r\nDu musst die logs beachten. Ggf Duty Cycle Problem. \r\nLäuft alles in den ersten 60 Minuten?\r\nAn YAHM an sich kann es nicht liegen, wenn überhaupt ist es Funkmodul Problem. \r\n\r\nGruß\r\n\r\nLeo\r\n\r\nVon meinem iPhone gesendet\r\n\r\n\u003e Am 06.01.2018 um 14:34 schrieb raintausdu \u003cnotifications@github.com\u003e:\r\n\u003e \r\n\u003e Hallo -\r\n\u003e \r\n\u003e ich habe auf der CCU Servicemeldungen von allen Geräten. Kein Gerät ist mehr über die Weboberfläche zu steuern.\r\n\u003e \r\n\u003e Ich habe vor gut 2 Stunden deshalb alles auf einer ersatz SD Karte neuinstalliert und das CCU2 Backup eingepielt - nach knapp 60 Minuten kamen die Servicemeldungen wieder.\r\n\u003e \r\n\u003e Was kann ich tun?\r\n\u003e Danke schon mal\r\n\u003e \r\n\u003e —\r\n\u003e You are receiving this because you are subscribed to this thread.\r\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\r\n\u003e \r\n"}],"action":{"name":"View Issue","url":"https://github.com/leonsio/YAHM/issues/156#issuecomment-355750141"}}}


> —


> You are receiving this because you commented.


> Reply to this email directly, view it on GitHub, or mute the thread.


> 




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/leonsio/YAHM","title":"leonsio/YAHM","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/leonsio/YAHM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@leonsio in #156: Hi\r\n\r\nSiehe innerhalb von YAHM unter /var/log/messages\r\n\r\nGruß \r\n\r\nLeo\r\n\r\nVon meinem iPhone gesendet\r\n\r\n\u003e Am 06.01.2018 um 16:03 schrieb raintausdu \u003cnotifications@github.com\u003e:\r\n\u003e \r\n\u003e Hi\r\n\u003e Danke für die schnelle Antwort.\r\n\u003e Kann ich das irgendwie testen?\r\n\u003e Gruß\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e -------- Ursprüngliche Nachricht --------Von: Leonid Kogan \u003cnotifications@github.com\u003e Datum: 06.01.18 15:25 (GMT+01:00) An: leonsio/YAHM \u003cYAHM@noreply.github.com\u003e Cc: raintausdu \u003cubastian@human-recycling-industry.de\u003e, Author \u003cauthor@noreply.github.com\u003e Betreff: Re: [leonsio/YAHM] etliche Servicemeldungen/ kein Gerät mehr erreichbar (#156) \r\n\u003e Hi\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e Du musst die logs beachten. Ggf Duty Cycle Problem. \r\n\u003e \r\n\u003e \r\n\u003e Läuft alles in den ersten 60 Minuten?\r\n\u003e \r\n\u003e \r\n\u003e An YAHM an sich kann es nicht liegen, wenn überhaupt ist es Funkmodul Problem. \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e Gruß\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e Leo\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e Von meinem iPhone gesendet\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e Am 06.01.2018 um 14:34 schrieb raintausdu \u003cnotifications@github.com\u003e:\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e Hallo -\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e ich habe auf der CCU Servicemeldungen von allen Geräten. Kein Gerät ist mehr über die Weboberfläche zu steuern.\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e Ich habe vor gut 2 Stunden deshalb alles auf einer ersatz SD Karte neuinstalliert und das CCU2 Backup eingepielt - nach knapp 60 Minuten kamen die Servicemeldungen wieder.\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e Was kann ich tun?\r\n\u003e \r\n\u003e \r\n\u003e \u003e Danke schon mal\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \u003e —\r\n\u003e \r\n\u003e \r\n\u003e \u003e You are receiving this because you are subscribed to this thread.\r\n\u003e \r\n\u003e \r\n\u003e \u003e Reply to this email directly, view it on GitHub, or mute the thread.\r\n\u003e \r\n\u003e \r\n\u003e \u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e —\r\n\u003e You are receiving this because you authored the thread.\r\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e \r\n\u003e {\"api_version\":\"1.0\",\"publisher\":{\"api_key\":\"05dde50f1d1a384dd78767c55493e4bb\",\"name\":\"GitHub\"},\"entity\":{\"external_key\":\"github/leonsio/YAHM\",\"title\":\"leonsio/YAHM\",\"subtitle\":\"GitHub repository\",\"main_image_url\":\"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png\",\"avatar_image_url\":\"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png\",\"action\":{\"name\":\"Open in GitHub\",\"url\":\"https://github.com/leonsio/YAHM\"}},\"updates\":{\"snippets\":[{\"icon\":\"PERSON\",\"message\":\"@leonsio in #156: Hi\\r\\n\\r\\nDu musst die logs beachten. Ggf Duty Cycle Problem. \\r\\nLäuft alles in den ersten 60 Minuten?\\r\\nAn YAHM an sich kann es nicht liegen, wenn überhaupt ist es Funkmodul Problem. \\r\\n\\r\\nGruß\\r\\n\\r\\nLeo\\r\\n\\r\\nVon meinem iPhone gesendet\\r\\n\\r\\n\\u003e Am 06.01.2018 um 14:34 schrieb raintausdu \\u003cnotifications@github.com\\u003e:\\r\\n\\u003e \\r\\n\\u003e Hallo -\\r\\n\\u003e \\r\\n\\u003e ich habe auf der CCU Servicemeldungen von allen Geräten. Kein Gerät ist mehr über die Weboberfläche zu steuern.\\r\\n\\u003e \\r\\n\\u003e Ich habe vor gut 2 Stunden deshalb alles auf einer ersatz SD Karte neuinstalliert und das CCU2 Backup eingepielt - nach knapp 60 Minuten kamen die Servicemeldungen wieder.\\r\\n\\u003e \\r\\n\\u003e Was kann ich tun?\\r\\n\\u003e Danke schon mal\\r\\n\\u003e \\r\\n\\u003e —\\r\\n\\u003e You are receiving this because you are subscribed to this thread.\\r\\n\\u003e Reply to this email directly, view it on GitHub, or mute the thread.\\r\\n\\u003e \\r\\n\"}],\"action\":{\"name\":\"View Issue\",\"url\":\"https://github.com/leonsio/YAHM/issues/156#issuecomment-355750141\"}}}\r\n\u003e —\r\n\u003e You are receiving this because you commented.\r\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\r\n\u003e \r\n"}],"action":{"name":"View Issue","url":"https://github.com/leonsio/YAHM/issues/156#issuecomment-355752718"}}}
