### ISSUE TITLE
Allgemeine Einstellungen ausgegraut + abhängige Seiten leer in WebUI 2.31.25

### ISSUE THREAD

**Issue by GerNgit** [leonsio/YAHM#162]
Hallo,

drei Versuche auf einem jeweils jungfräulichen System führten sowohl automatisiert als auch manuell installiert zum mehrfach beschrieben Fehler.

Zudem tauchen die Fehler Virtual Devices + HMIP-RF reagieren nicht auf.

Geräte lassen sich ohne Probleme anlernen und konfigurieren.

Vielen Dank vorab.

$ sudo yahm-ctl info
YAHM Version: 1.9
CCU2 Version: 2.31.25

Module information
Module Serial: NEQ1332400
Module Firmware: 1.4.1

LXC container information
Name:           yahm
State:          RUNNING
PID:            683
IP:             192.168.255.44
CPU use:        40.06 seconds
BlkIO use:      41.88 MiB
Link:           veth0S1XJK
 TX bytes:      6.88 MiB
 RX bytes:      1.21 MiB
 Total bytes:   8.09 MiB

$ sudo yahm-module installedInstalled modules:
	pivccu-driver       Driver for HM-MOD-RPI-PCB with Homematic-IP for Raspbian and Armbian

$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

$ uname -a
Linux raspberrypi 4.9.59-v7+ #1 SMP Sun Feb 11 01:22:55 UTC 2018 armv7l GNU/Linux

**Comment by leonsio** [comment]
Aktualisiere die FW auf 2.8.6

YAHM-ctl fw-update 

Von meinem iPhone gesendet

**Comment by GerNgit** [comment]
Vielen Dank, das funktionierte.
Der Richtigkeit halber für andere Leser:

yahm-ctl fw_update 
(Unter- statt Bindestrich)
