### ISSUE TITLE
Probleme da Homegear bereits installiert ist

### ISSUE THREAD

**Issue by Tech4Ever** [leonsio/YAHM#163]
Hi,

ich habe auf meinem RPi3 bereits Homegear installiert, möchte ber nun mal YAHM testen da es HomematicIP kompatibel ist. Ich habe nun einfach mal YAHM installiert, kann aber mein Funkmodul nicht akitivieren, bekomme folgende Fehlermeldung:

```
@openHABianPi:~# yahm-module -m hm-mod-rpi-pcb enable
Executing hm-mod-rpi-pcb module_install()
Found hardware: Raspberry Pi 3
Trying to disable bluetooth on Raspberry Pi 3 to use HM-MOD-RPI-PCB
Trying to disable serial console
Serial already disabled
Preparing devices inside LXC container
Creating symlink /dev/mmd_bidcos...
ln: failed to create symbolic link 'mmd_bidcos': File exists
```

Was kann ich tun?

**Comment by leonsio** [comment]
Welches Modul hast du aktiviert?

Von meinem iPhone gesendet

**Comment by Tech4Ever** [comment]
Das hm-mod-rpi-pcb von ELV.

**Comment by leonsio** [comment]
Ich meine welches YAHM Modul du verwendest ;)



Von meinem iPhone gesendet

**Comment by Tech4Ever** [comment]
Mmh, gute Frage... Ich habe es einfach nach dieser Anleitung installiert https://openhabdoc.readthedocs.io/de/latest/HomeMatic_YAHM/

Also :

`wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E bash -s quickinstall `

Und dann :

`yahm-module -m hm-mod-rpi-pcb enable`

Nun wollte ich :

`yahm-module -m homematic-ip enable`

ausführen und scheitere an og Fehlermeldung..

**Comment by Tech4Ever** [comment]
yahm-module -m homematic-ip enable

Ausführen und scheitere an og Fehlermeldung..

**Comment by leonsio** [comment]
Hi

Bitte pivccu-driver als Modul verwenden. 

Von meinem iPhone gesendet

**Comment by leonsio** [comment]
Füge noch vor enable -f hinzu

Von meinem iPhone gesendet

**Comment by Tech4Ever** [comment]
ok, werde es später ausprobieren und hier berichten.

Nur um sicher zu gehen: nach Installation von YAHM auf meinem RPi3 mit installiertem hm-mod-rpi-pcb Funkmodul kann ich dann Homematic sowie Homematic IP Geräte steuern, richtig? 

Ich lese halt ständig in unterschiedlichen Foren widersprüchliche Aussagen...

**Comment by leonsio** [comment]
Du musst zwischen Hard und Software unterscheiden 

Hardware hm-mod-rpi-pcb Funkmodul kann ab fw 2.0 Homematic IP

YAHM hm-mod-rpi-pcb Modul kann nur homematic 
YAHM pivccu-driver Modul kann beides

Gruß 

Leo

Von meinem iPhone gesendet

**Comment by Tech4Ever** [comment]
> Hardware hm-mod-rpi-pcb Funkmodul kann ab fw 2.0

Ok, Danke für die Info. Jetzt stellt sich mir die Frage, wie bekomme ich die FW Version meines Hardware Moduls heraus und wie update ich es gegebenenfalls? Kannst Du mir da auch nochmal weiterhelfen?

edit: So habe mal versucht meine Version rauszufinden, bekomme folgendes Ergebnis:

```
openHABianPi:~# /opt/YAHM/share/tools/hmgw/hmlangw -V
hmlangw 0.0.2
Copyright (c) 2015 Oliver Kastl
```

Ein Update schlägt leider fehl:

```
openHABianPi:~# /opt/YAHM/share/tools/hmgw/hmlangw -u
Can't open serial port /dev/ttyAMA0!
```

edit2: Ah, habe im Homegear Log noch eine Info gefunden:

`02/04/18 10:36:53.826 Module HomeMatic BidCoS: HM-MOD-RPI-PCB "My-HM-MOD-RPI-PCB": Info: Firmware version: 1.2.1`

Dies bedeutet ja wohl ich benötige zunächst ein FW Update...

**Comment by leonsio** [comment]
Sag mal was treibst du mit dem Funkmodul? Hab im eq3/OCCU kurz gesehen?

Update geht mit eq3configcmd Tool der ccu 
Schau einfach im homematic Forum da gibt es genug Beispiele 
Bin bis Sonntag unterwegs und kann dir kein Befehl liefern. 

Von meinem iPhone gesendet

**Comment by Tech4Ever** [comment]
naja, ich bekomme diese eq3configcmd Tool einfach nicht zum Laufen, vermutlich wegen fehlender Linux Kenntnisse. Habe es bereits über git gecloned und auch install.sh ausgeführt, jetzt komme ich nicht weiter.
Bei Ausführung bekomme ich einen Fehler:

```
./eq3configcmd update-coprocessor -p /dev/ttyAMA0 -c -u -d /opt/hm/firmware
./eq3configcmd: error while loading shared libraries: libeq3config.so: cannot open shared object file: No such file or directory

```
edit: Keine Chance ich geb es auf, ich bekomme dieses Funkmodul nicht auf den aktuellsten Stand, damit hat sich Homematic IP für mich wohl erledigt. Was bleibt ist die Erkenntnis das Linux für mich ein ewiges Ärgernis bleibt...

**Comment by leonsio** [comment]
Bin am we zurück und schicke dir die Befehle

Ist bei YAHM dabei. Musst du Library path setzen. Ist Kleinigkeit kann es aber von unterwegs nicht nachsehen. 

Gruß 

Leo

Von meinem iPhone gesendet

**Comment by Tech4Ever** [comment]
Hallo Leonsio,

erstmal vielen Dank, dass Du trotz Reisetätigkeit stets geantwortet hast!

Ich habe es endlich geschafft meine FW zu aktualisieren!! Das Thema ist somit erledigt. Das Anlernen eines HomematicIP Heizkörperthermostats hat auch bereits geklappt!

Nun bekomme ich allerdings keine Verbindung zu meinem alten Homematic (ohne IP) Rolladenaktor. Muss ich 

`yahm-module -m hm-mod-rpi-pcb enable`

auch noch ausführen (hab ich nämlich noch nicht gemacht nach dem ich ein altes image aufgespielt habe) oder soll der pivccu-driver sowohl Homematic als auch HomematicIP Geräte abdecken?

**Comment by leonsio** [comment]
Der Treiber kann beides. 

Von meinem iPhone gesendet

**Comment by Tech4Ever** [comment]
Super, jetzt klappt alles (musste meinen Rolladenaktor mal resetten). Vielen Dank für die Hilfe!!
