### ISSUE TITLE
Nach Upgrade auf 2.31.25 hängt 10 Minuten in "S62HMServer start". Anschliessend sind kann ich keine Diagramme mehr erzeugen.

### ISSUE THREAD

**Issue by wagner4u** [leonsio/YAHM#164]
Hi,
habe Upgrade von Yahm und CCU auf 2.31.25 gemacht.
Beim Neustart hängt die CCU2 sehr lange (10 Minuten).
Prozessliste ist:
_1_ 25855 25855 25855 ?           -1 Ss       0   0:00 lxc-start --quiet -n yahm -d -L /var/log/yahm/yahm_console.log
25855 30883 30883 30883 ?           -1 Ss       0   0:00  \_ init      
30883 30896 30896 30896 ?           -1 Ss       0   0:00      \_ /bin/sh /etc/init.d/rcS
30896 31367 30896 30896 ?           -1 S        0   0:00      |   \_ /bin/sh /etc/init.d/S62HMServer start
31367 31373 30896 30896 ?           -1 Sl       0   0:08      |       \_ java -Xmx64m -Dlog4j.configuration=file:///etc/config/log4j.xml -Dfile.encoding=ISO-8859-1 -jar /opt/HMServer/HMIPServer.jar /etc/c
31367 31374 30896 30896 ?           -1 S        0   0:00      |       \_ eq3configcmd wait-for-file -f /var/status/**HMServerStarted -p 5 -t 600_**

Danach kann ich zwar soweit alles bedienen, aber die Diagramme fehlen. Ich meine nicht die Daten vor dem Backup, sondern die Diagrammdefinitionen sind weg und in der WebUI  unter Einstellungen/Diagramme kann ich auch keine neuen anlegen!

Im Log lighttpd-error.log finde ich Einträge:
2018-02-17 12:44:08: (mod_proxy.c.1019) establishing connection failed: Connection refused 
2018-02-17 12:44:08: (mod_proxy.c.919) proxy-server disabled: 127.0.0.1 9292 8 
2018-02-17 12:44:08: (mod_proxy.c.1327) no proxy-handler found for: /pages/jpages/diagram/settings 

Habe das Gefühl, dass bei Neustart S62HMServer nicht vollständig durchläuft bzw. auf Fehler läuft und daher bestimmte Funktionen nicht vorhanden sind.
Das Verzeichnis /var/lib/lxc/yahm/sd-mmcblk0 ist vorhanden inkl. Datei .initialised und Verzeichnis measurement.
Bin da ratlos.

**Comment by wagner4u** [comment]
Da ich noch keine Antwort erhalten habe. Habe nun nochmal mit -f -v switch 2.31.25 drüber installiert:
Im Log /var/log/messages im yahm-container folgendes nach Start des Container:
>>>>>>>>>>>>>>>>>>>
_Mar  4 11:57:12 homematic-ccu2 syslog.info syslogd started: BusyBox v1.20.2
Mar  4 11:57:12 homematic-ccu2 user.notice kernel: klogd started: BusyBox v1.20.2 (2018-01-15 15:55:20 CET)
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[84]: specified group 'dialout' unknown
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[84]: specified group 'kmem' unknown
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[84]: specified group 'video' unknown
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[84]: specified group 'lp' unknown
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[84]: specified group 'floppy' unknown
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[84]: specified group 'cdrom' unknown
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[84]: specified group 'tape' unknown
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[87]: inotify_add_watch(6, /dev/mmcblk0, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[87]: inotify_add_watch(6, /dev/mmcblk0p2, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[86]: inotify_add_watch(6, /dev/mmcblk0p1, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[90]: inotify_add_watch(6, /dev/mmcblk0p7, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[89]: inotify_add_watch(6, /dev/mmcblk0p6, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[88]: inotify_add_watch(6, /dev/mmcblk0p5, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[88]: inotify_add_watch(6, /dev/loop0, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[90]: inotify_add_watch(6, /dev/loop2, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[91]: inotify_add_watch(6, /dev/loop3, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[89]: inotify_add_watch(6, /dev/loop1, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[95]: inotify_add_watch(6, /dev/ram0, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[94]: inotify_add_watch(6, /dev/loop7, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[102]: inotify_add_watch(6, /dev/ram4, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[90]: inotify_add_watch(6, /dev/ram13, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[92]: inotify_add_watch(6, /dev/loop5, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[93]: inotify_add_watch(6, /dev/loop6, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[97]: inotify_add_watch(6, /dev/ram11, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[98]: inotify_add_watch(6, /dev/ram12, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[100]: inotify_add_watch(6, /dev/ram2, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[105]: inotify_add_watch(6, /dev/ram6, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[99]: inotify_add_watch(6, /dev/ram15, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[104]: inotify_add_watch(6, /dev/ram5, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[101]: inotify_add_watch(6, /dev/ram3, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[91]: inotify_add_watch(6, /dev/ram14, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[88]: inotify_add_watch(6, /dev/ram10, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[96]: inotify_add_watch(6, /dev/ram1, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[86]: inotify_add_watch(6, /dev/loop4, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[95]: inotify_add_watch(6, /dev/ram8, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[94]: inotify_add_watch(6, /dev/ram9, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.err udevd[89]: inotify_add_watch(6, /dev/ram7, 10) failed: No such file or directory
Mar  4 10:57:12 homematic-ccu2 daemon.info ifplugd(eth0)[162]: ifplugd 0.28 initializing.
Mar  4 10:57:12 homematic-ccu2 daemon.info ifplugd(eth0)[162]: Using interface eth0/4A:49:43:49:79:F4 with driver <veth> (version: 1.0)
Mar  4 10:57:12 homematic-ccu2 daemon.info ifplugd(eth0)[162]: Using detection mode: SIOCETHTOOL
Mar  4 10:57:12 homematic-ccu2 daemon.info ifplugd(eth0)[162]: Initialization complete, link beat detected.
Mar  4 10:57:12 homematic-ccu2 daemon.warn ifplugd(eth0)[162]: Beep failure, disabled.
Mar  4 10:57:12 homematic-ccu2 daemon.info ifplugd(eth0)[162]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
Mar  4 10:57:12 homematic-ccu2 daemon.warn ifplugd(eth0)[162]: client: sysctl: error: 'net.ipv4.tcp_timestamps' is an unknown key
Mar  4 10:57:12 homematic-ccu2 daemon.warn ifplugd(eth0)[162]: client: eth0 carrier detected
Mar  4 11:57:12 homematic-ccu2 user.debug setclock: Try to get time from 192.168.100.1
Mar  4 11:57:12 homematic-ccu2 user.debug setclock: Sun Mar 4 11:57:12 CET 2018
Mar  4 10:57:12 homematic-ccu2 daemon.info ifplugd(eth0)[162]: Program executed successfully.
Mar  4 10:57:12 homematic-ccu2 auth.info sshd[237]: Server listening on 0.0.0.0 port 22.
Mar  4 10:57:12 homematic-ccu2 auth.info sshd[237]: Server listening on :: port 22.
Mar  4 10:57:12 homematic-ccu2 user.info logger: Updating RF Lan Gateway Coprocessor Firmware
Mar  4 10:57:12 homematic-ccu2 user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
Mar  4 10:57:12 homematic-ccu2 user.info update-coprocessor: performGatewayCoproUpdate(): updating NEQ1694391
Mar  4 10:57:14 homematic-ccu2 user.info update-coprocessor: Lan Device Information: Protocol-Version: 1 Product-ID: eQ3-HM-LGW Firmware-Version: 1.1.5 Serial Number: NEQ1694391
Mar  4 10:57:15 homematic-ccu2 user.info update-coprocessor: Lan Device Information: Protocol-Version: 1 Product-ID: eQ3-HM-LGW Firmware-Version: 1.1.5 Serial Number: NEQ1694391
Mar  4 10:57:16 homematic-ccu2 user.debug update-coprocessor: (NEQ1694391) CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in application.
Mar  4 10:57:16 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
Mar  4 10:57:16 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
Mar  4 10:57:16 homematic-ccu2 user.debug update-coprocessor: CCU2CommControllerMod::handleIncomingResponse() System response OK
Mar  4 10:57:16 homematic-ccu2 user.debug update-coprocessor: (NEQ1694391) CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in application.
Mar  4 10:57:16 homematic-ccu2 user.debug update-coprocessor: CoprocessorUpdate::startApplication():Coprocessor entered application.
Mar  4 10:57:17 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
Mar  4 10:57:17 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
Mar  4 10:57:17 homematic-ccu2 user.debug update-coprocessor: CCU2CommControllerMod::handleIncomingResponse() System response OK
Mar  4 10:57:17 homematic-ccu2 user.info update-coprocessor: Version: 1.4.1
Mar  4 10:57:17 homematic-ccu2 user.info update-coprocessor: Coprocessor firmware not necessary.
Mar  4 10:57:17 homematic-ccu2 user.info logger: Updating RF Lan Gateway Firmware
Mar  4 10:57:17 homematic-ccu2 user.info update-lgw-firmware: LAN Gateway Firmware Update...
Mar  4 10:57:17 homematic-ccu2 user.info update-lgw-firmware: Gateway NEQ1694391
Mar  4 10:57:19 homematic-ccu2 user.info update-lgw-firmware: Gateway type is eQ3-HM-LGW-App
Mar  4 10:57:19 homematic-ccu2 user.info update-lgw-firmware: Available Firmware Version:   1.1.5
Mar  4 10:57:19 homematic-ccu2 user.info update-lgw-firmware: Lan Gateway Firmware Version: 1.1.5
Mar  4 10:57:19 homematic-ccu2 user.info update-lgw-firmware: Firmware is up to date
Mar  4 10:57:19 homematic-ccu2 user.info logger: Updating Wired Lan Gateway Firmware
Mar  4 10:57:19 homematic-ccu2 user.info update-lgw-firmware: No gateway found in config file /etc/config/hs485d.conf
Mar  4 11:57:20 homematic-ccu2 user.warn multimac: UpstreamCharConnection could not open master port /dev/eq3loop: No such file or directory
Mar  4 11:57:20 homematic-ccu2 user.warn multimac: UpstreamCharConnection could not open master port /dev/eq3loop: No such file or directory
Mar  4 11:57:21 homematic-ccu2 user.err multimac: HomeMatic Coprocessor detected!!! Please install DualCoPro Firmware
Mar  4 11:57:21 homematic-ccu2 user.warn multimac: FastMacResponder read error: Interrupted system call
_
<<<<<<<<<<<<<<<<<
Insb. die vorletzte Zeile verstehe ich nicht. Habe schon einiges gelesen im Forum. 
Habe pivccu-Treiber installiert.
Beim Start bleibt das Skript S62HMServer immer noch hängen. Nach touch /var/status/HMServerStarted manuell, läuft der Prozess weiter und ich kann die CCU nutzen, nur nicht mit Diagrammen, etc.

Volker

**Comment by leonsio** [comment]
Du musst Firmware aktualisiere 
Siehe yahm-ctl help

Gruß 

Leo 

Von meinem iPhone gesendet

**Comment by wagner4u** [comment]
Oh my god ...
Zu blöd. Ja, einmal udpate mit "yahm-ctl -f -v fw_update" und schon geht wieder alles.
Die Diagramme sind dann auch wieder da, da der boot-Prozess vollständig durchläuft.
Leonsio, vielen Dank !!
