### ISSUE TITLE
Scripts deiver no output / CCU2 not starting

### ISSUE THREAD

**Issue by T1mey** [leonsio/YAHM#166]
Hi, 

after a fresh install on rpi3 the automatic installer has installed everything successful. At least no error visible.

Executing 

 sudo yahm-ctl start /  sudo yahm-ctl info

dellivers no output. None of the scripts do ..

yahm-ui does not open etc..

**Comment by leonsio** [comment]
Do you have enough free space on system left?
Take a look on dmesg maybe you can find some errors

**Comment by T1mey** [comment]
It is a fresh install... on 32GB SD card. 
I just enter the command and the shell is input ready again

**Comment by T1mey** [comment]
even 

root@xxx:/opt/YAHM/bin# ./yahm-ctl info
root@xxx:/opt/YAHM/bin#

have this behaviour. Permissions set to 777.


In dir /opt/YAHM the ouput is if I exceute yahm-ctl info

shell-init: Kann das aktuelle Verzeichnis nicht wiederfinden: getwd: Kann auf das übergeordnete Verzeichnis nicht zugreifen.: Datei oder Verzeichnis nicht gefunden

**Comment by leonsio** [comment]
Please take a look at dmesg or /var/log/messages

Try this:
/opt/YAHM/bin/yahm-ctl info
echo $?

And send me the output (number from 0-255)

**Comment by T1mey** [comment]
/opt/YAHM/bin/yahm-ctl info
echo $?

--> 0

**Comment by T1mey** [comment]
/opt/YAHM/yahm-init is executed as normal

**Comment by T1mey** [comment]
which yahm-ui liefert
/usr/sbin/yahm-ui

da steht auch die richtige links. zb.

yahm-ui -> /opt/YAHM/bin/yahm-ui

**Comment by T1mey** [comment]
So. I reinstalled the rpi3 (2017-11-29-raspbian-stretch-lite.img). 

Executed 

wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -

Last message:

 Attaching network configuration to LXC container
 yahmbr0 was attached to YAHM LXC container


Afterwards still same issues. no startup of ccu2 and scripts return directly after execution without any message or effect.

**Comment by leonsio** [comment]
Hi

Wird bei die die CCU gestartet?

lxc-info -n yahm

Du kannst auf die Console von CCU2 per "lxc-attach -n yahm“ kommen

**Comment by T1mey** [comment]
lxc-info -n yahm

Liefert **yahm doesn't exist**

**Comment by Yattien** [comment]
Das selbe hier. Frische Installation von "Raspbian Stretch Lite". Es wird kein lxc-Container mit automatischem oder manuellem Setup angelegt.

**Comment by leonsio** [comment]
Welche raspbian Version nutzt ihr? 
Von wann ist das Image?

Von meinem iPhone gesendet

**Comment by Yattien** [comment]
Version bei mir ist "Raspbian Stretch Lite"
> Minimal image based on Debian Stretch
> Version: November 2017
> Release date: 2017-11-29
> Kernel version: 4.9

**Comment by T1mey** [comment]
rpi3 (2017-11-29-raspbian-stretch-lite.img)
Kann es sein dass es was mit dem "set -e" zu tun hat ?

**Comment by T1mey** [comment]
wenn ich das auskommentiere laufen zumindest die Skripte wieder.

**Comment by leonsio** [comment]
Hab eine Idee woran es liegen könnte. 
Werde die Tage testen 

Von meinem iPhone gesendet

**Comment by leonsio** [comment]
So Problem müsste gefixt sein

Einfach YAHM neu installieren

wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash - 
Die bestehende CCU2 Installation wird nicht angefasst, falls vorhanden

**Comment by Yattien** [comment]
Sieht gut aus, lädt deutlich mehr (CCU, Kernelsourcen) runter. Danke für den schnellen Fix!

**Comment by T1mey** [comment]
Danke. Hab keinen commit gesehen. Woran lag es ?

Und noch eine zweite Frage... ich habe ein Backup der CCU2 (damals ohne pivccu-driver / mit HMIP).
Wenn ich das nun in einer neuen Installation einspielen möchte fährt die CCU2 nicht mehr hoch.

Gibt es hier Restriktionen?

**Comment by leonsio** [comment]
Hi

An einer Anfrage im anderen Modul. Dies siehst du nicht im YAHM Baum, dieser wird dynamisch nachgeladen. 

Erst ccu installieren. Dann Backup einspielen anschließend Funkmodul aktivieren. 
Falls du schon ccu installiert hast. Einfach nochmal die moduleinstallation durchlaufen lassen. 
Ansonsten /var/lib/lxc/yahm/yahm.log beachten 

Von meinem iPhone gesendet

**Comment by T1mey** [comment]
Danke für den Tipp... Das hat mir Mal ein gutes Stück Zeit gespart. Wollte schon von neuem konfigurieren. Wo find ich denn den Spenden Button ?

**Comment by leonsio** [comment]
Auf der Startseite ;)
Sonst einfach an leon@leonsio.com senden ;)

Von meinem iPhone gesendet

**Comment by T1mey** [comment]
Hi. Musste gerade yahm neu installieren.
Hat soweit alles gepasst.

Hab mein Backup der Version vorher installiert. Ca. Von vor 6 Monaten.

Irgendwie funktionieren die Geräte nicht mehr. Gibt's da evtl. Einen Trick
? Oder muss ich alles von vorne einrichten.

Tim

Leonid Kogan <notifications@github.com> schrieb am Sa., 24. Feb. 2018,
20:10:

**Comment by leonsio** [comment]
Schau in der /boot/config.txt ob da overlay eingetragen wurde
Geht bei manchen in stallationen nicht

**Comment by T1mey** [comment]
Wo soll die genau liegen ?

Im Container

var/lib/lxc/yahm

Und wie heißt der fehlende Eintrag ?





Leonid Kogan <notifications@github.com> schrieb am So., 23. Sep. 2018,
16:57:

**Comment by leonsio** [comment]
Innerhalb des Containers 

Yahm-ctl join

Dann unter /boot/config.txt

**Comment by T1mey** [comment]
Die Datei gibt es im Container gar nicht.
Hab's irgendwie nur auf dem Pi selbst gefunden.

Leonid Kogan <notifications@github.com> schrieb am So., 23. Sep. 2018,
17:06:

**Comment by leonsio** [comment]
Sorry hast recht, ist auf dem raspi zu finden

Siehe dazu auch https://github.com/leonsio/YAHM/issues/178 <https://github.com/leonsio/YAHM/issues/178>

**Comment by T1mey** [comment]
Danke. Hat geklappt !!!

Leonid Kogan <notifications@github.com> schrieb am So., 23. Sep. 2018,
17:15:
