### ISSUE TITLE
Update von YAHM 1.8 zu 1.9 (Änderung des Homematic-IP-Moduls)

### ISSUE THREAD

**Issue by Sschhsd** [leonsio/YAHM#169]
Guten Tag,

ich bin aktuell auf der YAHM-Version 1.8 und nutze das Homematic-IP-Modul.

Ich habe gesehen, dass ab der Version 1.9 eine neue Möglichkeit gibt die Homematic-IP-Endgeräte anzusprechen (Modul: pivccu-driver).

Ich wollte nachfragen, wie der Upgrade-Prozess aussehen würde?

- Deinstallieren des alten Homematic-IP-Moduls (homematic-ip)
- Update Pi Kernel auf aktuelle Version
- Update YAHM auf Version 1.9
- Installieren des neuen Homematic-IP-Moduls (pivccu-driver)

Müssen die Homematic-IP-Endgeräte dabei neu angelernt werden?

Vielen Dank im Voraus.

**Comment by leonsio** [comment]
Hi

Backup über die gui machen. 
Update auf YAHM 1.9
Homematic ip Modul deinstallieren
Pivccu-driver aktivieren

Ob du davor oder danach Update auf neue ccu fw machst ist egal. 

Von meinem iPhone gesendet
