### ISSUE TITLE
YAHM installation auf Debian Jessie schlägt fehl

### ISSUE THREAD

**Issue by tobias112** [leonsio/YAHM#17]
bekomme beim ausführen der Automatikinstallation auf einem Debian Jessie folgende Fehlermeldung:
- bereits ausgeführt als Lösungsversuch: 

apt-get clean

apt-get update

apt-get dist-upgrade

Fehler tritt weiterhin auf:

_**root@debian:/# wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
2016-05-20 23:26:24 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [4405/4405] -> "-" [1]
X86 CPU found, need to install QEMU
Installing dependencies
qemu-user-static is installed
binfmt-support is installed
Updating sources
Installing dependencies
Installing dependencies
install sendmail
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
An error occurred while processing quickinstall mode. Pleasy try manually installation
root@debian:/#**_ 

Manuelle Installation bringt ebenfalls folgende Fehlermeldung:

**_root@debian:/# root@debian:/# wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -
X86 CPU found, need to install QEMU
Installing dependencies
qemu-user-static is installed
binfmt-support is installed
Updating sources
Installing dependencies
Installing dependencies
install sendmail
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
bash: root@debian:/#:_** 

Im /var/log/yahm/ Verzeichnis befinden sich keine logfiles.
Was kann ich tun, bzw. gibt es den Fehler schon?

**Comment by leonsio** [comment]
führe bitte **apt-get install sendmail** aus und schau was da rauskommt

**Comment by tobias112** [comment]
okay, Fehler gefunden. Konnte **_sendmail_** nicht installieren. 

Erst muss man **_exim4_** deinstallieren 👍 
**_apt-get remove exim4 exim4-base exim4-config exim4-daemon-light_**

Danach lässt sich sendmail installieren:
**_apt-get install sendmail_**

Installation von **_YAHM_** läuft danach normal weiter.

**Comment by leonsio** [comment]
hast du Full oder Lite Jessie Installation genommen?
