### ISSUE TITLE
YAHM mit HM Lan Gateway

### ISSUE THREAD

**Issue by Noranius** [leonsio/YAHM#171]
Hallo an alle,
ich suche derzeit nach einem Konzept für die Nutzung von HM mit HM IP. Leider ist derzeit das Funkmodul für den RPI vergriffen (10 Wochen Lieferzeit). Jetzt ist meine Frage: ist es möglich YAHM mit dem Lan Gateway (HM-LGW-O-TW-W-EU) zu betreiben oder wird zwingend das PI-Modul gebraucht?

Gruß Noran

**Comment by leonsio** [comment]
Klar geht das
Einfach lan gw in die gui eintragen
Damit geht aber kein homematic ip, es geht nur mit dem hm ip Stick oder Funkmodul 

Stick + gw geht ebenfalls. 

P.s Stick bei Telekom bestellen kostet zusammengebaut so viel wie bei elv als Bausatz 

Von meinem iPhone gesendet

**Comment by Noranius** [comment]
Danke schön für die schnelle Antwort. Ich habe gerade mal nach dem Stick geschaut. Funktioniert damit auch das normale HomeMatic oder brauche ich letzten Endes zwei Schnittstellen für diese Systeme?

Gruß Noran

**Comment by leonsio** [comment]
Du brauchst leider zwei. 
Nur raspberry Funkmodul unterstützt beides

Von meinem iPhone gesendet
