### ISSUE TITLE
CCU2 nur noch auf englisch

### ISSUE THREAD

**Issue by hanan070893** [leonsio/YAHM#172]
Hallo zusammen
Musste mein Raspi3 neu aufsetzen und habe jetzt die CCU2-Firmware 2.29.23 auf englisch. Hat mir jemand einen Tipp was ich falsch mache.

Danke und liebe Grüsse

**Comment by leonsio** [comment]
https://homematic-forum.de/forum/viewtopic.php?f=26&t=21029

hat nix mit YAHM zu tun
