### ISSUE TITLE
Fake-LAN-GW auch für Homematic-IP möglich?

### ISSUE THREAD

**Issue by nibblerrick** [leonsio/YAHM#175]
Moin moin,

ich möchte anfangen auch IP-Komponenten einzubinden und gerne auf YAHM umsteigen.
Ich würde gerne YAHM virtualisiert auf X86 laufen lassen und die Anbindung über das HM-MOD-RPI-PCB machen. Für nicht-IP-Komponenten sollte das, soweit ich das verstanden habe, möglich sein mit einmal YAHM auf X86 und einem PI mit dem HM-MOD-RPI-PCB als Fake-LAN-GW.
Was ich aber noch nicht herausgefunden habe, ob der PI dann auch als Gateway für die IP-Komponenten fungieren kann. Geht das oder gibt es für dieses Szenario eine andere Möglichkeit?

**Comment by leonsio** [comment]
Hi

Ist leider nicht möglich 
Bleibe lieber nativ bei homematic 

Von meinem iPhone gesendet

**Comment by nibblerrick** [comment]
Also lieber ganz ohne IP-Komponenten?

**Comment by leonsio** [comment]
Ja

Ich würde entweder oder machen. Die sinnvoll verbinden kannst du sowieso nicht. Es muss dann immer etwas als Brücke laufen. Direkte Verknüpfung gibt es nicht. 

Von meinem iPhone gesendet

**Comment by nibblerrick** [comment]
Verbindung/Automatiken laufen bei mir sowieso über openHAB2, das ist also nicht das Problem. EQ3 scheint aber mehr an IP-Komponenten herauszubringen und zu entwickeln, daher wollte ich das integrieren, zum nächsten Winter hin wollte ich ein paar Heizkörperthermostate hinzufügen, da dachte ich dann an die IP-Varianten. Aber dann bleibe ich erstmal bei den nicht-IP-Komponenten, danke!

**Comment by leonsio** [comment]
Auch wenn du Automatisierung mit openhab machst. Kannst du mit homematic nativ eine direkt Verknüpfung zwischen Thermostat und Fenstersensor machen. Was dann auch ohne Zentrale funktioniert. 

Eine Verbindung zwischen homematic ip Thermostat und nativ homematic Fensterkontakt benötigt immer eine zentrale. 

Leider muss ich dir recht geben. Es kommen aktuell vermehrt homematic ip Komponente raus und die teils sinnvolle Erweiterung bzw. Weiterentwicklung haben. Andererseits gibt’s es aktuell mehr nativ homematic Komponenten und das IP Portfolio wird erst aufgebaut. 

Ich bin schon lange deswegen von eq3 enttäuscht. Sobald mehr und mehr Komponenten bei mir den Geist aufgeben wechsle ich auf offenere Protokolle wie knx/enocean. So eine produktpolitik will ich nicht unterstützen 

Gruß 

Leo

Von meinem iPhone gesendet

**Comment by nibblerrick** [comment]
Bisher habe ich nie Komponenten nativ miteinander verbunden, weil wenn OH2 ausfällt läuft sowieso einiges nicht mehr.
Ich habe glücklicherweise in einem guten Teil KNX-Komponenten liegen. Eines muss man dem lassen, es funktioniert schon sehr ordentlich und auch autark. Leider sind die Komponenten immer noch recht teuer und das die für die ETS-Software so viel Geld nehmen... grrr. Wenn die die ETS-Software kostenlos oder zumindest preisgünstig machen würden könnte KNX wohl eine bessere Verbreitung haben.
Mein Problem ist, dass ich in dem Teil um den es jetzt geht an einigen Stellen drahtlose Sachen brauche. Vielleicht sollte ich mich aber dann doch nochmal zu KNX-Funk einlesen.
