### ISSUE TITLE
Quickinstall Error

### ISSUE THREAD

**Issue by tis-cs** [leonsio/YAHM#176]
Hi, 
beim Versuch auf 2.35.15 zu updaten lief mal wieder alles schief, sodass ich alles neu aufsetzen musste. Hier kommt nun der folgende Fehler:

Installing LXC container (can take some time)
ERROR: We dont have any patches for this version, please call 'yahm-ctl update' and try again
An error occurred while processing quickinstall mode. Pleasy try manually installation

Jemand ne Idee?

Danke!

**Comment by leonsio** [comment]
Hi

Führe einfach Setup Skript erneut aus, kann sein dass da etwas schief gelaufen ist

Gruß

Leo

**Comment by tis-cs** [comment]
weiterhin...

`pi@homematic-pi3-ccu2:~ $ sudo wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
2018-07-02 21:51:00 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [6485/6485] -> "-" [1]
Found ARM based distribution
Updating sources (can take some time)..
	..done
Installing dependencies..
bash-completion is installed
wget is installed
dos2unix is installed
python is installed
git is installed
lxc is installed
liblzo2-dev is installed
bridge-utils is installed
python-lzo is installed
patch is installed
gzip is installed
openssl is installed
	..done
Clean up YAHM directory (removing old versions)..
	...done
Downloading actual version from git repository..
	..done
Including YAHM into PATH..
	..done
Installing bash command completion..
	done

	Enter quick install mode

Disable new dhcpcd on Raspbian
Synchronizing state of dhcpcd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable dhcpcd
ATTENTION: For log files see /var/log/yahm

	Installing LXC container (can take some time)
ERROR: We dont have any patches for this version, please call 'yahm-ctl update' and try again
An error occurred while processing quickinstall mode. Pleasy try manually installation`

**Comment by leonsio** [comment]
Hi

Hab grad nachgeschaut, habe noch keine Patches hierzu vorliegen

Werde es heute testen und einbauen

Gruß

Leo

**Comment by leonsio** [comment]
neue Version ist online, mach yahm-ctl update und probiere es erneut
