### ISSUE TITLE
Error create_bridge

### ISSUE THREAD

**Issue by hail0** [leonsio/YAHM#177]
Hi zusammen,

ich habe ein kleines Problem bei der Installation von YAHM.
folgende Schritte habe ich gemacht bisher:

1.) wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -
    --> Läuft ohne Fehler durch
2.) sudo yahm-lxc -b 2.31.25 install
   --> Läuft ohne Fehler durch
3.) sudo yahm-network create_bridge
    Trying to create new bridge yahmbr0 with physical interface eth0
    ATTENTION: No changes will be made. Use -d to test or -w flag to write changes
    No bridge with choosen name found, continue...
    Interface eth0 is physical and valid, continue...
  
      --> Findet keine Bridge?!

Kann da jemand helfen?!

Generelle Frage noch: Mein PI hat als Bootdevice einen USB-Stick und keine SD-Karte mehr.
                                   Könnte das irgendwie noch zu Problemen mit YAHM führen?

Thx für Eure Hilfe!
Gruß hail0

**Comment by leonsio** [comment]
Hi

Was jetzt genau das Problem?
Bei create_bridge prüft der ob bereits eine Bridge mit dem Namen existiert und wenn nicht gehts weiter
Du musst, wie auch im Text steht -w verwenden, um die Konfiguration zu schreiben 
Sonst wird dir am Ende dir Interfaces Datei angezeigt mit den Änderungen, die das System machen würde (aber ohne -w nicht macht)

Nachdem die Bridge angelegt wird, musst du diese mit attach_bridge an das Container anheften.
Die Änderungen werden bei Neustart des Netzwerks (reboot) aktiv

Gruß

Leo

**Comment by hail0** [comment]
Hi,

wie du beschrieben hast habe ich den -w Parameter gesetzt mit folgendem Ergebnis:

pi@raspberrypi:~ $ sudo yahm-network -w create_bridge
New CCU2 firmware: 2.35.15 available, update with 'yahm-lxc update' possible
Trying to create new bridge yahmbr0 with physical interface eth0
ATTENTION: Network configuration will be changed, you may no longer login to the system!!!
No bridge with choosen name found, continue...
Interface eth0 is physical and valid, continue...

Anschließend hab ich einen Reboot gemacht und dann versucht den attach durchzuführen:

pi@raspberrypi:~ $ sudo yahm-network attach_bridge
New CCU2 firmware: 2.35.15 available, update with 'yahm-lxc update' possible
ERROR: Bridge yahmbr0 dont exists.

MfG Hail0

**Comment by leonsio** [comment]
Patches für neue Version sind online

**Comment by selbolder** [comment]
Hallo, wo bekomme ich das Patch? Ich habe auch das Problem, daß mit meinem Raspberry Pi 3 Model B und der letzten Version von Stretch (2018-06-27) die automatische Intallation nicht zum laufen bringe, die manuelle Installation bricht auch bei "sudo yahm-network -w create_bridge" ab.

**Comment by derFunk** [comment]
Hier auch das gleiche Problem, Bridge wird nicht durch `yahm-network create_bridge` angelegt:

```
pi@pihome:~ $ sudo yahm-network -w create_bridge
Trying to create new bridge yahmbr0 with physical interface eth0
ATTENTION: Network configuration will be changed, you may no longer login to the system!!!
No bridge with choosen name found, continue...

Interface eth0 is physical and valid, continue...
pi@pihome:~ $ sudo yahm-network -w attach_bridge
ERROR: Bridge yahmbr0 dont exists.
pi@pihome:~ $
```

- Raspbian GNU/Linux 9 (stretch)
- Raspberry Pi 3 Model B Rev 1.2
- Linux pihome 4.19.49-v7+ #1233 SMP Mon Jun 10 15:55:31 BST 2019 armv7l GNU/Linux

**Comment by leonsio** [comment]
Poste deine interfaces Datei 

Von meinem iPhone gesendet

**Comment by derFunk** [comment]
interfaces ist leer.

```
# interfaces(5) file used by ifup(8) and ifdown(8)

# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'

# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d
```
(Keine configs in interfaces.d).

dhcpcd.conf:
```
# Inform the DHCP server of our hostname for DDNS.
hostname

# Use the hardware address of the interface for the Client ID.
clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
#duid

# Persist interface configuration when dhcpcd exits.
persistent

# Rapid commit support.
# Safe to enable by default because it requires the equivalent option set
# on the server to actually work.
option rapid_commit

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
# Most distributions have NTP support.
option ntp_servers
# Respect the network MTU. This is applied to DHCP routes.
option interface_mtu

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate Stable Private IPv6 Addresses instead of hardware based ones
slaac private

interface eth0
    static ip_address=192.168.2.116
    static routers=192.168.2.1
    static domain_name_servers=192.168.2.1
```

Ich seh's schon: https://github.com/leonsio/YAHM/issues/54
