### ISSUE TITLE
yahm-backup/yahm start: ImportError: No module named 'lsb_release', ...

### ISSUE THREAD

**Issue by gerassimo** [leonsio/YAHM#179]
Yahm lief seit gut einem Jahr problemlos, seit einiger Zeit gibt es die Fehlermeldungen:
pi@Raspi3Arilla:~$ sudo yahm-backup full_backup
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 28, in <module>
    import lsb_release
ImportError: No module named 'lsb_release'
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 28, in <module>
    import lsb_release
ImportError: No module named 'lsb_release'
New CCU2 firmware: 2.35.16 available, update with 'yahm-lxc update' possible
Trying to stop yahm container
Creating new backup from yahm version 2.27.8
tar: yahm/root/tmp/udev/control: socket ignored
tar: yahm/root/tmp/log: socket ignored
STATUS: Backup was successfully created: /tmp/YAHM/yahm_backup-2.27.8.tgz
Please start yahm container with 'sudo yahm-ctl -n yahm start' manually
pi@Raspi3Arilla:~$
pi@Raspi3Arilla:~$
pi@Raspi3Arilla:~$ sudo yahm-ctl -n yahm start
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 28, in <module>
    import lsb_release
ImportError: No module named 'lsb_release'
pi@Raspi3Arilla:~$

**Comment by leonsio** [comment]
schau ob bei dir mit dem Dateisystem alles in Ordnung ist
die Fehlermeldung kommt von lsb_release Anwendung, ggf. das Paket neuinstallieren (DEB)

**Comment by gerassimo** [comment]
Danke!
Dateisystem ist ok, Neuinstallation/Reinstall lsb_release/lsb_core will leider auch nicht (alle "Google-Varianten" probiert). Schau'n mer mal, melde mich.

**Comment by gerassimo** [comment]
So, jetzt hat's geklappt! Danke!
