### ISSUE TITLE
yahm-module -m hm-mod-rpi-pb  -f -v disable funktioniert nicht

### ISSUE THREAD

**Issue by Blackei** [leonsio/YAHM#18]
Hi,

ich hatte / habe leider Probleme mit dem PI3 und dem Funkmodul. Habe es installiert und wollte, weil es nicht funktioniert hat wieder deaktivieren. Nach einer erneuten Installation kam folgendes:
......
Preparing devices inside LXC container
Creating device /dev/ttyAMA0...
Creating symlink /dev/mmd_bidcos...
Creating symlink /dev/ccu2-ic200...
ln: failed to create symbolic link ‘ccu2-ic200’: File exists

Und im rfd.conf sind bei mir jetzt folgende Werte / Einträge doppelt 

[Interface 0]
# [Interface 0]

Type = CCU2
# Type = CCU2

Description = CCU2-Coprocessor
# Description = CCU2-Coprocessor

ComPortFile = /dev/mmd_bidcos
# ComPortFile = /dev/mmd_bidcos

AccessFile = /dev/null
# AccessFile = /dev/null

ResetFile = /dev/ccu2-ic200
# ResetFile = /dev/ccu2-ic200

Der deinstall ist wohl nicht ganz sauber. Werde es nochmal neu aufsetzen....
Das Funkmodul muss doch unter Jessy und nicht im Container installiert werden, oder??!!

**Comment by leonsio** [comment]
Hi

bzgl. Uninstall schaue ich nochmal
Das Modul führt sowohl Änderungen am Container als auch am Host aus siehe [Wiki](https://github.com/leonsio/YAHM/wiki/YAHM-Module:-HM-MOD-RPI-PCB)

und bitte auch den Punkt beachten: https://github.com/leonsio/YAHM/wiki/Problembehandlung#funkmodul-funktioniert-nicht-unter-ccu2

**Comment by Blackei** [comment]
Mit dem Modul war wirklich eine dämliche Frage, sorry...
Mit der Hilfe für das Funkmodul blicke ich nicht durch ;-(

Ich konnte aber "nur" nichts schalten, einer Fehlermeldung aus der CCU kam nicht.

**Comment by leonsio** [comment]
Hattest du auf dem Pi schon riegdnwas gemacht oder ist es eine frische Installation?
explizit hast du manuell serielle Konsole abgeschaltet?

deine RFD.conf sieht gut aus, erscheint unter Einstellungen/Geräte BidCos Service?
schau auf der CCU unter /var/log/messages ob da Fehlermeldungen kommen

**Comment by FabiE88** [comment]
Hallo Zusammen,

habe das gleiche Problem. Installation hat alles funktioniert auf meinen RPI3 aber ich kann keine Geräte anlernen.
z.B. ein Fensterkontakt HM-Sec-SC meldet sich erfolgreich an (laut LED) aber im Posteingang ist kein Gerät !?

Was kann ich tun?

**Comment by hanisoft** [comment]
Ich habe das selbe problem auf meinen pi3. Und zusäzlich hab ich ein ähnliches problem mit dem funk lan adapter. Der lässt sich installieren, aber wen ich ei gerät anlerne verliert er die Verbindung und ist und bleibt dann nicht vrbunden. Auch nach einen neustart nicht.
