### ISSUE TITLE
Netzwerkkonfiguration stimmt nicht

### ISSUE THREAD

**Issue by Hellhero** [leonsio/YAHM#185]
Hi, 
allem voran viele dank für die tolle Arbeit! Ist wirklich super.
Aber ich habe ein Problem: 
Auf meinem Pi3 lief YAHM fast 2 Jahre absolut problemlos, doch seit ich mit Docker mein Openhab und den IOBroker auf dem gleichen Pi zum laufen bringen wollte gibt es nurnoch Probleme. Das hauptsächliche Problem ist, dass der YAHM-LXC-Container keine bzw. eine falsche IP-Adrese bekommt - und zwar immer 192.168.1.255. 
Auf meiner FritzBox! läuft der "normale" dhcp-Server welcher mich mit IP-Adresse aus dem 192.168.150.0/24er Raum versorgt. Das komische ist: manchmal bekommt der Container einer Adresse aus dem Netz - aber aus dem Container kann ich trotzdem keinen Ping in Richtung FritzBox absetzen. 

Hat jemand eine Idee woran das liegen könnte? Oder hat jemand Erfahrungen mit YAHM und Docker auf dem gleichen System ? 

Danke und frohe Weihnachten.

**Comment by JackGruber** [comment]
Hi,

ja kenn die Probleme.
Liegt an der docker installation, das Netzwerk wird dabei modifiziert.
```
sudo iptables -N YAHM_LXC
sudo iptables -A YAHM_LXC -i yahmbr0 -j ACCEPT
sudo iptables -A FORWARD -i yahmbr0 -m conntrack --ctstate NEW -j YAHM_LXC
sudo iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j YAHM_LXC
```

Hab es mit iptables Einträgen wieder zum laufengebracht, aber nicht 100%.
Hab daher einen eigenen PI für CCU und ioBroker aufgesetzt.

**Comment by leonsio** [comment]
Installiere iobroker und openhab in weiteren lxc Instanz. Lxc und docker auf gleichen System ist keine gute Idee. 

Von meinem iPhone gesendet

**Comment by Hellhero** [comment]
Danke euch beiden für die schnellen Antworten, habe es jetzt über die iptables Einträge zum laufen bekommen, werde mich aber in das LXC-Thema noch mal einarbeiten, habe bisher nur Docker-Erfahrung und wollte es deshalb damit umsetzen.
