### ISSUE TITLE
Unterstützung für Debian Buster

### ISSUE THREAD

**Issue by zilon84** [leonsio/YAHM#186]
Hallo,

gibt es aktuell Pläne für die Unterstützung von Debian/ Raspbian Buster? Bzw. was müsste getan werden, damit YAHM unter Buster lauffähig wird?

Danke und VG
Zilon

**Comment by leonsio** [comment]
Hi

Ich habe keine Pläne für. Was läuft unter Buster nicht?
Ich nehme an das höchste was passieren kann ist, dass die Netzwerkeinstellungen nicht funktionieren. Rest müsste laufen

Gruß

Leo

Von meinem iPhone gesendet

**Comment by zilon84** [comment]
Momentan scheitert die Isntallation am Check der Distro.
`Sorry, this script does not support your distribution/release (Raspbian buster).`

Werd es mal mit händischem Anpassen des Install-Skriptes testen.

**Comment by leonsio** [comment]
Das kannst du recht einfach in der installation routine anpassen. Schau dir einfach installationsskript an. Müsste weit oben sein. 

Gruß 

Leo

Von meinem iPhone gesendet

**Comment by zilon84** [comment]
Danke! Das hab ich schon gefunden und gemacht. Installation ist damit soweit durchgelaufen.

Inzwischen scheint es wirklich an den Netzwerkeinstellungen zu scheitern. Die Bridge wird nicht erstellt.

**Comment by zilon84** [comment]
Vermute, dass der IP-Check fehlschlägt, da nicht in
 `/etc/dhcpcd.conf` 
sondern in
 `/etc/network/interfaces`
danach gesucht wird. Das war aber auch in den älteren Distros dort schon konfiguriert.

**Comment by leonsio** [comment]
Kann sein. 
Du kannst die Bridge ja auch manuell erstellen. I h nehme an die brctl Befehle gehen weiterhin. Was fehlt ist die Einstellungen persistent zu machen. 

Hab mich mit neuen Debian Version nicht befasst. Die alte läuft wunderbar, bis jetzt kein Bedarf an Wechsel gehabt. Das neue dhcpd mag ich persönlich sowieso nicht. Schau einfach ob es ein fallback zu interfaces Datei gibt und aktiviere diesen.  Dann soll alles weiterhin funktionieren. 
Ich hab jetzt leider keine Zeit mich mit den Anpassungen zu beschäftigen. Komme maximal im kommenden Jahr dazu. 

Von meinem iPhone gesendet

**Comment by leonsio** [comment]
Hab nochmal bei Debian buster nachgeschaut. 
Die verwenden weiterhin die Interfaces Datei zur Netzwerk Konfiguration. 
Es ist wiedermal rapsbian was den komischen dhcpd pusht. :(

Somit liegt’s nicht an Debian. Sondern an raspbian. ;(((

Probiere den Dienst zu deaktivieren

sudo service dhcpcd stop
sudo systemctl disable dhcpcd

Ggf. Hilfst. 
Du müsstest jedoch auf der console Verbunden sein. 
Davor die Interfaces Datei ablegen
Dann service networking restart angeben
Und hoffen dass es klappt ;)

Von meinem iPhone gesendet

**Comment by zilon84** [comment]
Ja, hab das gerade mal umgestellt. Damit konnte die Bridge dann auch erfolgreich erstellt werden. Danke!

Inzwischen scheitert es nur noch am Starten des Containers.

`Failed to load config for yahm
Failure to retrieve information on /var/lib/lxc:yahm`

Installierte Versionen:
> YAHM Version: 1.9
> CCU2 Version: 2.31.25

Die aktuelle 2.49.18 konnte ich nicht installieren. Da lautete der Hinweis immer, dass keine Patches vorhanden wären.

**Comment by leonsio** [comment]
Hi

Geh in den patches und in den scripts Ordner auf dem Host. Dort musst du nur ein symlink mit der richtigen Firmware Version machen. 

Bzgl. Lxc schau in dem
var/lib/lxc/yahm ordner nach. Da liegt ein log
Dort steht was das Problem ist

Von meinem iPhone gesendet

**Comment by zilon84** [comment]
Hi,

nochmals vielen Dank. Das scheint jetzt auch funktioniert zu haben.

Dass der Container nicht gestartet werden konnte, lag an einer zu alten Syntax der Konfiguration. Lässt sich mit einem 
`lxc-update-config -c <Pfad zu Datei>`
beheben.

Zuletzt scheitert es nur noch daran, dass das Funkmodul nicht erkannt wird. pivccu-driver ist installiert. Das Modul selbst scheint in Ordnung zu sein. In FHEM direkt eingebungen funktioniert es.

Ausgabe nach `yahm-ctl info:`

`Module information
Module Serial:
Module Firmware: not
`

**Comment by zilon84** [comment]
So, das Problem ist nun auch gelöst. Musst die `/boot/config.txt` ändern und `dtoverlay=pivccu-bcm2835` ergänzen. 
`Module information
Module Serial: QEQxxxxxxx
Module Firmware: 1.4.1
`
Das Firmwareupdate auf die neuste Version funktioniert nicht und es gibt folgende Rückmeldung:

`2019/12/14 13:24:10.572 <Error> CCU2CommControllerMod::performIdentify(): Unable to determine coprocessor state.
2019/12/14 13:24:10.572 <Error> CoprocessorUpdate::startApplication():Could not start Coprocessor application.

2019/12/14 13:24:10.572 <Error> Could not start Application, maybe no application on device, do update with dummy Version: 0.0.0
`
Woran könnte das liegen bzw. wo kann ich da was machen?

EDIT: Hab das Update jetzt händisch mittels:

`lxc-attach -n yahm --  eq3configcmd update-coprocessor -p /dev/mxs_auart_raw.0 -t HM-MOD-UART -u -c -d /firmware/HM-MOD-UART`

durchgeführt.
