### ISSUE TITLE
Bleibt hängen bei Homematic CCU2 ist noch nicht bereit

### ISSUE THREAD

**Issue by tobias112** [leonsio/YAHM#19]
Bitte warten. Sie werden automatisch auf die Startseite weitergleitet. 
warte schon über 15 Minuten aber auch durch neu Laden verändert sich die Seite nicht.
Wo kann ich die Fehler ansehen warum nicht startet?

![image](https://cloud.githubusercontent.com/assets/19496367/15441266/40a2f1a4-1eda-11e6-9ee3-1441ce98878a.png)

**Comment by leonsio** [comment]
https://github.com/leonsio/YAHM/wiki/Problembehandlung#wo-finde-ich-die-boot-logsmeldungen
