### ISSUE TITLE
HM-MOD...  Error disabling CSMA/CA

### ISSUE THREAD

**Issue by ploebb** [leonsio/YAHM#2]
... beschwert sich rfd beim initialisieren vom Modul.

Normal liegt das dran, dass der user unter dem rfd ausgeführt wird nicht in der gruppe dialout ist.
Nur welcher user ist das, wenn rfd innerhalb von lxc ausgeführt wird??

**Comment by leonsio** [comment]
Eigentlich wird alles von root ausgeführt, bei mir läuft es ohne Probleme 

```
c[19:45:23][root@rpi2:~]
# cat /etc/group | grep dial
dialout:x:20:pi
[19:45:30][root@rpi2:~]
# ls -al /dev/ttyAMA0 
crw-rw---- 1 root dialout 204, 64 Mai 12 19:07 /dev/ttyAMA0
```

```
/usr/local/etc/config # rfd -l 0 -c -f /etc/config/rfd.conf
2016/05/12 17:44:48.228 <Info> BidCoS-Service started
2016/05/12 17:44:48.231 <Info> XmlRpc Server is listening on TCP port 2001
2016/05/12 17:44:48.250 <Debug> CCU2CommController::init() - Legacy initialization.
2016/05/12 17:44:53.253 <Debug> () CCU2CommController::startCoprocessorApp(): Trying to start coprocessor application
2016/05/12 17:44:53.756  CCU2CommController::startCoprocessorAppThreadFunction(): Send start command
2016/05/12 17:44:53.756  CCU2CommController::SendSystemCommdand()
2016/05/12 17:44:53.757  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 00 03 18 0a 
2016/05/12 17:44:53.759  RX SERIAL: fd 00 04 00 00 04 01 99 
2016/05/12 17:44:53.759  RX SERIAL: 3d 
2016/05/12 17:44:53.759  RX FRAME: 00 00 04 01 
```

**Comment by ploebb** [comment]
Fehlalarm...

Es lief die ganze Zeit noch nen altes lxccu auf dem ich verbunden war _facepalm_

Ich teste weiter ^^

**Comment by leonsio** [comment]
Hab selbst noch ein Bug gefunden und zwischenzeitlich gefixt
Nachdem neue Bridge erstellt wurde, wird das Netzwerk nun neugestartet, damit die Änderungen wirksam werden.

Mit git pull bekommst du aktuelle Version

**Comment by ploebb** [comment]
Ja die bridge musste ich eh von Hand konfigurieren, weil die alte bridge von lxccu noch eingestellt war und es deshalb nen Fehler gab.

Evtl könnte man beim bridge erstellen prüfen ob `lxccubr0` vorhanden ist und das entsprechend einfach durch `yahmbr0` ersetzen.

Grade startet aber yahm gar nicht.. mal sehn woran das liegt.

**Comment by leonsio** [comment]
du kannst auch die alte Bridge an YAHM übergeben

yahm-network -b lxccubr0 attach_bridge

Gruß

leo
