### ISSUE TITLE
CCU-Historian 2.19.9 nicht lauffähig

### ISSUE THREAD

**Issue by tobias112** [leonsio/YAHM#23]
Wie ja auch schon andere Benutzer festgestellt haben, gibt es bei der Version 2.19.9 Schwierigkeiten mit dem ccu-historian addon, bzw. lauf Fähigkeit.

http://homematic-forum.de/forum/viewtopic.php?f=26&t=31043&start=30#p285161

Bis 2.17.16 gab es wohl keine Schwierigkeiten.

**Comment by leonsio** [comment]
Ich kann zwar ein Blick drauf werfen. Aber bezweifle dass es an YAHM liegt. An dem Code Bereich hat sich nix geändert.  
Läuft es auf Original 2.19.9?

**Comment by leonsio** [comment]
hi ich  schließe das ticket vorerst, es scheint an CuxD bzw. neuer FW zu liegen und nicht am Yahm
