### ISSUE TITLE
Gateway`s nicht sichtbar in CCU->Systemsteuerung->LAN Gateway

### ISSUE THREAD

**Issue by fisart** [leonsio/YAHM#28]
Umgebung : RASPI 3 / Jessie / CCU 2.19.9 / 2 runde LAN Adapter + RASPI Funkmodul

Die Gateways und das Funkmodul  scheinen zu funktionieren werden allerdings nicht angezeigt. Zuordnungen verschwinden nach Definition in der Anzeige. Fehler scheint identisch mit : [https://github.com/leonsio/YAHM/wiki/Problembehandlung#hs485-oder-hm-lan-gateway-zeigen-kein-status-an-ger%C3%A4te-einstellungen-seite-ist-leer](url) Ich setzte allerdings weder CuxD noch HS485 ein. Komme leider nicht über SSH auf die CCU um /etc/config_templates/InterfacesList.xml 
/etc/config/InterfacesList.xml zu verändern.

**Comment by leonsio** [comment]
auf dem Host **yahm-ctl join** dann bist du auf der CCU
siehe https://github.com/leonsio/YAHM/wiki#steuerungsmodul

**Comment by fisart** [comment]
Danke, die Dateien waren leer und nachdem ich den fix eingespielt habe sind
die Gateways zu sehen. Spende ist unterwegs allerdings spinnt Paypal im
Moment (Bestex/Fisart)

2016-05-29 17:03 GMT+02:00 Leonid Kogan notifications@github.com:

**Comment by leonsio** [comment]
freut mich dass es geklappt hat
gruß leo
