### ISSUE TITLE
README download link sudo

### ISSUE THREAD

**Issue by ploebb** [leonsio/YAHM#3]
`sudo wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | bash -s quickinstall -`

müsste heißen:
`wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E bash -s quickinstall -`

**Comment by leonsio** [comment]
danke werde es anpassen
