### ISSUE TITLE
Geräteeinstellungen können nicht abgefragt werden.

### ISSUE THREAD

**Issue by TheRealTremes** [leonsio/YAHM#30]
Wenn ich bei Einstellungen > Geräte > irgendein Gerät > Einstellungen klicke, dann kommt diese Meldung:

"Das Gerät mit der Seriennummer 'NEQ05XXXXX' vom Interface 'BidCos-RF' konnte nicht abgefragt werden!"

Das Raspi-Funkmodul ist aktiviert. YHAM läuft mit aktuellem Jessie auf einem Raspi 2

Die Installation inkl. Jessie ist frisch. Es ist nur YAHM installiert.

**Comment by leonsio** [comment]
Siehe Problemlösungen im Wiki

**Comment by leonsio** [comment]
https://github.com/leonsio/YAHM/wiki/Problembehandlung#hs485-oder-hm-lan-gateway-zeigen-kein-status-an-geräte-einstellungen-seite-ist-leer

**Comment by TheRealTremes** [comment]
Die Datei gibt es scheinbar bei mir nicht:

> /etc/config_templates/InterfacesList.xml: Datei oder Verzeichnis nicht gefunden

**Comment by leonsio** [comment]
du musst auf der CCU2 schauen

hab folgende Zeile in die Doku aufgenommen
Auf der CCU2 Konsole (**yahm-ctl join** oder nach dem Login per SSH auf die CCU2)
