### ISSUE TITLE
Quickinstall auf frischem Jessie 2016-05-10

### ISSUE THREAD

**Issue by jimmyneutron1974** [leonsio/YAHM#32]
Hi, beim Quickinstall von YAHM auf einem ganz frischen Jessie komme ich auf einem Raspberry 3 soweit:

wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E bash -s quickinstall -
2016-05-31 18:05:28 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [4574/4574] -> "-" [1]
Found ARM based distribution
Updating sources
Installing dependencies
Installing dependencies
sendmail is installed
wget is installed
dos2unix is installed
python is installed
git is installed
lxc is installed
liblzo2-dev is installed
bridge-utils is installed
python-lzo is installed
patch is installed
gzip is installed
openssl is installed
Downloading actual version from git repository
An error occurred while processing quickinstall mode. Pleasy try manually installation

Was kann ich tun?

Gruß

Jimmy

**Comment by leonsio** [comment]
Einfach normal probieren.  Ab und zu spinnt github rum

**Comment by jimmyneutron1974** [comment]
Hab das schon 5x probiert. Jessie neu installiert, wieder das Gleiche.

**Comment by leonsio** [comment]
poste bitte den Inhalt von /var/log/yahm/git.log da steht der Grund warum dies nicht geht

**Comment by kalastaja** [comment]
Ich hab' das gleiche Problem,
hier das Logfile

###

Cloning into 'YAHM'...
Checking out files:   2% (2/87)   ^MChecking out files:   3% (3/87)   ^MChecking out files:   4% (4/87)   ^MChecking ou$
Submodule 'share/tools/Network-Interfaces-Script' (https://github.com/leonsio/Network-Interfaces-Script.git) registered$
Submodule 'share/tools/arm-board-detect' (https://github.com/leonsio/arm-board-detect.git) registered for path 'share/t$
Submodule 'share/tools/rpi-source' (https://github.com/notro/rpi-source) registered for path 'share/tools/rpi-source'
Cloning into 'share/tools/Network-Interfaces-Script'...
Submodule path 'share/tools/Network-Interfaces-Script': checked out '0e61ac98ea60ae833c7370b8083968c96a2fbdb0'
Cloning into 'share/tools/arm-board-detect'...
Submodule path 'share/tools/arm-board-detect': checked out 'b82e24879b26d256dba229c42de1b533882d8618'
Cloning into 'share/tools/rpi-source'...
Submodule path 'share/tools/rpi-source': checked out '1caa816d834e7d4105826bf7463909568912b411'
fatal: destination path 'YAHM' already exists and is not an empty directory.
fatal: destination path 'YAHM' already exists and is not an empty directory.
####

**Comment by leonsio** [comment]
**fatal: destination path 'YAHM' already exists and is not an empty directory.**
löscht einfach vorher /opt/YAHM Verzeichnis und probiert es nochmal

**Comment by jimmyneutron1974** [comment]
Verzeichnis gelöscht, neu probiert:

sendmail is installed
wget is installed
dos2unix is installed
python is installed
git is installed
lxc is installed
liblzo2-dev is installed
bridge-utils is installed
python-lzo is installed
patch is installed
gzip is installed
openssl is installed
Downloading actual version from git repository
Including YAHM into PATH
    Installing bash command completion
ln: failed to create symbolic link ‘/etc/bash_completion.d/yahm_completion’: File exists
An error occurred while processing quickinstall mode. Pleasy try manually installation

**Comment by leonsio** [comment]
Bitte die Datei ebenfalls löschen. Ich passe installier an

> Am 01.06.2016 um 20:06 schrieb jimmyneutron1974 notifications@github.com:
> 
> ‘/etc/bash_completion.d/yahm_completion’

**Comment by jimmyneutron1974** [comment]
Installing dependencies
sendmail is installed
wget is installed
dos2unix is installed
python is installed
git is installed
lxc is installed
liblzo2-dev is installed
bridge-utils is installed
python-lzo is installed
patch is installed
gzip is installed
openssl is installed
Downloading actual version from git repository
Including YAHM into PATH
    Installing bash command completion
    Done

```
Enter quick install mode

Installing LXC container
```

An error occurred while processing quickinstall mode. Pleasy try manually installation
pi@raspberrypi:~ $

**Comment by leonsio** [comment]
hab gerade alles nochmal getestet und es sollte alles gehen
falls nicht bitte die manuelle Installation probieren mit **yahm-lxc -v install** und den output hier posten

**Comment by jimmyneutron1974** [comment]
Einen Schritt weiter komme ich nun. Frisches Jessie:

Found ARM based distribution
Updating sources
Installing dependencies
install sendmail
The mail frontend needs a installed 'sendmail', using pager
bash-completion is installed
wget is installed
install dos2unix
python is installed
git is installed
install lxc
install liblzo2-dev
install bridge-utils
install python-lzo
patch is installed
gzip is installed
openssl is installed
Downloading actual version from git repository
Including YAHM into PATH
Installing bash command completion
Done

```
Enter quick install mode

Installing LXC container
YAHM LXC container was installed successfully

Creating Bridge for networking
```

An error occurred while processing quickinstall mode. Pleasy try manually installation

**Comment by jimmyneutron1974** [comment]
Wenn ich jetzt die manuelle Installation mache, kommt folgende Meldung:

ERROR: YAHM instance is already installed

**Comment by leonsio** [comment]
Der fliegt ja bei Netzwerk konfig raus. Kannst install überspringen

**Comment by jimmyneutron1974** [comment]
Wie?

**Comment by jimmyneutron1974** [comment]
So, jetzt mal abschließend, ohne irgendwelche Bröckchen. Frisches Jessie drauf. Wie komme ich durch durch die Installation? Oder ich bin raus.

**Comment by jimmyneutron1974** [comment]
pi@raspberrypi:~ $ yahm-lxc -v
This script must be run as root!
pi@raspberrypi:~ $ sudo yahm-lxc -v
YAHM LXC management script

Usage Example: 

./yahm-lxc [FLAG] COMMAND
./yahm-lxc  -n mycccu install

Flags:
-n        - LXC container name.
-f        - Force operation (no halt on errors).
-v        - Verbose output 
-d        - Path to custom CCU2 firmware file
-b    - Build number (=version) of the CCU2-FW

Commands:
install     - Create new lxc instance with actual ccu2 image.
update      - Updates lxc instance to the actual version.
remove      - Removes lxc instance.

**Comment by leonsio** [comment]
kann dein Problem nicht nachvollziehen, gerade neuinstallation gemacht und alles ohne Probleme durchgelaufen und was du mit dem letzten Post mir sagen möchtest ist mir völlig unverständlich, da steht doch genau was du machen musst. einfach Anweisungen auf dem Bildschirm folgen
