### ISSUE TITLE
Fehlerhaftes HTML bei Anlernen einer HM-RC-4-2

### ISSUE THREAD

**Issue by FChristian** [leonsio/YAHM#33]
Don't know if it's a Homematic or a YAHM Problem.. Anyway it's a problem of mini-minor topic ;)

![yahm-rc](https://cloud.githubusercontent.com/assets/19758651/15804509/731569b8-2b0b-11e6-9a47-d13879f388df.JPG)

**Comment by leonsio** [comment]
Ich glaube es liegt an der Firmware;)
Ich passe keine Sprachdatei an

Gruß 

Leo
