### ISSUE TITLE
Direkte Verknüpfungen mit BidCos können nicht bearbeitet werden

### ISSUE THREAD

**Issue by maxikatze** [leonsio/YAHM#34]
Hi,

Meine Konfiguration:
Hard/Software:
Rapsberry Pi 2 mit Raspbian Jessie
YAHM + CCU2 Firmware Version 2.19.9
HomeMatic RF-LAN Gateway
HomeMatic RS485 Gateway
CuxD USB Dongle für Uniroll Gurtwickler
Backup (ohne Plugins) von CCU1 eingespielt

Ich habe noch folgendes Problem bei den direkten Verknüpfungen bei YAHM:
- Bei allen Direktverknüpfungen, die mit BidCoS arbeiten, kann ich diese nicht editieren. Dies tauchen zwar in der Liste auf, wenn ich auf bearbeiten klicke, kommt anschließen ein leeres Fenster.
- Direktverknüpfungen mit reinen Wired-Geräten können problemlos editiert werden
- In der Raspberrymatic (gleicher PI, gleiche Hardware - andere SD-Karte) können alle direkten Verknüpfungen editiert werden.

Ist dies evtl. ein ähnliches Problem, das ich vorher mit den Geräteparametern und den LAN-Gateways hatte ? Kann/soll/muss ich testweise irgendwelche Konfigurations-Dateien aus dem Raspberrymatic nehmen und evtl. in die YAHM-Installation einkopieren ?

Mit freundlichen Grüßen und meinen allerherzlichsten Dank für die tolle Programmierarbeit

**Comment by maxikatze** [comment]
Hi,

Sorry - Korrektur:
Es sieht so aus, als ob es diese Probleme nur bei Verknüpfungen gibt, bei denen Bewegungsmelder beteiligt sind. Alle anderen funktionieren (habe gerade alle Verknüpfungen durchgeklickt - die Bewegungsmelder stehen bei mir ganz oben)

Beim Öffnen der direkten Verknüpfungen - egal, ob diese editierbar sind oder nicht - scheinen immer Fehlereinträge ins Log-File zu kommen:
Beispiel:
Jun  5 12:53:44 homematic-ccu2 local0.err ReGaHss: Error: IseESP::ExecError= Execution failed: [-1] 0 0x00 [0] 144 0x90 [1] 0 0x00 [2] 9 0x09 [3] 0 0x00 [4] 28 0x1c  [../Platform/DOM/iseESPexec.cpp (11622)]
Jun  5 12:53:44 homematic-ccu2 local0.err ReGaHss: Error: IseESP::ExecError= Execution failed: [-1] 0 0x00 [0] 144 0x90 [1] 0 0x00 [2] 9 0x09 [3] 0 0x00 [4] 28 0x1c  [../Platform/DOM/iseESPexec.cpp (11622)]
Jun  5 12:53:48 homematic-ccu2 local0.err ReGaHss: Error: IseESP::ExecError= Execution failed: [-1] 0 0x00 [0] 144 0x90 [1] 0 0x00 [2] 9 0x09 [3] 0 0x00 [4] 28 0x1c  [../Platform/DOM/iseESPexec.cpp (11622)]
Jun  5 12:53:48 homematic-ccu2 local0.err ReGaHss: Error: IseESP::ExecError= Execution failed: [-1] 0 0x00 [0] 144 0x90 [1] 0 0x00 [2] 9 0x09 [3] 0 0x00 [4] 28 0x1c  [../Platform/DOM/iseESPexec.cpp (11622)]

Gruß

**Comment by leonsio** [comment]
Dann würde das ich den Fehler bei der Firmware sehen und nicht bei YAHM ;)
Raspberrymatic ist ja noch bei 2.15 

Du kannst einfach YAHM mit 2.15.5 installieren und schauen ob das Problem auftritt 

Gruß 

Leo

**Comment by maxikatze** [comment]
Hi,

Ich befürchte auch, dass es an der Firmware liegt.
Aber jetzt die 2.15.5 in YAHM zu installierern - lieber nicht. Never change a running System :-)

Merkwürdigerweise kann ich die Direktverknüpfungen neu anlegen - diese überschreiben dann die alten.
Oder: ich kann sie löschen - wird korrekt an die Geräte übertragen.
Das habe ich dann auch so gemacht und gelassen - und die notwendigen Verknüpfungen in Programme ausgelagert. Das läuft mit dem Raspberry so schnell, dass man nicht mal merkt, dass es über die "CCU" läuft.

Wenn sonst niemand das Problem hat, kann man dieses "Issue" wohl schliessen :-)

Gruß
