### ISSUE TITLE
Installation auf frischem Jessie 27.05.16

### ISSUE THREAD

**Issue by sapcons** [leonsio/YAHM#35]
Hallo. Das Problem wurde bereits beschrieben aber ohne wirkliche Lösung geschlossen. Fakt ist, dass die automatisierte Methode sowohl auf einem Full, als auch Lite Jessie abbricht. Das git.log schreibt keinen Fehlergrund. Hab es mit neuen SD-Karten auf einem RPI2 mehrfach versucht.

**Comment by leonsio** [comment]
kann es leider nicht nachvollziehen, wie ich im homematic-forum lese, haben kürzlich einige die Anwendung ohne Probleme installiert

**Comment by sapcons** [comment]
ich werde es später noch einmal probieren. Soll ich dir log-Files schicken? Wenn ja, welche brauchst du? Danke

**Comment by leonsio** [comment]
schick den kompletten Inhalt von /var/log/yahm

Gruß

Leo

**Comment by sapcons** [comment]
Hallo,

Hier die Dateien und auch die Info aus dem Terminalfenster.

Danke und Grüße,

Kai

root@raspberrypi:/home/pi# wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
2016-06-06 14:48:35 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [4616/4616] -> "-" [1]
Found ARM based distribution
Updating sources
Installing dependencies
install sendmail
The mail frontend needs a installed 'sendmail', using pager
bash-completion is installed
wget is installed
install dos2unix
python is installed
install git
install lxc
install liblzo2-dev
install bridge-utils
install python-lzo
patch is installed
gzip is installed
openssl is installed
Clean up YAHM directory (removing old versions)
done
Downloading actual version from git repository
Including YAHM into PATH
Installing bash command completion
Done

```
  Enter quick install mode

  Installing LXC container
  YAHM LXC container was installed successfully

  Creating Bridge for networking
```

An error occurred while processing quickinstall mode. Pleasy try manually installation
root@raspberrypi:/home/pi#

[yahm.zip](https://github.com/leonsio/YAHM/files/300681/yahm.zip)

**Comment by ghost** [comment]
habs grad erfolgreich auf nem Pi1 B mit homegear image installiert, einziges problem war das im basis system eth0 nicht auskommentiert wurde, danach gabs zwei interfaces mit der selben ip und ich konnte das basisystem nicht mehr erreichen, das yahm interface und homematic hat prima funktioniert.

**Comment by sapcons** [comment]
habs grad erfolgreich auf nem Pi1 B mit homegear image installiert, einziges problem war das im basis system eth0 nicht auskommentiert wurde, danach gabs zwei interfaces mit der selben ip und ich konnte das basisystem nicht mehr erreichen, das yahm interface und homematic hat prima funktioniert.

**Comment by ghost** [comment]
Detailinfo
Das Basisistem ist ein Rpi1 B (ohne +)

root@homegearpi:~# lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie

nach erfoglreicher automtischer installation ist homegear auf der "virtuellen" ip sauber gestartet, den Raspi selber konnte ich aber nicht mehr erreichen. Der Grund in /etc/network/interfaces

auto eth0
iface eth0 inet dhcp
iface eth0 inet6 auto

auto yahmbr0
iface yahmbr0 inet dhcp
    bridge_ports eth0

war eth0 nicht auskommentiert, was dazu geführt hat das eth0 und yahmbr0 die selbe ip erhalten haben, was falsch ist nur das bridge interface sollte ne ip haben. nach asukommentieren der eth0 config

auto eth0
#iface eth0 inet dhcp
#iface eth0 inet6 auto

auto yahmbr0
iface yahmbr0 inet dhcp
    bridge_ports eth0

**Comment by leonsio** [comment]
hi nach dem Reboot oder davor?
eigentlich sollte dhcp auf manual geändert werden, dadurch würde das Interface keine IP bekommen
ist das eine frische Lite installation, oder wurde irgendwas angepasst?

**Comment by sapcons** [comment]
ich habe eine SD-Karte komplett neu mit einem Jessie lite installiert (Stand 27.05.). Darauf dann die automatische Installation gestartet.

---

hi nach dem Reboot oder davor?
eigentlich sollte dhcp auf manual geändert werden, dadurch würde das Interface keine IP bekommen
ist das eine frische Lite installation, oder wurde irgendwas angepasst?

**Comment by sapcons** [comment]
running. 
eth0 wurde händisch auskommentiert.
bridge 'yahmbr0' konnte nicht angelegt - nur nachdem ich einen eigenen Namen verwendet habe

Trying to create new bridge yahmbr0 with physical interface eth0
ATTENTION: Network configuration will be changed, you may no longer login to the system!!!
No bridge with choosen name found, continue...
Interface eth0 is physical and valid, continue...

mit eigenem Namen hat es dann funktioniert die Bridge anzulegen und den Container zuzuordnen.

LXC container information
Name:           yahm
State:          RUNNING
PID:            10954
IP:             192.168.178.24
CPU use:        18.46 seconds
BlkIO use:      284.00 KiB
Link:           vethGBI3PR
 TX bytes:      4.23 KiB
 RX bytes:      13.76 KiB
 Total bytes:   17.99 KiB

VIELEN DANK

**Comment by leonsio** [comment]
laut den logs hat alles funktioniert, zumindest sieht die interfaces datei gut aus
das einzigste was passieren könnte, ist dass du neue IP für die Bridge bekommst und deswegen nicht auf das System drauf kommst, was wahrscheinlich auch der Fall war

ich werde den Hinweis dafür in den quickinstall einbauen (bei manueller kommt die Meldung)
