### ISSUE TITLE
HM-DIS-EP-WM55 unbekanntes Gerät / Icon fehlt

### ISSUE THREAD

**Issue by TSpielmann** [leonsio/YAHM#38]
Hallo zusammen
Raspberry Jessi, Kernel 4.4.11, CCU FW 2.19.9. Frisch eingerichtet, Restore aus bestehendem CCU Backup. HM-IP disabled.
Der Aktor lässt sich anlernen und auch konfigurieren. Allerdings ist bereits hier das ICON nicht vorhanden. Nach einem Neustart wird das Gerät nicht mehr als "HM-DIS-..." sondern als "unkown Device" in den Geräten angezeigt. Programaktionen sind nur im Klartext und nicht über das vorgesehene Edit PopUp einzutragen. Ablernen und Rücksetzen des Gerätes über CCU(YAHM) funktioniert. Mangels Vergleich kann ich nicht sagen, ob dies nur unter YAHM passiert. In einer frischen YAHM Installation mit nur diesem Gerät habe ich den gleichen Effekt.

![anlernen](https://cloud.githubusercontent.com/assets/20240868/16518971/33a7a630-3f86-11e6-9b41-b072be3eb01d.PNG)

![unbenanntes-geraet](https://cloud.githubusercontent.com/assets/20240868/16519032/96b34ee6-3f86-11e6-875e-acbbf1ce92e1.PNG)

![programme](https://cloud.githubusercontent.com/assets/20240868/16519079/e51c97d6-3f86-11e6-812c-96e9d8cc7bbd.PNG)

**Comment by leonsio** [comment]
Ist ein Problem der CCU Firmware
