### ISSUE TITLE
Externe Auswertung der Info Meldung

### ISSUE THREAD

**Issue by fisart** [leonsio/YAHM#39]
Ich führe über IP-Symcon den folgenden Befehl aus : 

$message = $ssh->exec("sudo yahm-ctl -v info");

print_r ($message);

und erhalte dann die folgende Anzeige : LXC container information

Der Rest fehlt !

**Comment by leonsio** [comment]
Hi  ich sehe das nicht als YAHM Problem

ggf kann die Methode nicht mit Farb-Formatierung auf der Console umgehen, frag im Symcon Forum
Anbei Quelltext der Ausgabe. Kannst diese in ein Bash Skript packen und mit symcon testen

``` bash
info() {
    [ $use_colour -eq 1 ] && echo -ne "\033[01;34m"
    echo -e "$@" >&2
    [ $use_colour -eq 1 ] && echo -ne "\033[00m"
}
```

ich weiß nicht was du machen möchtest du kannst auch mit lxc-attach ein Befehl direkt auf CCU Konsole ausführen Bsp.: **lxc-attach -n yahm "ifconfig"**

**Comment by fisart** [comment]
Danke das hilft mir : _lxc-attach -n yahm "ifconfig"_

*Kleine Anmerkung : Ich würde die Farbanzeige optional machen. Bei mir ist
das schwarz auf blauem Hintergrund schlecht lesbar und bei der Remote
abfrage mit ssh2 kommt nicht alles rüber.  *

2016-07-03 21:01 GMT+02:00 Leonid Kogan notifications@github.com:
