### ISSUE TITLE
/opt/YAHM/bin nicht im PATH von sudo

### ISSUE THREAD

**Issue by ploebb** [leonsio/YAHM#4]
Für normale user wird der Pfad jetzt in die `PATH` mit aufgenommen. Für sudo allerdings nicht.
sudo resettet standardmäßig die environment und nimmt seine eigene `PATH`, die in `/etc/sudoers` definiert ist.

Damit man die Skripte mit `sudo` aufrufen kann müsste also `/opt/YAHM/bin` an die `secure_path` Variable in der `/etc/sudoers` angehängt werden.

**Comment by leonsio** [comment]
Vielleicht sammelst du alles was dir einfällt und machst ein größeres Pull request ;) 
Wie ich sehe bist du fleißig dabei 👍

**Comment by ploebb** [comment]
Jepp kann ich machen

**Comment by leonsio** [comment]
Hi

wie siehts bei dir aus? Da ich bis jetzt keine gravierenden Bugs gefunden habe, wollte ich morgen ein Release rausbringen.

Gruß

Leo

**Comment by ploebb** [comment]
Bei mir läufts jetzt, bis auf diesen issue. Da müsste man noch nen sed-Befehl basteln der den Pfad in der Datei ergänzt. Bin gestern nicht dazu gekommen und seit heute Nachmittag nicht mehr daheim.
Hätte es gern noch mal auf nem frischen Raspbian getestet.

Achja der bridge-test-modus hatte die ssh-Verbindung lahmgelegt. Musste den Stecker ziehen und danach nen Backup wieder einspielen (SD-zerschossen?)
Dabei schließe ich aber einen Anwenderfehler von mir nicht aus ^^
Habe schließlich die lxccubr0 bridge an yahm gebunden und damit liefs einwandfrei.

Auch das Funkmodul hat funktioniert. 
Find das Konzept übrigens sehr gelungen mit den Modulen und den verschiedenen Skripten!

Ich finde ein Beta-Release kannst du auf jeden Fall rausbringen.
Wenn du nen Forum-Thread aufmachst schreib am besten den Link hier rein, dann schau ich am Wochenende ab und an mal rein und versuche nen bisschen Support zu leisten.

Gruß Jonas

Ps: ich schau mal, ob ich grad noch nen sed-Befehl zusammen bekomme für den Pfad.

**Comment by ploebb** [comment]
Okay.. ich bekomme es grad nicht hin.
Prinzipiell ist es sehr gefährlich die sudoers-datei direkt zu verändern. Wenn da nen syntax-Fehler drin ist funktioniert `sudo` nicht mehr und man kann das dann nur mit `su` und root-passwort wieder retten.
(Grade passiert ;-))

Theoretisch sollte man wohl in `/etc/sudoers.d` eine neue Datei anlegen. Diese wird mit `include` in der `sudoers` am Schluss eingebunden.

Fürs erste würde ich evtl. in der README einfach empfehlen die ganze Sache unter root zu installieren und zu managen (`sudo su`).

**Comment by ploebb** [comment]
Oder aber man setzt einfach Links zu den Skripten in einen secure_path-Ordner (z.B. in `/usr/local/sbin`). Das wäre vielleicht die sauberste Lösung.
Dann müsste der Ordner auch nicht mehr in die normale `PATH`-Variable
