### ISSUE TITLE
XMLRPC steht nicht zur Verfügung

### ISSUE THREAD

**Issue by dkrizic** [leonsio/YAHM#40]
Wenn ich YAHM starte, läuft kein XMLRPC auf Port 2001:

```
Starting Nmap 6.47 ( http://nmap.org ) at 2016-07-06 10:58 CEST
Nmap scan report for homematic (10.10.2.48)
Host is up (0.0014s latency).
rDNS record for 10.10.2.48: homematic.xxx.yyy
Not shown: 996 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
1999/tcp open  tcp-id-port
8181/tcp open  unknown

```

**Comment by leonsio** [comment]
läuft nur sofern du rfd richtig konfigurierst, entweder mit lanGW oder mit funkmodul

**Comment by dkrizic** [comment]
Ich verwende HomeGear, das funktioniert alles, d.h. weder LanGW noch Funkmodul? Hier macht wohl ein virtuelles Device Sinn, oder?

**Comment by leonsio** [comment]
Kann ich dir nicht sagen, schau einfach was in /var/log/messages zum rfd Prozess steht

**Comment by leonsio** [comment]
irgend ein Update? sonst schließe ich den Thread

**Comment by leonsio** [comment]
falls das Problem noch immer besteht, bitte Thread erneut öffnen
