### ISSUE TITLE
YAHM Module: HM MOD RPI PCB on bananian

### ISSUE THREAD

**Issue by wep4you** [leonsio/YAHM#41]
Id like to install the YAHM and the module on a BananaPro with banana. What to do to get this working. With a raspberry PI-3 the installation worked for me but, without a hdd i get file corruption about 1 a week, with different cards, so i decided to change to banana pro with a SSD Harddisk, but can't install the YAHM. Is it possible to enhance the script for Installation on a banana with bananian?

**Comment by leonsio** [comment]
HI

eigentlich sollte es egal sein ob YAHM auf SD/SSD oder HDD installiert wird.
Mach einfach git clone und führe die Installation lokal durch, bzw. an welcher Stelle bekommst du I/O Fehlermeldungen ich nehme an beim checkout? (alternativ ZIP Datei von Github runterladen)

Gruß

Leo

**Comment by wep4you** [comment]
Hallo,

YAHM ist nicht der Auslöser für die Fehler, habe ich nur am gleichen raspberry laufen gehabt, und wollte jetzt auf banana umsteigen.
YAHm bekomme ich am bananian zum laufen, allerdings funktioniert das Script für die Installation des Funkmoduls nicht, schreibt das es sich um kein Raspbian Betriebssystem handelt, wenn ich das mit -f einfach ignoriere, fängt er zwar an das Script auszuführen schmeisst aber Fehlermeldungen, da anscheinend unterschiedliche Boot Scripts zwischen Raspbian und bananian existieren und das Script damit natürlich nichts anfangen kann.

**Comment by leonsio** [comment]
da ich kein BananaPi habe, kann ich es leider nicht testen.
Ein Problem was es mit Bananian/Armbian gab ist die Deaktivierung/Anpassung der UART Schnittstelle, frag lieber im [Homematic Forum](http://homematic-forum.de/forum/viewtopic.php?f=18&t=31033&start=390) insbesondere User Homoran/starfish und Leon265130 die haben auch Bananen und versucht YAHM damit zum Laufen zu bringen

Außerdem müsstest du schauen unter welche GPIO das Funkmodul zu finden ist (sollte 18 wie bei Rpi sein) und wie man die GPIOs ansteuert. Pinkompatibilität ist leider nicht alles ;)

Solltest du erfolgreich sein, sag Bescheid und ich baue die Änderungen ein
