### ISSUE TITLE
Zweites HM-LGW-O-TW-W-EU-2 anmelden schlägt fehl

### ISSUE THREAD

**Issue by leiweke** [leonsio/YAHM#42]
Hallo Ich habe gerade versucht ein zweites HM-LGW-O-TW-W-EU-2 (NEQxxxxxxx) in betrieb zunehmen. aber es schlägt fehl und es landet im bootloader mode (Power blinkt schnell - Netzwerk blinkt normal) und ich bekomme es nicht mehr daraus.
Das erste LAN-GW (KEQxxxxxxx) funktioniert ohne Probleme 
Hier das Logg der CCU2:
CCU2CommControllerMod::handleIncomingResponse() System response OK
Jul 11 19:44:34 homematic-ccu2 user.info update-coprocessor: Firmwareupdate successfull
Jul 11 19:44:34 homematic-ccu2 user.info logger: Updating RF Lan Gateway Firmware
Jul 11 19:44:34 homematic-ccu2 user.info update-lgw-firmware: LAN Gateway Firmware Update...
Jul 11 19:44:34 homematic-ccu2 user.info update-lgw-firmware: Gateway KEQxxxxxxx
Jul 11 19:44:36 homematic-ccu2 user.info update-lgw-firmware: Gateway type is eQ3-HM-LGW-App
Jul 11 19:44:36 homematic-ccu2 user.info update-lgw-firmware: Available Firmware Version:   1.1.5
Jul 11 19:44:36 homematic-ccu2 user.info update-lgw-firmware: Lan Gateway Firmware Version: 1.1.5
Jul 11 19:44:36 homematic-ccu2 user.info update-lgw-firmware: Firmware is up to date
Jul 11 19:44:36 homematic-ccu2 user.info update-lgw-firmware: LAN Gateway Firmware Update...
Jul 11 19:44:36 homematic-ccu2 user.info update-lgw-firmware: Gateway NEQxxxxxxx
Jul 11 19:44:38 homematic-ccu2 user.info update-lgw-firmware: Gateway type is eQ3-HM-LGW-App
Jul 11 19:44:38 homematic-ccu2 user.info update-lgw-firmware: Available Firmware Version:   1.1.5
Jul 11 19:44:38 homematic-ccu2 user.info update-lgw-firmware: Lan Gateway Firmware Version: 1.1.3
Jul 11 19:45:03 homematic-ccu2 user.err update-lgw-firmware: Could not enter bootloader.
Jul 11 19:45:03 homematic-ccu2 user.info logger: Updating Wired Lan Gateway Firmware
Jul 11 19:45:03 homematic-ccu2 user.info update-lgw-firmware: No gateway found in config file /etc/config/hs485d.conf
Jul 11 21:45:14 homematic-ccu2 user.debug setclock: Try to get time from 0.de.pool.ntp.org
Jul 11 21:45:14 homematic-ccu2 user.debug setclock: Mon Jul 11 21:45:14 CEST 2016
Jul 11 21:45:18 homematic-ccu2 user.err rfd: UnifiedLanCommController::connect(): Unable to connect.
Jul 11 21:45:18 homematic-ccu2 user.crit rfd: CCU2LGWCommController::init(): Cannot connect to HomeMatic Lan Gateway with serial number NEQ0382326.
Jul 11 21:45:28 homematic-ccu2 user.info kernel: [1032442.477978] w1_master_driver w1_bus_master1: Family 0 for 00.9cca00000000.e1 is not registered.
Jul 11 21:45:30 homematic-ccu2 user.info kernel: [1032444.188228] EXT4-fs (mmcblk0p2): re-mounted. Opts: data=ordered
Jul 11 19:45:30 homematic-ccu2 daemon.info init: starting pid 489, tty '/dev/tty1': '/sbin/getty -L tty1 115200 linux'
Jul 11 21:45:35 homematic-ccu2 user.err rfd: HSSParameter::GetValue() id=DECISION_VALUE failed getting physical value.
Jul 11 21:45:56 homematic-ccu2 user.err rfd: HSSParameter::GetValue() id=DECISION_VALUE failed getting physical value.

Kann jemand bitte helfen?
Vielen Dank
SL

**Comment by leiweke** [comment]
hier noch das full log vom start:
Jul 11 20:15:14 homematic-ccu2 daemon.warn ifplugd(eth0)[155]: client: Lease of 192.168.178.101 obtained, lease time 864000
Jul 11 20:15:14 homematic-ccu2 daemon.warn ifplugd(eth0)[155]: client: rm: can't remove '/var/etc/resolv.conf': No such file or directory
Jul 11 20:15:14 homematic-ccu2 daemon.warn ifplugd(eth0)[155]: client: udhcpc (v1.20.2) started
Jul 11 20:15:14 homematic-ccu2 daemon.warn ifplugd(eth0)[155]: client: Sending discover...
Jul 11 20:15:14 homematic-ccu2 daemon.warn ifplugd(eth0)[155]: client: Sending select for 192.168.178.101...
Jul 11 20:15:14 homematic-ccu2 daemon.warn ifplugd(eth0)[155]: client: Lease of 192.168.178.101 obtained, lease time 864000
Jul 11 20:15:14 homematic-ccu2 daemon.info ifplugd(eth0)[155]: Program executed successfully.
Jul 11 20:15:14 homematic-ccu2 user.info logger: Updating RF Lan Gateway Coprocessor Firmware
Jul 11 20:15:15 homematic-ccu2 user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
Jul 11 20:15:15 homematic-ccu2 user.info update-coprocessor: performGatewayCoproUpdate(): updating KEQ1065306
Jul 11 20:15:17 homematic-ccu2 user.info update-coprocessor: Lan Device Information: Protocol-Version: 1 Product-ID: eQ3-HM-LGW Firmware-Version: 1.1.5 Serial Number: KEQxxxxxxx
Jul 11 20:15:17 homematic-ccu2 user.info update-coprocessor: Lan Device Information: Protocol-Version: 1 Product-ID: eQ3-HM-LGW Firmware-Version: 1.1.5 Serial Number: KEQxxxxxxx
Jul 11 20:15:18 homematic-ccu2 user.debug update-coprocessor: (KEQxxxxxxx) CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in application.
Jul 11 20:15:18 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
Jul 11 20:15:18 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
Jul 11 20:15:18 homematic-ccu2 user.debug update-coprocessor: CCU2CommControllerMod::handleIncomingResponse() System response OK
Jul 11 20:15:18 homematic-ccu2 user.debug update-coprocessor: (KEQxxxxxxx) CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in application.
Jul 11 20:15:18 homematic-ccu2 user.debug update-coprocessor: CoprocessorUpdate::startApplication():Coprocessor entered application.
Jul 11 20:15:19 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
Jul 11 20:15:19 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
Jul 11 20:15:19 homematic-ccu2 user.debug update-coprocessor: CCU2CommControllerMod::handleIncomingResponse() System response OK
Jul 11 20:15:19 homematic-ccu2 user.info update-coprocessor: Version: 1.4.1
Jul 11 20:15:19 homematic-ccu2 user.info update-coprocessor: Coprocessor firmware not necessary.
Jul 11 20:15:19 homematic-ccu2 user.info update-coprocessor: performGatewayCoproUpdate(): updating NEQxxxxxxx
Jul 11 20:15:19 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): Bidcos frame
Jul 11 20:15:19 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): Bidcos frame
Jul 11 20:15:21 homematic-ccu2 user.info update-coprocessor: Lan Device Information: Protocol-Version: 1 Product-ID: eQ3-HM-LGW Firmware-Version: 1.1.3 Serial Number: NEQxxxxxxx
Jul 11 20:15:21 homematic-ccu2 user.info update-coprocessor: Lan Device Information: Protocol-Version: 1 Product-ID: eQ3-HM-LGW Firmware-Version: 1.1.3 Serial Number: NEQxxxxxxx
Jul 11 20:15:22 homematic-ccu2 user.debug update-coprocessor: (NEQxxxxxxx) CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in bootloader.
Jul 11 20:15:22 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
Jul 11 20:15:22 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
Jul 11 20:15:22 homematic-ccu2 user.debug update-coprocessor: CCU2CommControllerMod::handleIncomingResponse() System response OK
Jul 11 20:15:22 homematic-ccu2 user.debug update-coprocessor: (NEQxxxxxxx) CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in bootloader.
Jul 11 20:15:22 homematic-ccu2 user.debug update-coprocessor: (NEQxxxxxxx) CCU2CommControllerMod::startCoprocessorApp(): Trying to start coprocessor application
Jul 11 20:15:22 homematic-ccu2 user.debug update-coprocessor: CCU2CommControllerMod::sendSystemCommand(): Start Application / Bootloader
Jul 11 20:15:23 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): Bidcos frame
Jul 11 20:15:23 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
Jul 11 20:15:23 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
Jul 11 20:15:23 homematic-ccu2 user.debug update-coprocessor: CCU2CommControllerMod::handleIncomingResponse() System response OK
Jul 11 20:15:23 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
Jul 11 20:15:23 homematic-ccu2 user.debug update-coprocessor: (NEQxxxxxxx) CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in application.
Jul 11 20:15:23 homematic-ccu2 user.debug update-coprocessor: CoprocessorUpdate::startApplication():Coprocessor entered application.
Jul 11 20:15:24 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
Jul 11 20:15:24 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
Jul 11 20:15:24 homematic-ccu2 user.debug update-coprocessor: CCU2CommControllerMod::handleIncomingResponse() System response OK
Jul 11 20:15:24 homematic-ccu2 user.info update-coprocessor: Version: 1.4.1
Jul 11 20:15:24 homematic-ccu2 user.info update-coprocessor: Coprocessor firmware not necessary.
Jul 11 20:15:24 homematic-ccu2 user.info logger: Updating RF Lan Gateway Firmware
Jul 11 20:15:24 homematic-ccu2 user.info update-lgw-firmware: LAN Gateway Firmware Update...
Jul 11 20:15:24 homematic-ccu2 user.info update-lgw-firmware: Gateway KEQxxxxxxx
Jul 11 22:15:26 homematic-ccu2 user.info kernel: [1034240.443779] yahmbr0: port 3(vethMT54L6) entered forwarding state
Jul 11 20:15:26 homematic-ccu2 user.info update-lgw-firmware: Gateway type is eQ3-HM-LGW-App
Jul 11 20:15:26 homematic-ccu2 user.info update-lgw-firmware: Available Firmware Version:   1.1.5
Jul 11 20:15:26 homematic-ccu2 user.info update-lgw-firmware: Lan Gateway Firmware Version: 1.1.5
Jul 11 20:15:26 homematic-ccu2 user.info update-lgw-firmware: Firmware is up to date
Jul 11 20:15:26 homematic-ccu2 user.info update-lgw-firmware: LAN Gateway Firmware Update...
Jul 11 20:15:26 homematic-ccu2 user.info update-lgw-firmware: Gateway NEQxxxxxxx
Jul 11 20:15:28 homematic-ccu2 user.info update-lgw-firmware: Gateway type is eQ3-HM-LGW-App
Jul 11 20:15:28 homematic-ccu2 user.info update-lgw-firmware: Available Firmware Version:   1.1.5
Jul 11 20:15:28 homematic-ccu2 user.info update-lgw-firmware: Lan Gateway Firmware Version: 1.1.3
Jul 11 22:15:29 homematic-ccu2 user.info kernel: [1034243.073252] w1_master_driver w1_bus_master1: Family 0 for 00.7aca00000000.d5 is not registered.
Jul 11 20:15:53 homematic-ccu2 user.err update-lgw-firmware: Could not enter bootloader.
Jul 11 20:15:53 homematic-ccu2 user.info logger: Updating Wired Lan Gateway Firmware
Jul 11 20:15:53 homematic-ccu2 user.info update-lgw-firmware: No gateway found in config file /etc/config/hs485d.conf
Jul 11 22:15:57 homematic-ccu2 user.warn multimac: FastMacResponder could not open port /dev/mxs_auart_raw.0: No such file or directory
Jul 11 22:15:57 homematic-ccu2 user.warn multimac: MacController could not open port /dev/mxs_auart_raw.0: No such file or directory
Jul 11 22:15:57 homematic-ccu2 user.debug multimac: SubsystemManager::ThreadFunction() started. Id=331
Jul 11 22:15:57 homematic-ccu2 user.warn multimac: UpstreamCharConnection could not open master port /dev/eq3loop: No such file or directory
Jul 11 22:15:57 homematic-ccu2 user.debug multimac: Subsystem 1 ThreadFunction() started. Id=332
Jul 11 22:15:57 homematic-ccu2 user.warn multimac: UpstreamCharConnection could not open master port /dev/eq3loop: No such file or directory
Jul 11 22:15:57 homematic-ccu2 user.debug multimac: Subsystem 2 ThreadFunction() started. Id=333
Jul 11 22:15:59 homematic-ccu2 user.info rfd: BidCoS-Service started
Jul 11 22:15:59 homematic-ccu2 user.info rfd: XmlRpc Server is listening on TCP port 2001
Jul 11 22:16:01 homematic-ccu2 user.info rfd: Found HomeMatic Lan Gateway with IP Address 192.168.178.110
Jul 11 22:16:01 homematic-ccu2 user.info rfd: Lan Device Information: Protocol-Version: 1 Product-ID: eQ3-HM-LGW Firmware-Version: 1.1.5 Serial Number: KEQxxxxxxx
Jul 11 22:16:02 homematic-ccu2 user.debug rfd: CCU2CommController::init() - Improved initialization.
Jul 11 22:16:02 homematic-ccu2 user.info rfd: Lan Device Information: Protocol-Version: 1 Product-ID: eQ3-HM-LGW Firmware-Version: 1.1.5 Serial Number: KEQxxxxxxx
Jul 11 22:16:02 homematic-ccu2 user.debug rfd: (KEQxxxxxxx) CCU2CommController::handleIncomingSerialFrame(): Command not parseable.
Jul 11 22:16:02 homematic-ccu2 user.debug rfd: CCU2CommController::improvedInit() - Coprocessor is in application.
Jul 11 22:16:02 homematic-ccu2 user.debug rfd: Switching RF-LGW LED OFF
Jul 11 22:16:02 homematic-ccu2 user.info rfd: CCU2CommController::init(): Coprocessor Bootloader Version is: 1.0.4
Jul 11 22:16:02 homematic-ccu2 user.info rfd: CCU2CommController::init(): Coprocessor Firmware Version is: 1.4.1
Jul 11 22:16:02 homematic-ccu2 user.info rfd: (KEQxxxxxxx) CCU2CommController::setCSMACAEnabled(): CSMA/CA disabled.
Jul 11 22:16:02 homematic-ccu2 user.debug rfd: Default interface is now KEQxxxxxxx
Jul 11 22:16:08 homematic-ccu2 user.info rfd: Found HomeMatic Lan Gateway with IP Address 127.0.0.1
Jul 11 22:16:08 homematic-ccu2 user.err rfd: UnifiedLanCommController::connect(): Unable to connect.
Jul 11 22:16:08 homematic-ccu2 user.crit rfd: CCU2LGWCommController::init(): Cannot connect to HomeMatic Lan Gateway with serial number NEQxxxxxxx.
Jul 11 22:16:08 homematic-ccu2 user.info rfd: Current AES key=0, previous AES key=0
Jul 11 22:16:08 homematic-ccu2 user.debug rfd: (KEQxxxxxx) Response status: Input wrong.
Jul 11 22:16:08 homematic-ccu2 user.debug rfd: CCU2BidcosRemoteInterface::StartInterface(): addr=26 69 a6 
Jul 11 22:16:08 homematic-ccu2 user.debug rfd: (KEQxxxxxxx) Response status: OK.

Danke
SL

**Comment by leonsio** [comment]
es scheint was mit dem Update nicht zu klappen, probier mal das ding manuell zu aktualisieren
siehe dazu https://github.com/eq-3/occu/wiki/Tools
