### ISSUE TITLE
CUxD Interface lässt sich nicht öffnen

### ISSUE THREAD

**Issue by Manawyrm** [leonsio/YAHM#44]
**[Gelöst! Siehe unten]**

Hi,

ich habe aktuell die Problematik, dass ich nach dem Einspielen eines Backups das cuxd-Webinterface nicht mehr öffnen kann.

Ich habe bereits so ziemlich alle Möglichkeiten durch, also ein Backup mit Cuxd, ein Backup ohne Cuxd, ein Backup mit Cuxd und angelegten Cuxd-Devices, bei allen ist nach dem Einspielen auf dem YAHM-CCU kein Aufrufen des WebIFs von CUxD mehr möglich, es kommt die "Die CCU ist noch nicht bereit"-Meldung, wie beim booten. 

```
Jul 17 21:23:30 homematic-ccu2 user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
Jul 17 21:23:30 homematic-ccu2 user.info logger: Updating RF Lan Gateway Firmware
Jul 17 21:23:30 homematic-ccu2 user.info update-lgw-firmware: No gateway found in config file /etc/config/rfd.conf 
Jul 17 21:23:30 homematic-ccu2 user.info logger: Updating Wired Lan Gateway Firmware 
Jul 17 21:23:30 homematic-ccu2 user.info update-lgw-firmware: No gateway found in config file /etc/config/hs485d.conf
Jul 17 23:23:51 homematic-ccu2 user.info homematic: started cux-daemon 
Jul 17 21:23:52 homematic-ccu2 daemon.info init: starting pid 429, tty '/dev/tty1': '/sbin/getty -L tty1 115200 linux' 
Jul 17 23:24:03 homematic-ccu2 local0.err ReGaHss: Error: XmlRpc: Error in XmlRpcClient::writeRequest: write error (error 111). [../Platform/DOM/iseXmlRpc.h (281)]
Jul 17 23:24:03 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallXmlrpcMethod: execute failed; method =init Params = {"xmlrpc_bin://127.0.0.1:1999","1425"} result= nil [../Platform/DOM/iseXmlRpc.cpp (262
Jul 17 23:24:03 homematic-ccu2 local0.err ReGaHss: Error: IseXmlRpc::CallInit: CallXmlrpcMethod failed [../Platform/DOM/iseXmlRpc.cpp (1219)]
Jul 17 23:24:03 homematic-ccu2 local0.err ReGaHss: Error: XmlRpcClientThread::ThreadFunction(): failed call init for interface=CUxD [../Platform/RT/iseRTHss.cpp (163)]
```

Ich bin mir nicht sicher, ob die Log-Nachrichten überhaupt zum cuxd gehören, oder zu einer anderen Sache.

Wichtige Infos wären ansonsten noch, dass das Quellgerät (von dem die Backups kommen) der gleiche RPi mit Funkmodul ist, nur mit einer anderen SD-Karte. 

Vielleicht habe ich ja nur einen blöden kleinen Denk/Konfigurationsfehler gemacht, in jedem Falle würde ich mich über eine Antwort sehr freuen.

Viele Grüße,
Tobias

**Comment by Manawyrm** [comment]
Hm,
ich habe gerade mal manuell versucht auf der Konsole cuxd zu starten und bekomme ein 

```
~ # /etc/init.d/S55cuxd start
modprobe: chdir(4.4.13-v7+): No such file or directory
~ # 
```

zu sagen wäre noch, dass ich ein aktuelles Raspbian Jessie Lite als Hostsystem verwende.
Spontan hätte ich gesagt, dass der Fehler von der Zeile `modprobe ehci_hcd` kommt. Ich weiß nicht recht, ob das ein fataler Fehler ist, aber in jedem Falle wird das so nicht klappen, da der RPi ja den propritären bcm2835-USB-Stack verwendet.

```
~ # netstat -tlen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 0.0.0.0:1999            0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:2001            0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:8181            0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      
tcp        0      0 :::9292                 :::*                    LISTEN      
tcp        0      0 :::22                   :::*                    LISTEN      
```

cuxd scheint aber generell nicht zu laufen, da der ganze TCP-Socket nicht da ist. 

```
/usr/local/etc/config # cd /usr/local/addons/cuxd
/usr/local/addons/cuxd # ls
CUXD.PNG                  curl                      cuxd_addon.cfg            dfu-programmer            index.html                maintenance.html          update_addon
ajax.gif                  cuxd                      devicelist.inc            extra                     libusb-1.0.so.0           redir.ccc                 webcamconfig-default.ini
cproxy.ccc                cuxd.inc                  dfu                       index.ccc                 libusb-1.0.so.0.1.0       robots.txt
/usr/local/addons/cuxd # ./cuxd
/bin/sh: ./cuxd: not found
/usr/local/addons/cuxd # ls -lAh cuxd
-rwxr-xr-x    1 root     root      738.3K Jul 17 21:20 cuxd
```

x-Bit ist also gesetzt, es scheint fast so, als ob die Kiste das Binary nicht laden möchte?! 
Habe mir die Datei mal auf den Rechner gezogen und mit file angesehen: 

```
[tobias@tobias-arch Schreibtisch]$ file cuxd 
cuxd: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, stripped
```

Klingt doch eig. erstmal nicht verkehrt, oder? Fehlt irgendwas? 

**Nachtrag:** 
Na Toll! Schönen Monolog gehalten... 
Nach dem letzten File ist mir dann das "interpreter /lib/ld-linux-armhf.so.3" ins Auge gesprungen.
Der LXC-Container emuliert ja eher eine CCU2, als den RaspberrypiMatic. 
Also mal das cuxd_1.7_ccu.tar.gz installiert und siehe da: es funktioniert. 

Ich fänd einen Hinweis darauf im FAQ sehr nett :-)

**Comment by leonsio** [comment]
Hi

Wechselst du von raspberrymatic?

Modprobe Fehlermeldungen ist irrelevant;)

Gruß 

Leo

**Comment by Manawyrm** [comment]
Hi,

ja, genau. 
Daher stammte auch meine initale Idee, das kompilierte Addon für RPiMatic zu nehmen, nicht das für die CCU2, was so natürlich grandios schiefgeht ;)

Viele Grüße,
Tobias

**Comment by leonsio** [comment]
YAHM simuliert komplett eine CCU, deswegen musst du alle Addons gegen „normale“ tauschen
Sag bitte Bescheid ob es dann läuft

Gruß

Leo

**Comment by leonsio** [comment]
YAHM simuliert komplett eine CCU, deswegen musst du alle Addons gegen „normale“ tauschen
Sag bitte Bescheid ob es dann läuft


Gruß

Leo

**Comment by Manawyrm** [comment]
Jo, siehe meinen zweiten Post, mit dem CCU2 Addon läufts jetzt prima :)

Der Hauptgrund warum ich die Issue noch offen gelassen habe, war, dass du das vielleicht irgendwo im FAQ mal erwähnen könntest :-)

**Comment by leonsio** [comment]
habe nur aufm handy mails gesehen und da werden die nachträglichen Änderungen nicht übermittelt ;)  
Ich werde in Wiki aufnehmen, Danke für den Hinweis.
dann schließe ich das Thread
