### ISSUE TITLE
Update Crasht beim Rücksichern des LXC Config

### ISSUE THREAD

**Issue by thkl** [leonsio/YAHM#50]
Issue: 
Die Rücksicherungsroutine sucht im falschen Pfad dadurch crasht das Script

Solution: Zeile 345 und folgede
    progress "Restoring old LXC config"
    cp ${YAHM_TMP}_update/${LXCNAME}/conf\* ${LXC_ROOT}/

**Comment by leonsio** [comment]
danke ist mir ebenfalls aufgefallen, habe gefixt
