### ISSUE TITLE
yahm-init: Deaktivierung von dhcpcd

### ISSUE THREAD

**Issue by pfink** [leonsio/YAHM#54]
Ist das hier 962ebb6 wirklich notwendig? Das zerschießt bei mir erstmal meine gesamte Netzwerkkonfiguration, da mein Router die IPs für den dhcpcd frei hält und ich mich auch an versch. anderen Stellen auf dhcpcd verlasse. Wie würde ein Ansatz _mit_ dhcpcd aussehen, gibt es hier etwas zu beachten?

**Comment by leonsio** [comment]
hallo Patrick 
ja das ist leider notwendig.
1. dhcpd ist nicht Debian (Jessie) und aktuellem Ubuntu konform, zumindest in Moment setzen beide Distributionen auf isc-dhcp
2. dhcpd ist völliger Blödsinn, ich habe meine Interfaces datei und da will ich alle Netzwerk Einstellungen vornehmen und nicht meine statische konfig in anderem tool pflegen
3. Bei dem Großteil der User macht dhcpd nur Probleme weil die damit nicht zurecht kommen (siehe Raspbian Forum)
4. Rapsbian kann sich nicht entscheiden was man nimmt und wechselt im Zuge des Major Releases mal plötzlich von isc-dhcp zu dhcpd, ich habe quasi nur original Jessie Zustand wiederhergestellt.

Ob irgendwann volle Unterstützung für dhcpd kommt, kann ich nicht sagen, du kannst diese gern beitragen von mir wird es diese in Moment nicht kommen.

Theoretisch kannst du YAHM installieren und dhcpd wieder aktiveren, die IP Konfig musst du dann selbst vornehmen.  
Wähle manuelle installation (starte anschließend dhcpd wieder), erstelle manuell mit brctl eine bridge und füge diese per yahm-network -b BRIDENAME attach_bridge dem CCU Container zu

**Comment by pfink** [comment]
Danke für die Antwort! Ich hab' mich inzwischen nochmal durch den Networking-Dschungel von Raspbian gewühlt und werde jetzt wohl auch auf dhcpcd verzichten und stattdessen in Zukunft vollständig auf systemd-networkd setzen (und alles andere deaktivieren), das erscheint mir für meine Bedürfnisse der sauberste und effizienteste Ansatz.

Im Sinne der Kompaitibilität ist der jetzige YAHM-Ansatz aber wohl das Optimum für die breite Masse. Die Bridge müsste ich ja dann manuell konfigurieren, aber so wie ich verstanden habe gibt es hier ja nichts YAHM-spezifisches zu beachten.

**Comment by leonsio** [comment]
Dann sehe ich mich in meiner Entscheidung bestätigt auf dhcpd zu verzichten ;)
