### ISSUE TITLE
Probleme mit der Network-Bridge

### ISSUE THREAD

**Issue by Burki24** [leonsio/YAHM#55]
Hallo Leonsio,

Beim Umyug mit YAHM auf einen Odroid XU4 mit Ubuntu 16.04 (Mate) ergibt sich folgendes Problem:

Beim Erstellen der NEtywerk-Bridge erwartet YAHM ein Device mit Namen: eth0. Bei Ubuntu seit Version 15.10 gibt es diese Bezeichnung so nicht mehr. Dort werden die Devices enx (mit anschliessender Mac) genannt. Demzufolge bricht die Installation der Bridge ab. Als Fehler kommt: 

ERROR: Interface eth0 does not exists
ERROR: This Interface is not supported, please choose only physical interface

Ich habe bisher keine Moeglichkeit gefunden, den Netzwerk-Adapter wieder nach eth0 zu benennen, da dann mein Ubuntu keine Netzwerk-Verbindung mehr herstellt.

Vielleicht kann man das in der Bridge-Installation irgendwie anpassen.

Vielen Dank,

Burkhard

**Comment by leonsio** [comment]
Hi Burkhard 

Verwende bitte manuelle installation (aus dem git branch) bzw die Gui Version 
Da kannst du netzwerkkarte auswählen 

Gruß 

Leo

**Comment by Burki24** [comment]
Hallo Leo,

die Gui bietet mir in der Oberfläche keine Möglichkeit, die Netzwerkkarte zu ändern. Ist jedoch kein Problem, da ich die Bezeichnung in Ubuntu anpassen konnte. Wird auch akzeptiert. Allerdings wird jedesmal, wenn ich die Bridge erstellen will (egal, ob über die Gui oder per command) angezeigt, das der gewählte Bridgename nicht existiert. (No bridge with choosen name found)

Unter yahm-network show_bridge zeigt er mir nur eine: lxcbr0.

Ich weiß, gehört hier eigentlich nicht rein, aber irgendeine Idee ???

Viele Grüße

Burkhard

**Comment by leonsio** [comment]
Hi

Du machst wohl ein Update von lxccu bitte beachte die Einträge im Wiki

Du musst eigentlich nichts umbenennen, sollte auch so gehen. 

Gruß 

Leo

**Comment by leonsio** [comment]
und hat geklappt?

**Comment by Burki24** [comment]
Hallo Leo,

sorry für die späte Antwort. Bin mit der CCU doch wieder auf den Raspi 3 umgestiegen. Lief sofort perfekt. Anscheinend git es beim Odroid noch nen paar Schwachstellen. Inzwischen laufen YAHM und Symcon auf dem Raspi. Und das mehr als perfekt.

Nochmal vielen herzlichen Dank für Eure suuuper Arbeit.

P.S.: Donation geht heute raus. Ich finde, wenn sich Leute solche Mühe geben, sollte man das auch honorieren.

Viele Grüße

Burkhard
