### ISSUE TITLE
Network wird falsch konfiguriert.

### ISSUE THREAD

**Issue by Manawyrm** [leonsio/YAHM#56]
Hi,

auf einem aktuellen Debian Jessie Lite (RPi3) tritt ein problematisches Verhalten des Install-Scriptes auf: 
nach einer Ausführung von yahm-init bzw. den Setup-Scripts ist eine Bridge angelegt, 
eth0 hat aber trotzdem immer noch eine IP, die gleiche wie die Bridge. 
Das verhindert natürlich effektiv jeglichen Netzwerkverkehr. 

Ich nehme an, der Commit hier macht das: 
https://github.com/leonsio/YAHM/commit/962ebb6a21b1c3cdc6757fec973e7e670c4bf356

In Zeile 108 wird mittels sed in der /etc/network/interfaces rumgebastelt:
https://github.com/leonsio/YAHM/blob/master/yahm-init#L108

Die richtige Konfiguration für das eth0 müsste aber doch manual sein, oder? Hier wird die ja von sed auf dhcp gesetzt.

Ideen? 

Viele Grüße,
Tobias

**Comment by leonsio** [comment]
bitte develop branch verwenden, das Problem ist dort bereits behoben
