### ISSUE TITLE
Fehler beim Update auf 2.21.10

### ISSUE THREAD

**Issue by tobias112** [leonsio/YAHM#57]
> root@cubietruck:~# sudo yahm-lxc update
> 
> Installed version: 2.19.9
> Available version: 2.21.10
> 
> Trying to create a backup from installed version 2.19.9, calling: 'yahm-backup data_backup' script
> Clean up TMP directory
> Creating Backup from /usr/local folder
> lxc_container: No such file or directory - failed to open '/proc/644/ns/mnt'
> lxc_container: failed to enter the namespace
> root@cubietruck:~#

**

In dem angegebenen Pfad gibt es den Ordner tatsächlich nicht. Was kann ich tun um das Update durchzuführen?

**Comment by leonsio** [comment]
bitte noch etwas warten bis neue Version online ist, oder die aus dem develop branch verwenden
yahm-ctl update && cd /opt/YAHM && git checkout develop

damit sind viele Bugs was das Update angeht behoben
