### ISSUE TITLE
Fehler bei Direkte Verknüpfungen

### ISSUE THREAD

**Issue by EFAG-Christian** [leonsio/YAHM#58]
Zunächst: super Projekt!
Mein Fehler: unter dem Menüpunkt "Direkte Verknüpfungen" wird bei mir (seit der Installation von YAHM) ein Fehler angezeigt. Habe das System schon seit 4 Tagen am laufen - ist mir aber erst heute zufällig aufgefallen:

An internal error was detected in the service software. The diagnostics are being emailed to the service system administrator (root).

Heck, since you're debugging, I'll show you the errors right here:
can't read "sender_descr(TYPE)": no such element in array
    while executing
"isInExceptionList $sender_descr(TYPE) $receiver_descr(TYPE)"
    (procedure "put_tablebody" line 89)
    invoked from within
"put_tablebody"
    (procedure "put_page" line 42)
    invoked from within
"put_page"

Screenshot:
![fehler-direkte](https://cloud.githubusercontent.com/assets/21197630/17892692/e18dc38e-6942-11e6-862b-d8c9f94a4a1e.jpg)

Browser Cache leeren, Restart des Containers etc. hab ich schon versucht. 

Bin mir nicht 100% sicher dass es am YAHM liegt - wäre aber nahe liegend da unter der CCU2 mit der gleichen Firmware Version noch alles funktioniert hat.

Eine Neuinstallation des Images und Zurückspielen der letzten Sicherung habe ich (noch) nicht versucht. 

Nachtrag: CCU Firmware Version: 2.21.10, YAHM 1.5

**Comment by leonsio** [comment]
Hi

Die Fehlermeldung ist auf den ersten Blick CCU spezifisch und hat nichts mit YAHM zu tun. 
Funktioniert das Funkmodul? Kannst du Einstellung bei den Geräten aufrufen ?

Gruß

Leo

**Comment by thkl** [comment]
Der Fehler tritt auf, wenn ein angelerntes Gerät ein unvollständiges LinkSet (Direktverbindung zwischen Kanälen) zurückgibt. Und zwar genau dann, wenn bei diesem LinkSet Sender und Empfänger der das gleiche Gerät sind. Das sind Geräte, wo eine interne Gerätetaste vorhanden ist und die irgendwas auslöst. (zb Dimmer)

Der Fehler tritt in /www/config/ic_linkpeerlist.cgi auf .. die wird aber durch YAHM nicht angefasst.

**Comment by EFAG-Christian** [comment]
Hm, komisch - hat vor der Portierung in YAHM alles funktioniert. Vielleicht aber auch ein Nebeneffekt beim Backup einspielen. 

Danke thkl für die genaue Beschreibung des Fehlers. Da du dich offensichtlich ziemlich gut mit diesem Fehler auskennst (da ich über 300 Geräte im Einsatz habe komme ich nicht darauf welche Komponente die Ursache sein könnte) - hast du mir einen Ansatz wie ich den Fehler finden / beheben kann? Neue Direktverknüpfungen habe ich jedenfalls schon lange nicht mehr eingefügt gehabt. 
Jetzt alle Dimmer entfernen wäre problematisch. Und einzelne Direktverknüpfungen kann ich so ja nicht löschen.

Das Funkmodul scheint gut zu funktionieren. Alles andere schient auch problemlos zu gehen.

**Comment by thkl** [comment]
Das wird schwer, denn der Fehler tritt bei mir nicht auf.  
Ich denk mal genauer drüber nach.

**Comment by EFAG-Christian** [comment]
ok, danke dir. Ich befürchte jedoch das hat wirklich nichts mit YAHM zu tun und ist nur zufällig gleichzeitig aufgetreten. Je mehr ich mich mit dem Thema beschäftige desto eher vermute ich dass das eher mit dem Firmware Update auf die 2.21.10 neu hinzugekommen ist (hatte seitdem nicht mehr in die direkte Verknüpfungen reingeschaut.) Werde das mal testen.
Danke für das tolle Projekt - bei meiner Komponentenanzahl ist die Beschleunigung der CCU IMMENS!

**Comment by leonsio** [comment]
Stelle log Level auf Maximum ggf. Siehst du mehr Informationen im log

**Comment by EFAG-Christian** [comment]
ok, Problem tritt mit der 2.19.9 Firmware nicht auf - jetzt kann ich nach der Fehlerhaften Verknüpfung suchen. Vielen Dank für die Tipps. War nun doch falscher Alarm für hier - sorry.

PS: ist es Absicht dass die Info-LED an den LAN-Repeatern mit YAHM nicht mehr den Status durch blinken anzeigen? (langsam für Statusmeldungen vorhanden, schnell für Alarmmeldungen forhanden)

**Comment by thkl** [comment]
Und auch mit der Blinkelampe hat YAHM Nix am Hut :)
In der FW 2.21.10 wurden div Änderungen am rfd Daemon gemacht.  Ggf hängt es ja damit zusammen.

**Comment by EFAG-Christian** [comment]
tut mir leid - da muss ich widersprechen. 
- YAHM mit der aktuellsten Firmware 2.21.10: Status LED geht nicht
- CCU2 mit der aktuellsten Firmware 2.21.10 und gleicher Sicherung wie YAHM: Status LED geht

Klar, kann auch ein anderer Effekt sein - ist aber schon sehr nachvollziehbar (zumindest bei mir hier).

PS: ist mir eigentlich auch egal - schau da eh nicht drauf - ist mir nur aufgefallen und wollte darauf hinweisen.

**Comment by leonsio** [comment]
Die LEDs werden vom n YAHM deaktiviert. Allerdings nur auf der CCU ob es auch Effekt auf LAN GW hat, kann ich nicht ausschließen, sollte aber nicht
