### ISSUE TITLE
Nach Update keine Verbindung mehr zu Geräten

### ISSUE THREAD

**Issue by sapcons** [leonsio/YAHM#59]
Nach dem Update auf 2.21.10 (das problemlos durchgelaufen ist) wird kein Gerät mehr gefunden.

**Comment by leonsio** [comment]
hi
läuft das RFD Prozess?

**Comment by sapcons** [comment]
Das werde ich heute prüfen. Zur Sicherheit (wenn nicht): Wie starte ich den Prozess händisch? Danke

**Comment by thkl** [comment]
Am sichersten ist es, die komplette CCU neu zu starten. Da sich RegaHSS auf den rfd Prozess verbinden muss, damit Programme , Scripte und Teile des WebUI richtig funktionieren.
Ansonsten /etc/init.d/S61rfd start und /etc/init.d/S70ReGaHss restart

**Comment by leonsio** [comment]
beachte bitte auch folgenden Wiki Eintrag: [https://github.com/leonsio/YAHM/wiki/Problembehandlung#hs485-oder-hm-lan-gateway-zeigen-kein-status-an-ger%C3%A4te-einstellungen-seite-ist-leer](https://github.com/leonsio/YAHM/wiki/Problembehandlung#hs485-oder-hm-lan-gateway-zeigen-kein-status-an-ger%C3%A4te-einstellungen-seite-ist-leer)

**Comment by leonsio** [comment]
Falls das Problem noch besteht, bitte Ticket erneut aufmachen.
