### ISSUE TITLE
LXCCU Einstellungen der Geräteparameter nicht möglich

### ISSUE THREAD

**Issue by prusede** [leonsio/YAHM#6]
Hard/Software
Rapsberry Pi 2 mit Raspbian Jessie ,
CCU2 Firmware Version 2.17.16)
Rapsberry Pi Funkmodul
HomeMatic RF-LAN Gateway
HomeMatic RS485 Gateway
Backup von  LXCCU 2.15.2 eingespielt 

Unter Einstellungen/Geräte im Feld rechts unter Aktionen dann auf Einstellungen (Kanalparameter einstellen) wird die Fehlermeldung "Das Gerät mit der Seriennummer '123456' vom Interface 'BidCos-RF' konnte nicht abgefragt werden!" oder Das Gerät mit der Seriennummer 'LEQ1323132' vom Interface 'BidCos-Wired' konnte nicht abgefragt werden!.
Meldung kommt bei allen RF und Wired Sensoren.Bei CUxD Geräte kann man die Parameter ohne Problemen auslesen und ändern.

**Comment by leonsio** [comment]
könnte eventuell damit zusammen hängen:

http://homematic-forum.de/forum/viewtopic.php?f=31&t=26879&start=70#p282482

werde dies im Auge behalten

**Comment by leonsio** [comment]
Hi

bitte mach ein Update auf 2.19.9 und schalte Homematic-IP **NICHT** aus

Mit dem HMIPServer der für die Gruppen und auch für die Geräteeinstellungen zuständig ist, komme ich auf die Geräte Einstellungen Seite

Gruß

Leo

**Comment by leonsio** [comment]
Habe gerade ein Update wie geschrieben vorgenommen und auf meinem Rpi3 funktioniert nun alles ohne Probleme
ich Pushe gleich noch ein Commit welches die Bugs schließt

**Comment by prusede** [comment]
Ok muss ich nach dem Update Homematic Ip wieder einschalten, ist im Moment
aus in der Quickinstalltion deaktiviert worden oder ist nach dem Update
Homatic Ip wieder eingeschaltet.
Am 19.05.2016 10:28 schrieb "Leonid Kogan" notifications@github.com:

**Comment by leonsio** [comment]
Hi

Homematic-IP kann man wieder abschalten, es wird HMIPServer nicht mehr ausgetauscht

Gruß

Leo

**Comment by prusede** [comment]
Ok,
also mache ich ein Update von Yham und der CCU auf die 2.19. sonst nichts
und alles sollte gehen??
Am 19.05.2016 12:10 schrieb "Leonid Kogan" notifications@github.com:

**Comment by leonsio** [comment]
Hi

du machst Update auf 2.19.9
dann musst du homematic-ip deaktivieren und hm-mod… installieren. Die Reihenfolge der letzten beiden Schritte ist egal

dann sollte alles gehen 

Gruß

Leo

**Comment by prusede** [comment]
hm-mod...  ist was
Am 19.05.2016 12:56 schrieb "Leonid Kogan" notifications@github.com:

**Comment by leonsio** [comment]
hm-mod-rpi-pcb ;)

**Comment by prusede** [comment]
ok danke
werde ich gegen 22Uhr testen
Am 19.05.2016 13:50 schrieb "Leonid Kogan" notifications@github.com:

**Comment by prusede** [comment]
Hallo,

Habe keine Ahnung: 

So würde ich es heute Abend machen oder lieber neu mit Quickinstallation aufsetzen habe wirklich keinen Plan.
1. ```
      sudo yahm-ctl update                      (update Yahm)
   ```
2. ```
     ???????????????                                (update CCU2)
   ```
   
      3  .  sudo yahm-module -f -m homematic-ip disable  (Homematic IP deaktivieren)
   
      4 .   ?????????????????                              (  hm-mod-rpi-pcb  installieren)

Von: Leonid Kogan [mailto:notifications@github.com] 
Gesendet: Donnerstag, 19. Mai 2016 13:51
An: leonsio/YAHM YAHM@noreply.github.com
Cc: prusede 802070@gmail.com; Author author@noreply.github.com
Betreff: Re: [leonsio/YAHM] LXCCU Einstellungen der Geräteparameter nicht möglich (#6)

hm-mod-rpi-pcb ;)

**Comment by leonsio** [comment]
Hi

Bei einer Neuinstallation führe einfach Quickinstall aus und aktiviere am Ende noch das Raspi-Funkmodul, so wie du es ja bereits gemacht hast
mehr ist nicht notwendig

Gruß

Leo

**Comment by prusede** [comment]
Habe jetzt Pi2 neu mit der Quickinstall ausgeführt und Funkmodul Aktiviert  komme immer noch nicht auf die Geräte Einstellungen.

Von: Leonid Kogan [mailto:notifications@github.com] 
Gesendet: Donnerstag, 19. Mai 2016 17:29
An: leonsio/YAHM YAHM@noreply.github.com
Cc: prusede 802070@gmail.com; Author author@noreply.github.com
Betreff: Re: [leonsio/YAHM] LXCCU Einstellungen der Geräteparameter nicht möglich (#6)

Hi

Bei einer Neuinstallation führe einfach Quickinstall aus und aktiviere am Ende noch das Raspi-Funkmodul, so wie du es ja bereits gemacht hast
mehr ist nicht notwendig

Gruß

Leo

**Comment by prusede** [comment]
Ich weiß nicht weiter,habe wie beschrieben die Quickinstall durchgeführt und Funkmodul aktiviert.

Habe jetzt die FW2.19.9. er wird mir immer noch unter  Startseite > Programme & Verknüpfungen > Direkte Verknüpfungen > Geräte- / Kanalparameter einstellen die Meldung Das Gerät mit der Seriennummer 'IEQ0404272' vom Interface 'BidCos-RF' konnte nicht abgefragt werden! angezeigt.

Lan und RF Gateway bekomme ich auch nichts im Status angezeigt ist alles noch wie vorher nur das jetzt noch das Allgemeine-Einstellungen Problem nach Zentrale-Wartung gewandert ist.

Von: Leonid Kogan [mailto:notifications@github.com] 
Gesendet: Donnerstag, 19. Mai 2016 12:57
An: leonsio/YAHM YAHM@noreply.github.com
Cc: prusede 802070@gmail.com; Author author@noreply.github.com
Betreff: Re: [leonsio/YAHM] LXCCU Einstellungen der Geräteparameter nicht möglich (#6)

Hi

du machst Update auf 2.19.9
dann musst du homematic-ip deaktivieren und hm-mod… installieren. Die Reihenfolge der letzten beiden Schritte ist egal

dann sollte alles gehen 

Gruß

Leo

**Comment by leonsio** [comment]
IEQ0404272 was ist das für ein Gerät?

**Comment by prusede** [comment]
Ist ein RF Funksensor. Habe das bei allen Geräten außer denn  CUxd Geräte.
Am 19.05.2016 21:23 schrieb "Leonid Kogan" notifications@github.com:

**Comment by leonsio** [comment]
ich gehe morgen der Sache nochmal nach
habe dich bis jetzt so verstanden dass das Problem überwiegend bei Geräteeinstellungen auftritt
also Einstellungen/Geräte/irgend ein Gerät/Einstellen

Unter Programme und Verknüpfungen habe ich noch nicht geschaut

**Comment by prusede** [comment]
Ja unter Einstellungen/Geräte/irgend ein Gerät/Einstellen kommt die Meldung
Am 19.05.2016 21:48 schrieb "Leonid Kogan" notifications@github.com:

**Comment by leonsio** [comment]
Kommt die Meldung wenn du Dialog öffnest oder wenn du Änderungen vornimmst und die Einstellungen an Geräte übermittelt werden?
Bei mir scheint alles zu funktionieren

habe frische 2.19.9er Installation genommen und ein Backup von ccu2 eingespielt

<img width="1617" alt="bildschirmfoto 2016-05-21 um 17 55 59" src="https://cloud.githubusercontent.com/assets/786711/15449426/d442a3a2-1f7d-11e6-8043-dabd564001b8.png">
<img width="1616" alt="bildschirmfoto 2016-05-21 um 17 56 20" src="https://cloud.githubusercontent.com/assets/786711/15449428/d4467b1c-1f7d-11e6-8214-8b6ca6f51b6c.png">
<img width="668" alt="bildschirmfoto 2016-05-21 um 17 56 33" src="https://cloud.githubusercontent.com/assets/786711/15449427/d4452014-1f7d-11e6-87a9-e34fabffc65c.png">

**Comment by prusede** [comment]
Wenn ich den Dialog Einstellen anklicke. Könnte es ein das es was mit dem Lan RS485 und RF Gateways liegt. Im  Backup von meinem Bruder ist auch ein RS485 im Betrieb und wie beschrieben wird bei mir auch nicht der Status bei den Gateways angezeigt.

Von: Leonid Kogan [mailto:notifications@github.com] 
Gesendet: Samstag, 21. Mai 2016 18:01
An: leonsio/YAHM YAHM@noreply.github.com
Cc: prusede 802070@gmail.com; Author author@noreply.github.com
Betreff: Re: [leonsio/YAHM] LXCCU Einstellungen der Geräteparameter nicht möglich (#6)

Kommt die Meldung wenn du Dialog öffnest oder wenn du Änderungen vornimmst und die Einstellungen an Geräte übermittelt werden?
Bei mir scheint alles zu funktionieren

habe frischen 2.19.9er Installation genommen und ein Backup von ccu2 eingespielt

 https://cloud.githubusercontent.com/assets/786711/15449426/d442a3a2-1f7d-11e6-8043-dabd564001b8.png 
 https://cloud.githubusercontent.com/assets/786711/15449428/d4467b1c-1f7d-11e6-8214-8b6ca6f51b6c.png 
 https://cloud.githubusercontent.com/assets/786711/15449427/d4452014-1f7d-11e6-87a9-e34fabffc65c.png

**Comment by leonsio** [comment]
ich habe leider kein RS485 im Einsatz nur RF Gateway und damit gehts ohne Probleme
<img width="1155" alt="bildschirmfoto 2016-05-21 um 18 52 25" src="https://cloud.githubusercontent.com/assets/786711/15449687/34066808-1f85-11e6-8171-46ae15abc7e2.png">

geh mal auf Einstellungen/Zentrale Wartung/ und stelle die Logs auf Alles loggen.
Anschließend restarte CCU2 und beobachte /var/log/messages ob es da irgendwelche Fehler gibt, die auf dein Problem deuten können

**Comment by leonsio** [comment]
```
1 homematic-ccu2 daemon.warn ifplugd(eth0)[193]: client: Sending select for 192.168.2.139...
May 21 16:50:22 homematic-ccu2 daemon.warn ifplugd(eth0)[193]: client: Lease of 192.168.2.139 obtained, lease time 86400
May 21 16:50:22 homematic-ccu2 user.info logger: Updating RF Lan Gateway Coprocessor Firmware
May 21 16:50:22 homematic-ccu2 user.debug update-coprocessor: firmware filename is: coprocessor_update_hm_only.eq3
May 21 16:50:22 homematic-ccu2 user.info update-coprocessor: performGatewayCoproUpdate(): updating KEQ1065218
May 21 16:50:22 homematic-ccu2 daemon.info ifplugd(eth0)[193]: Program executed successfully.
May 21 16:50:24 homematic-ccu2 user.info update-coprocessor: Lan Device Information: Protocol-Version: 1 Product-ID: eQ3-HM-LGW Firmware-Version: 1.1.5 Serial Number: KEQ1065218
May 21 16:50:24 homematic-ccu2 user.info update-coprocessor: Lan Device Information: Protocol-Version: 1 Product-ID: eQ3-HM-LGW Firmware-Version: 1.1.5 Serial Number: KEQ1065218
May 21 16:50:25 homematic-ccu2 user.debug update-coprocessor: (KEQ1065218) CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in application.
May 21 16:50:25 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
May 21 16:50:25 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
May 21 16:50:25 homematic-ccu2 user.debug update-coprocessor: CCU2CommControllerMod::handleIncomingResponse() System response OK
May 21 16:50:25 homematic-ccu2 user.debug update-coprocessor: (KEQ1065218) CCU2CommControllerMod::handleIdentifyEvent(): Coprocessor is in application.
May 21 16:50:25 homematic-ccu2 user.debug update-coprocessor: CoprocessorUpdate::startApplication():Coprocessor entered application.
May 21 16:50:26 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::CCU2CoprocessorCommandMod(): System frame
May 21 16:50:26 homematic-ccu2 user.debug update-coprocessor: CCU2CoprocessorCommandMod::isResponseStatusOk(): System status OK
May 21 16:50:26 homematic-ccu2 user.debug update-coprocessor: CCU2CommControllerMod::handleIncomingResponse() System response OK
May 21 16:50:26 homematic-ccu2 user.info update-coprocessor: Version: 1.4.1
May 21 16:50:26 homematic-ccu2 user.info update-coprocessor: Coprocessor firmware not necessary.
May 21 16:50:26 homematic-ccu2 user.info logger: Updating RF Lan Gateway Firmware
May 21 16:50:26 homematic-ccu2 user.info update-lgw-firmware: LAN Gateway Firmware Update...
May 21 16:50:26 homematic-ccu2 user.info update-lgw-firmware: Gateway KEQ1065218
May 21 16:50:28 homematic-ccu2 user.info update-lgw-firmware: Gateway type is eQ3-HM-LGW-App
May 21 16:50:28 homematic-ccu2 user.info update-lgw-firmware: Available Firmware Version:   1.1.5
May 21 16:50:28 homematic-ccu2 user.info update-lgw-firmware: Lan Gateway Firmware Version: 1.1.5
May 21 16:50:28 homematic-ccu2 user.info update-lgw-firmware: Firmware is up to date
May 21 16:50:28 homematic-ccu2 user.info logger: Updating Wired Lan Gateway Firmware
May 21 16:50:28 homematic-ccu2 user.info update-lgw-firmware: No gateway found in config file /etc/config/hs485d.conf
May 21 18:50:32 homematic-ccu2 user.warn multimac: FastMacResponder could not open port /dev/mxs_auart_raw.0: No such file
```

**Comment by prusede** [comment]
Habe den log Order im Nas kopiert http://jenspruss.tankstelle-riesenbeck.com:5000/sharing/g3acqZqjg

Von: Leonid Kogan [mailto:notifications@github.com] 
Gesendet: Samstag, 21. Mai 2016 18:54
An: leonsio/YAHM YAHM@noreply.github.com
Cc: prusede 802070@gmail.com; Author author@noreply.github.com
Betreff: Re: [leonsio/YAHM] LXCCU Einstellungen der Geräteparameter nicht möglich (#6)

ich habe leider kein RS485 im Einsatz nur RF Gateway und damit gehts ohne Probleme
 https://cloud.githubusercontent.com/assets/786711/15449687/34066808-1f85-11e6-8171-46ae15abc7e2.png 

geh mal auf Einstellungen/Zentrale Wartung/ und stelle die Logs auf Alles loggen.
Anschließend restarte CCU2 und beobachte /var/log/messages ob es da irgendwelche Fehler gibt, die auf dein Problem deuten können

**Comment by prusede** [comment]
Das sind aber viele Fehler oder !!!!!!!!!!!!!!!!!!!!

Von: Leonid Kogan [mailto:notifications@github.com] 
Gesendet: Samstag, 21. Mai 2016 18:54
An: leonsio/YAHM YAHM@noreply.github.com
Cc: prusede 802070@gmail.com; Author author@noreply.github.com
Betreff: Re: [leonsio/YAHM] LXCCU Einstellungen der Geräteparameter nicht möglich (#6)

ich habe leider kein RS485 im Einsatz nur RF Gateway und damit gehts ohne Probleme
 https://cloud.githubusercontent.com/assets/786711/15449687/34066808-1f85-11e6-8171-46ae15abc7e2.png 

geh mal auf Einstellungen/Zentrale Wartung/ und stelle die Logs auf Alles loggen.
Anschließend restarte CCU2 und beobachte /var/log/messages ob es da irgendwelche Fehler gibt, die auf dein Problem deuten können

**Comment by leonsio** [comment]
sorry aber das hilft wenig, die wichtigsten Logs kommen nach dem Start und werden später überschrieben
Wie gesagt starte yahm neu (yahm-ctl stop && yahm-ctl start) und gehe auf die Konsole yahm-ctl join und schau oder kopier die Logs nach dem start

Erst da versucht er die Verbindung zu den verschiedenen GWs

**Comment by prusede** [comment]
Ist die log Datei unter /var/log/yahm bin mit winscp auf den PI.

Das komische ist das beide Gateways Senden und empfangen.

Von: Leonid Kogan [mailto:notifications@github.com] 
Gesendet: Samstag, 21. Mai 2016 19:18
An: leonsio/YAHM YAHM@noreply.github.com
Cc: prusede 802070@gmail.com; Author author@noreply.github.com
Betreff: Re: [leonsio/YAHM] LXCCU Einstellungen der Geräteparameter nicht möglich (#6)

sorry aber das hilft wenig, die wichtigsten Logs kommen nach dem Start und werden später überschrieben
Wie gesagt starte yahm neu (yahm-ctl stop && yahm-ctl start) und gehe auf die Konsole yahm-ctl join und schau oder kopier die Logs nach dem start

Erst da versucht er die Verbindung zu den verschiedenen GWs

**Comment by prusede** [comment]
Oder soll ich den Pi über Portweiterleitung freigeben

Von: Leonid Kogan [mailto:notifications@github.com] 
Gesendet: Samstag, 21. Mai 2016 19:18
An: leonsio/YAHM YAHM@noreply.github.com
Cc: prusede 802070@gmail.com; Author author@noreply.github.com
Betreff: Re: [leonsio/YAHM] LXCCU Einstellungen der Geräteparameter nicht möglich (#6)

sorry aber das hilft wenig, die wichtigsten Logs kommen nach dem Start und werden später überschrieben
Wie gesagt starte yahm neu (yahm-ctl stop && yahm-ctl start) und gehe auf die Konsole yahm-ctl join und schau oder kopier die Logs nach dem start

Erst da versucht er die Verbindung zu den verschiedenen GWs

**Comment by leonsio** [comment]
hi schick die Daten über Homematic-Forum
ich brauche 1. Zugang zu SSH auf dem Pi und 2. Zugang zur CCU Gui

**Comment by leonsio** [comment]
Hi

ich glaube ich habs, du hast bei deinen Gateways **keine IP** drin stehen!!!
hab im anderen Thread auch nachgeschaut und da fehlt Bsp: **IP Address = 192.168.2.31**
Trage die IP ein und dann wird es wahrscheinlich gehen

P.S. warum es vorher funktioniert hat, kann ich dir nicht sagen, es steht irgendwo was von Multicast kann aber sein dass die das mit der zeit geändert haben

**Comment by maxikatze** [comment]
Hi !
Ich habe exakt das gleiche Problem wie prusede:

Hard/Software:
Rapsberry Pi 2 mit Raspbian Jessie - gestern neu installiert
CCU2 Firmware Version 2.19.9 - gestern neu aufgesetzt
HomeMatic RF-LAN Gateway - auf Werkseinstellung zurückgesetzt
HomeMatic RS485 Gateway - auf Werkseinstellung zurückgesetzt
CuxD USB Dongle für Uniroll Gurtwickler
Backup (ohne Plugins) von CCU1 eingespielt

Alle Geräte + Programme der CCU1 sind vorhanden und funktionieren prinzipiell - d.h. im Moment ist meine alte und unglaublich langsame CCU1 hinsichtlich der Funktion ersetzt mit dem Raspberry.
Die Aktoren können über die Web-Oberfläche wie auch über die Programme geschaltet werden.

Aber:
1. Unter Einstellungen/Geräte im Feld rechts unter Aktionen dann auf Einstellungen (Kanalparameter einstellen) wird die Fehlermeldung "Das Gerät mit der Seriennummer '123456' vom Interface 'BidCos-RF' konnte nicht abgefragt werden!" oder Das Gerät mit der Seriennummer 'LEQ1323132' vom Interface 'BidCos-Wired' konnte nicht abgefragt werden!.
Meldung kommt bei allen RF und Wired Sensoren.Bei CUxD Geräte kann man die Parameter ohne Problemen auslesen und ändern.
2. Beide LAN Gateways werden nicht mit dem Status "verbunden" angezeigt - sondern gar nichts - aber es funktionieren beide... Bei beiden habe ich auch die IP-Adresse angegeben.
3. Es werden keinerlei Direktverbindungen aus der CCU1 angezeigt

**Comment by leonsio** [comment]
@prusede hast dein Backup auch Wurzeln in der CCU1?
einziger gemeinsamer Nenner ist RS485 GW, habt ihr mal ohne probiert?

ein Funk-GW habe ich auch, und der wird als "Verbunden" angezeigt, dauert zwar paar Sekunden, dann kommt aber die Meldung.

**Comment by leonsio** [comment]
Es kam ein Hinweis aus dem HM Forum, schau mal wie bei dir die InterfacesList.xml aus dem /etc/conifg/ Verzeichnis aussieht

@maxikatze ich habe nie ein Restore aus CCU1 probiert, ich würde folgende Dateien prüfen
1. /etc/config/rfd.conf folgende Einträge müsste drin stehen

Für das Funkmodul falls vorhanden

```
[Interface 0]
Type = CCU2
Description = CCU2-Coprocessor
ComPortFile = /dev/mmd_bidcos
AccessFile = /dev/null
ResetFile = /dev/ccu2-ic200
```

Für das GW falls vorhanden, wobei die IP/Serial/KEy anders seins sollten 

```
[Interface 1]
Type = HMLGW2
Name = CCU2-GW1
Serial Number = KEQ1065218
Encryption Key = vLNg=*CDWx
IP Address = 192.168.2.31
```

die Interfaces Datei sollte etwa so aussehen

```
<?xml version="1.0" encoding="utf-8" ?> 
<interfaces v="1.0">
    <ipc>
        <name>BidCos-RF</name>
        <url>xmlrpc_bin://127.0.0.1:2001</url> 
        <info>BidCos-RF</info> 
    </ipc>
    <ipc>
        <name>VirtualDevices</name>
        <url>xmlrpc://127.0.0.1:9292/groups</url> 
        <info>Virtual Devices</info> 
    </ipc>
    <ipc>
        <name>CUxD</name>
        <url>xmlrpc_bin://127.0.0.1:8701</url> 
        <info>CUxD</info> 
    </ipc>
</interfaces>
```

**Comment by maxikatze** [comment]
Hi leonsio,

Ich werde mich über das kommende "lange" Wochenende damit beschäftigen.
Im Moment habe ich Raspberrymatic laufen mit meinen Gateways - funktioniert alles auch mit Restore aus der CCU1 - daher weiß ich, dass die Hardware OK ist.
Ich möchte aber auf jeden Fall langfristig auf YAHM wechseln - das ist für mich im Augenblick die beste Lösung.

Kann ich einen Restore aus der Raspberrrymatic in YAHM nutzen ? Das entspricht doch einer CCU2 ?

Danke und Gruß

**Comment by leonsio** [comment]
So, das Problem ist nun hoffentlich behoben, wobei die Ursache noch nicht ganz klar ist

https://github.com/leonsio/YAHM/wiki/Problembehandlung#hs485-oder-hm-lan-gateway-zeigen-kein-status-an-geräte-einstellungen-seite-ist-leer

**Comment by prusede** [comment]
Ok Super Danke, wird heute getestet, bei meiner interface. list der alten
CCU  sind noch Einträge mit Seriennummer und Passwort ist das nicht mehr
erforderlich.
Am 25.05.2016 09:40 schrieb "Leonid Kogan" notifications@github.com:

**Comment by maxikatze** [comment]
Hört sich super an :-)
Vielen Dank.
Werde das morgen gleich testen.

**Comment by maxikatze** [comment]
Hi,
Ich komme hier nicht weiter.
Bei mir gibt es kein /etc/config/ Verzeichnis.
Ich bin mit dem Terminal als root angemeldet.
Das einzige was ich finde ist: 
/var/lib/lxc/yahm/rootfs/etc/config_templates
Auch hier kein config-Verzeichnis
Stehe wohl komplett auf dem Schlauch.
Gruss

**Comment by leonsio** [comment]
innerhalb von CCU2 schauen (yahm-ctl join) nicht unter Debian

**Comment by maxikatze** [comment]
Danke - hat geklappt :-)
