### ISSUE TITLE
Einstellungen/Systemsteuerung/Sicherheit funktioniert nicht

### ISSUE THREAD

**Issue by AS-Igel** [leonsio/YAHM#60]
Ich habe jüngst YAHM-Version 1.5 manuell auf einem RasPi (Jessie) installiert und eingerichtet. Die CCU-Firmware-Version ist 2.21.10. Ich hab' zwei HM-Configuration-Tool-LAN (die alten fliegenden Untertassen) hinzufügen können, weitere Adapter oder gar das Raspberry-Funkmodul ist nicht angeschlossen.

Fehler 1:
Bei Auswahl von Einstellungen/Systemsteuerung/Sicherheit wird der Hintergrund ausgegraut, aber es passiert nichts weiter. Ich muss mich wieder neu anmelden, damit das Web-UI funktioniert.

Fehler 2:
Ich hab versucht etliche Geräte aus einer bestehenden Windows-BidCos-Installation zu importieren (dazu gibt's ja auch gute Anleitungen), aber der einzige Hinweis, dass sie *.dev-Dateien halbwegs erkannt werden, ist ein Zähler am Knopf "Posteingang" unter "Geräte anlernen". Wechsele ich in den Posteingang, dann ist die Liste leer; genauso wie die Geräteliste selber.

Leider weiß ich noch nicht so recht, wo ich mit dem debuggen der Fehler anfangen soll. Im Wiki hab' ich dazu nichts gefunden.

**Comment by AS-Igel** [comment]
After an update to the latest RasPi firmware and YAHM running for a longer time both issues are gone.

**Comment by leonsio** [comment]
Freut mich dass alles von alleine geklappt hat :)
