### ISSUE TITLE
YAHM OpenVPN on same device

### ISSUE THREAD

**Issue by sami1979** [leonsio/YAHM#61]
I am running yahm on an raspberry pi 3 and installed openvpn.
I configured it with a tun interface. I can establish the tunnel. I can also ping the IP from raspberry pi.
But I cannot ping the ccu ip.

I can see with tcpdump that the ping request in the tun interface and also on the yahmbr0 interface.
The echo reply I can see in the yahmbr0 interface, but it seems to be not going through the tun interface.

There is no echo reply.

Is there a known incompatibility. Has anyone tried that?
No iptables used. Everything allowed.

**Comment by leonsio** [comment]
ip forwarding enabled?

sysctl -w net.ipv4.ip_forward=1

**Comment by sami1979** [comment]
Yes, enabled

**Comment by leonsio** [comment]
Ich teste das die Tage. 
Weitere Vermutung: Routen insbesondere Ruckroute checken.

**Comment by sami1979** [comment]
Routen sehen gut aus. Müsste alles passen. Thx. Ich bin mal gespannt

**Comment by leonsio** [comment]
Kannst du von CCU deine openvpn Clients anpingen?
Poste bitte die openvpn config und deine ip Netze, damit ich es reproduzieren kann

**Comment by sami1979** [comment]
Ping vom Raspberry zum client über die IP ist möglich.
Das ist meine Config vom server.
[server.zip](https://github.com/leonsio/YAHM/files/518176/server.zip)

Mein Netz ist das 192.168.192.0/24
IP des Raspberry: 192.168.192.10
IP der CCU: 192.168.192.200

**Comment by leonsio** [comment]
sorry bin noch nicht dazu gekommen, hole es aber die tage nach

**Comment by renne** [comment]
Ich empfehle TAP-devices statt TUN-devices. Dadurch ist z.B. das Notebook voll im lokalen Netz eingebunden. Auf dem Raspberry wird das OpenVPN-TAP-device in der /etc/network/interfaces eingebunden:

```
auto yahmbr0
iface yahmbr0 inet dhcp
    bridge_ports eth0
```

wird durch

```
auto yahmbr0
iface yahmbr0 inet dhcp
    bridge_ports eth0 tap0
```

ersetzt.

Auf z.B. dem Notebook wird ein DHCP-Client für tap0 aktiviert. Dadurch bekommt das Notebook IP und Routen durch den Router im lokalen Netz des Raspberries. TAP-devices kapseln keine TCP/UDP-Pakete sondern Ethernet-Frames. Dadurch wird auch Multicast-Traffic übertragen (z.B. IPTV).

**Comment by sami1979** [comment]
Prinzipiell gebe ich dir Recht dass TAP viele Vorteile hat. Leider unterstützt der Android Client kein TAP Mode. Ich hab mal das tun0 in der /etc/network/interfaces den bridge_ports hinzugefügt. Leider erreiche ich die YAHM IP immer noch nicht.
Hattest du es mit TUN in der Konstallation getestet?

**Comment by renne** [comment]
Mit Android nur kurz vor ein paar Jahren. Du benötigst die [OpenVPN Connect App](https://play.google.com/store/apps/details?id=net.openvpn.openvpn) und auf dem Raspberry ein [geroutetes OpenVPN](https://secure-computing.net/wiki/index.php/OpenVPN/Routing). TUN-devices können nicht zu einer Bridge hinzugefügt werden, weil die Bridge nur Ethernet-Frames zwischen Ethernet-devices weiterleitet.

Achtung: Android kann nur ein VPN zur selben Zeit. Mehrere gleichzeitige VPNs (z.B. Fritzbox, TOR, ...) sind nicht möglich.

**Comment by sami1979** [comment]
OK, das erklärt jetzt das Problem. Da muss ich mir was anderes einfallen lassen.
Thx.
Ich close den Issue

**Comment by sami1979** [comment]
Kleiner Nachtrag.
Das TAP Device muss beim Erstellen der Bridge existieren.

Mit den Änderungen in der interfaces hat es geklappt:

auto yahmbr0
iface yahmbr0 inet dhcp
&nbsp;&nbsp;&nbsp;&nbsp;pre-up openvpn --mktun --dev tap0
&nbsp;&nbsp;&nbsp;&nbsp;post-down openvpn --rmtun --dev tap0
&nbsp;&nbsp;&nbsp;&nbsp;bridge_ports eth0 tap0
