### ISSUE TITLE
Statusmeldungen des YAHM-CLIs werden auf stderr ausgegeben

### ISSUE THREAD

**Issue by pfink** [leonsio/YAHM#62]
Es scheint, als würden die Statusmeldungen des YAHM CLIs (offenbar sind alle Befehle betroffen) auf stderr anstatt auf stdout ausgegeben. Das wird insbesondere dann unangenehm, wenn man die YAHM-Installation in ein größeres Installationsskript oder eine Automatisierungslösung wie bspw. [Ansible ](https://github.com/ansible/ansible) einbetten möchte.

Vielleicht ließe sich das bei Gelegenheit ausbessern?

**Comment by leonsio** [comment]
da habe ich wohl zuviel copy&paste gemacht, wird beim nächsten push gefixt

falls du nicht warten möchtest:
https://github.com/leonsio/YAHM/blob/master/share/include.sh#L54
https://github.com/leonsio/YAHM/blob/master/share/include.sh#L61

dort jeweils die Umleitung entfernen, bei error/die würde ich die drin lassen

**Comment by pfink** [comment]
Super, danke Dir!
