### ISSUE TITLE
HM-CFG-USB-2

### ISSUE THREAD

**Issue by SummerWine** [leonsio/YAHM#63]
How to use the HM-CFG-USB-2 with YAHM?

**Comment by renne** [comment]
The HM-CFG-USB-2 does not support uploading firmware-updates on the homematic devices. If you're using a Raspberry I suggest to use the [HM-MOD-RPI-PCB](http://www.elv.de/output/controller.aspx?cid=74&detail=10&detail2=52520).

**Comment by Marioheld** [comment]
That is not true! Openhab, Homegear, RaspberryMatic and fhem can update firmware from Homematic Devices with the HM-CFG-USB-2. Most use this (https://git.zerfleddert.de/cgi-bin/gitweb.cgi/hmcfgusb) converter. So there is technically no argument against integraiting the USB Adapter in YAHM.
