### ISSUE TITLE
xubuntu 16.04 ARM - create bridge

### ISSUE THREAD

**Issue by Feichtmeier** [leonsio/YAHM#64]
Hi! Under xubuntu 16.04 the network interface names are a bit stranger than eth0
When I try to attach the bridge I receive this error:

sudo yahm-network -w create_bridge
Trying to create new bridge yahmbr0 with physical interface eth0
ATTENTION: Network configuration will be changed, you may no longer login to the system!!!
No bridge with choosen name found, continue...
ERROR: Interface eth0 does not exists
ERROR: This Interface is not supported, please choose only physical interface

Is there a way to attach an interface that is named different than eth0? Thanks in advance

**Comment by Folcr** [comment]
"-i" is your friend.

see this: https://github.com/leonsio/YAHM/wiki/YAHM-Netzwerk
YAHM Network management script

Usage Example: 

./yahm-network [FLAG] COMMAND
./yahm-network -n mycccu -b mybridge attach_bridge

Flags:
-n          - LXC container name.
-f          - Force operation (no halt on errors).
-v          - Verbose output 
-b          - Bridge name       (default=yahmbr0)
-i          - Interface name    (default=eth0)
-d          - Dry run (test configuration, without writing changes)
-w          - Write network changes 

Commands:
create_bridge   -  Creating new bridge for LXC Container
delete_bridge   -  Delete bridge and restore configuration
attach_bridge   -  Attach existing bridge to LXC container
dettach_bridge  -  Remove a bridge form LXC container
show_bridge     -  Show system bridges

**Comment by Feichtmeier** [comment]
oh god... thank you :O

Am Fr, 4. Nov, 2016 um 11:22 schrieb Volker B. 
notifications@github.com:
