### ISSUE TITLE
YAHM in ESXi VM - No working HMServer (Java) & No Network

### ISSUE THREAD

**Issue by BOFH90** [leonsio/YAHM#66]
**EN:**

Hi,
The default network configuration doesnt work when the lxc-container runs on Debian Jessie in a VMware ESXi VM. Promiscious Mode has to be enabled on the vswitch on the ESXi-Host and you have to change the config.network settings to "macvlan" to get a dhcp-lease / link.

Also with disabled HM-IP Module the Java-Runtime doesnt work:
-Virtual Devices Error:
`/ # cat /var/log/messages | grep 'VirtualDevices'
Nov  6 11:03:39 homematic-ccu2 local0.err ReGaHss: Error: XmlRpcClientThread::ThreadFunction(): failed call init for interface=VirtualDevices [../Platform/RT/iseRTHss.cpp (163)]`
-Diagrams not working
-"General Settings" doesnt open.
[hs_err_pid268.log.txt](https://github.com/leonsio/YAHM/files/574708/hs_err_pid268.log.txt)
[hs_err_pid265.log.txt](https://github.com/leonsio/YAHM/files/574709/hs_err_pid265.log.txt)
[hs_err_pid260.log.txt](https://github.com/leonsio/YAHM/files/574710/hs_err_pid260.log.txt)
[hmserver.log.txt](https://github.com/leonsio/YAHM/files/574716/hmserver.log.txt)

For the Network, you could add a check if "open-vm-tools" are installed -> if yes, write the "macvlan" settings instead to the network-config.

The rest works flawlessly :) Thumbs up for that great project and your hard work.

**DE:**

Hi, 
Die standart Netzwerk-Config funktioniert auf einem VMware ESXi-Server nicht. Hier erhält der LXC-Container keinen Lease bzw. selbst mit fester IP ist keine Verbindung möglich. Um dies zu beheben muss der "Promiscious Mode" im vSwitch aktiviert werden. Weiter ist hier die "config.network" anzupassen und auf "macvlan" umzustellen. Danach funktioniert die Kommunikation einwandfrei.

Das 2te Problem (leider noch ohne Lösungsweg/Workaround) ist, das das Java nicht funktioniert. Dabei tritt die Meldung "Virtual Devices" auf und die Diagramme und "Allgemeine Einstellungen" lassen sich nicht aufrufen.:
`/ # cat /var/log/messages | grep 'VirtualDevices'
Nov  6 11:03:39 homematic-ccu2 local0.err ReGaHss: Error: XmlRpcClientThread::ThreadFunction(): failed call init for interface=VirtualDevices [../Platform/RT/iseRTHss.cpp (163)]`

Die HMServer.jar habe ich bereits zum test ohne Erfolg ausgetauscht.
Anbei sind noch die Log-Dateien, die mir sinnig erscheinen. Falls mehr benötigt wird, einfach bescheid geben.:
[hs_err_pid268.log.txt](https://github.com/leonsio/YAHM/files/574708/hs_err_pid268.log.txt)
[hs_err_pid265.log.txt](https://github.com/leonsio/YAHM/files/574709/hs_err_pid265.log.txt)
[hs_err_pid260.log.txt](https://github.com/leonsio/YAHM/files/574710/hs_err_pid260.log.txt)
[hmserver.log.txt](https://github.com/leonsio/YAHM/files/574716/hmserver.log.txt)

Der rest funktioniert einwandfrei :) 👍 für das super Projekt und eure harte Arbeit, die bereits investiert wurde und noch wird.

**Comment by Folcr** [comment]
> you have to change the config.network settings to "macvlan" to get a dhcp-lease / link.

That sounds interesting: I had a problem since that the CCU2 doesn't receive a DHCP address by dnsmasq according the MAC address that is specified in /var/lib/lxc/yahm/config.network?? I had to set the network setings inside the CCU2 system configurations.
Can you reveal details how to configure that?

**Comment by BOFH90** [comment]
yes its in "/var/lib/lxc/yahm/config.network"

Heres my config: (static)

```
lxc.network.type = macvlan
lxc.network.macvlan.mode = bridge
lxc.network.flags = up
lxc.network.link = yahmbr0
lxc.network.ipv4 = X.X.X.X/24
lxc.network.ipv4.gateway = X.X.X.X
lxc.network.hwaddr = XXXXXXXXXXXXX
```

**Comment by leonsio** [comment]
Ich würde nicht empfehlen die Software auf x86 zu betreiben. Es macht mehr Sinn die native x86 OCCU zu nehmen. Oder z.B die docker Version. 

Ich habs mit vsphere und Debian Jessie getestet und es hat funktioniert

**Comment by BOFH90** [comment]
Alles klar, nur sollte ja lt. Beschreibung x86 unter Debian Jessie funktionieren. Ich kann dank CCU-Historian auf die Diagramme verzichten. Beim nächsten FW-Upgrade werde ich dann auf die occu migrieren.
