### ISSUE TITLE
RF-LAN-Gateway zeigt keinen Status

### ISSUE THREAD

**Issue by DocZoid** [leonsio/YAHM#67]
Ich habe bereits ähnliche Issues wie diesen gesehen, aber die haben mein Problem nicht gelöst. Daher poste ich meins auch:

Umgebung odroid XU3 
Ubuntu 16.04
Yahm aktuell (yahm-ctl update heute ausgeführt, v1.5)
CCU2 in YAHM v. 2.21.10

Ich versuche, ein HM-LGW-O-TW-W-EU HM-Lan-Gateway anzuschließen. Sonstige HM-Komponenten sind von einer CCU1 per Backup übernommen worden. Ein System-Sicherheitsschlüssel ist gesetzt.

Wenn ich das LAN-Gateway (LGW) anlege mit Seriennummer MEQ... und dem PW vom Etikett (welches offenbar ärgerlicherweise Sicherheitsschlüssel in der Konfiguration heißt und nichts mit dem System-Sicherheitschlüssel zu tun hat, oder?) erscheint kurz der Status "inaktiv".

Wenn ich dann auf Übernehmen drücke (oder erst einer Komponente dieses Modul zuweise und dann übernehme) wird das Feld Status wieder leer.

Zentralen-Neustart über Systemsteuerung->Zentrale-Wartung ... Status-Feld in der LGW-Konfig bleibt leer

Ich kann den Komponenten das Modul zuweisen, aber sobald ich woanders hin klicke und dann wieder zurück in die Einstellungsseite ist die Zuordnung aufgehoben. Auch wenn ich zwischendurch auf Übernehmen klicke.

Die Netzwerk-LED des LGW blinkt langsam grün (keine Anbindung an CCU)

LGW-IP ist aus dem YAHM-Container heraus anpingbar.

InterfacesList Inhalt:
```
<?xml version="1.0" encoding="utf-8"?>
<interfaces v="1.0">
  <ipc>
    <name>BidCos-RF</name>
    <url>xmlrpc_bin://127.0.0.1:2001</url>
    <info>BidCos-RF</info>
  </ipc>
  <ipc>
    <name>VirtualDevices</name>
    <url>xmlrpc://127.0.0.1:9292/groups</url>
    <info>Virtual Devices</info>
  </ipc>
</interfaces>
```
Wenn ich unter BidCos-RF die IP 10.0.1.27 (Da ist kein Zahlendreher, 10...27 ist richtig, und nicht die localhost oder so) einsetze, kommt das UI nicht mehr zurück, wenn ich eine Zuordnung zum LGW konfiguriere...

Irgendwelche Tipps?

Achja, was ich so an Fehlern in logs gefunden habe (beide wiederholt):
messages:
`Nov  7 21:31:30 homematic-ccu2 local0.err ReGaHss: Error: IseESP::ExecError= Execution failed: [-1] 0 0x00 [0] 144 0x90 [1] 0 0x00 [2] 97 0x61 [3] 0 0x00 [4] 99                                                                              0x63  [../Platform/DOM/iseESPexec.cpp (11622)]
`

hmserver.log:
```
Nov 7 21:32:54 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: long-lasting deployment, check deployment configuration - currently deployed 15 out of 17
Nov 7 21:32:54 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-6] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open])
Nov 7 21:32:54 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-9] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [connector.open])
Nov 7 21:32:59 de.eq3.ccu.bidcos.dispatcher.BidCosRpcDispatcher ERROR [Timer-1] Could not register BidCos-RF_java
Nov 7 21:33:01 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-6] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open])
Nov 7 21:33:01 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-9] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [connector.open])
N

```

**Comment by thkl** [comment]
Das GW muss in der /usr/local/etc/config/rfd.conf eingetragen sein

> [Interface 1]
> Type = HMLGW2
> Name = LAN Gateway
> Serial Number = SERIENNUMMER
> Encryption Key = AUTHKEY
> IP Address = IPDESGATES

Das sollte eigentlich das WegGUI machen ....

**Comment by DocZoid** [comment]
Das GW ist dort auch eingetragen. Ohne Namen und ohne IP, weil ich die nicht angegeben habe (steht ja optional an den Feldern. Auch mit Angabe der IP funktioniert es aber nicht).

**Comment by DocZoid** [comment]
LÖSUNG - d'oh! Das PW des LAN-Adapters hat ein vorangestelltest GLeichheitszeichen "=", welches ich (und mindestens auch dieser Kunde hier: http://www.elv.de/topic/funk-lan-gateway-falsches-passwort.html, und meine Frau beim Test auch) nicht als zum Passwort zugehörig erkannt habe.

Alles ok jetzt!
