### ISSUE TITLE
Missing device and channel parameters

### ISSUE THREAD

**Issue by renne** [leonsio/YAHM#68]
Hi,

I installed YAHM, ran "yahm-module -f -m hm-mod-rpi-pcb enable" and imported the CCU2 configuration from LXCCU. When I go to "Startseite > Programme & Verknüpfungen > Direkte Verknüpfungen > Geräte- / Kanalparameter einstellen" the CCU2 headers and footers are shown but "Das Gerät mit der Seriennummer 'XXXXXXXXXX' vom Interface 'BidCos-RF' konnte nicht abgefragt werden! " is shown instead of device information/parameters.

Controlling devices via "Startseite > Status und Bedienung > Geräte" works fine.

How can I debug this?

**Comment by leonsio** [comment]
Bitte schau unter Problembehebung (Wiki) und Vergleiche es mit deiner rfd.conf

**Comment by renne** [comment]
```
[Interface 0]
Type = CCU2
Serial Number = 123456789
Description = CCU2-Coprocessor
ComPortFile = /dev/mmd_bidcos
AccessFile = /dev/null
ResetFile = /dev/ccu2-ic200
```

war trotz "yahm-module -f -m hm-mod-rpi-pcb enable" auskommentiert. Nach Entfernen der Kommentarzeichen und Reboot des kompletten RPis besteht der Fehler weiterhin.

**Comment by renne** [comment]
After a complete re-installation it works, now.
