### ISSUE TITLE
Automatische Installation von sendmail etc.

### ISSUE THREAD

**Issue by jboeddeker** [leonsio/YAHM#69]
Alle MTAs sind normalerweise sendmail-kompatibel, das Installationsskript installiert ohne Rückfrage sendmail, was dazu führt, dass bestehende MTAs ohne Rückfrage entfernt werden.  

Das gilt natürlich für alle Pakete die mit check_install_deb installert werden (sendmail bash-completion wget dos2unix python git lxc liblzo2-dev bridge-utils python-lzo patch gzip openssl), nur bei sendmail gibt es eine MAsse an Alternativen.

**Comment by jboeddeker** [comment]
Achso, vielleicht mit "which sendmail" prüfen, ob etwas sendmail-artiges auf dem System ist, und falls ja das Paket nicht austauschen. (Das könnte man natürlich mit jedem verwendeten Tool so machen)

**Comment by leonsio** [comment]
Ich schaue es mir nochmal an
ich habe extra sendmail gesetzt, da sonst Installationsskript bei einem frischen raspbian lite rummeckert

gruß

Leo

**Comment by leonsio** [comment]
es kommt zu komischen Meldungen bei der Installation, deswegen tausche ich es aus.
Ich muss leider davon auslegen, dass das System exklusiv für YAHM zur Verfügung steht und kann keine Rücksicht auf diverse andere Anpassungen machen

Für die Leute, die bereits etwas verändert haben, existiert die manuelle Installation.
quickinstall ist quasi für Noobs  ;)
