### ISSUE TITLE
LXCCU gibt keinen Status der Lan-Gateways aus.

### ISSUE THREAD

**Issue by prusede** [leonsio/YAHM#7]
Hard/Software
Rapsberry Pi 2 mit Raspbian Jessie ,
CCU2 Firmware Version 2.17.16)
Rapsberry Pi Funkmodul
HomeMatic RF-LAN Gateway
HomeMatic RS485 Gateway
Backup von  LXCCU 2.15.2 eingespielt 

Unter  Einstellungen > Systemsteuerung > Lan Gateway wird der Status beider Gateways nicht angezeigt.
Habe mal HomeMatic RF-LAN Gateway und HomeMatic RS485 Gateway ohne Erfolg neu installiert .
Beider Geräte funktionieren aber in der LXCCU werden halt nicht als Aktiv angezeigt.

**Comment by leonsio** [comment]
Werde ich am Donnerstag angehen. Gruß leo

**Comment by prusede** [comment]
Super bin gespannt, danke für die gute Arbeit.

Gruß Jens
Am 17.05.2016 22:41 schrieb "Leonid Kogan" notifications@github.com:

Werde ich am Donnerstag angehen. Gruß leo

**Comment by leonsio** [comment]
Kannst du bitte zwischenzeitlich bitte deine RS485.conf und rfd.conf aus /etc/config/ Verzeichnis hier posten

Gruß

Leo

**Comment by TheRealTremes** [comment]
Von vorhin? Falls ja, leider nicht. Ist schon alles platt.

**Comment by prusede** [comment]
Hallo,

war heute unterwegs hier die beiden Dateien.

Gruß Jens

Von: Leonid Kogan [mailto:notifications@github.com] 
Gesendet: Mittwoch, 18. Mai 2016 13:22
An: leonsio/YAHM YAHM@noreply.github.com
Cc: prusede 802070@gmail.com; Author author@noreply.github.com
Betreff: Re: [leonsio/YAHM] LXCCU gibt keinen Status der Lan-Gateways aus. (#7)

Kannst du bitte zwischenzeitlich bitte deine RS485.conf und rfd.conf aus /etc/config/ Verzeichnis hier posten

Gruß

Leo

**Comment by leonsio** [comment]
und wie Sie sehen, sehen Sie nichts :(
sehe leider kein Inhalt der Dateien (oder sind die Leer? ;)) 

Gruß

Leo

**Comment by prusede** [comment]
Sind eigendlich .dev Dateien im Ordner

**Comment by prusede** [comment]
2016-05-18 21:07 GMT+02:00 Leonid Kogan notifications@github.com:

**Comment by prusede** [comment]
wie bekomme ich die Dateien hochgeladen
Dateien werden nicht unterstützt !!!!!!

**Comment by leonsio** [comment]
Einfach Inhalte Posten

**Comment by prusede** [comment]
Habe die Dateien mal auf den NAS freigegeben:

http://jenspruss.tankstelle-riesenbeck.com:5000/sharing/h4DQGbrCf

**Comment by prusede** [comment]
rfd:

```
# This File was automatically generated
# TCP Port for XmlRpc connections
Listen Port = 2001

Log Destination = Syslog
Log Identifier = rfd

Persist Keys = 1

#PID File = /var/rfd.pid
#UDS File = /var/socket_rfd

Device Description Dir = /firmware/rftypes
Device Files Dir = /etc/config/rfd
Address File = /etc/config/ids
Key File = /etc/config/keys
Firmware Dir = /firmware
Replacemap File = /firmware/rftypes/replaceMap/rfReplaceMap.xml


[Interface 0]
Type = CCU2
Description = CCU2-Coprocessor
ComPortFile = /dev/mmd_bidcos
AccessFile = /dev/null
ResetFile = /dev/ccu2-ic200

[Interface 1]
Type = HMLGW2
Name = 
Serial Number = MEQ0461006
Encryption Key = +Hk5SK27=4
```

und die hs485d

```
# This File was automatically generated
# TCP Port for XmlRpc connections
Listen Port = 2000

Log Destination = Syslog
Log Identifier = hs485d

[Interface 0]
Type = HMWLGW
Name = 
Serial Number = KEQ0112512
Encryption Key = tNgXHsKmD8

```

**Comment by leonsio** [comment]
mach bitte Update auf die aktuelle Version

```
yahm-ctl update
```

Du kannst dann das nächste Mal beim start unter /var/log/yahm/yahm_console.log die Boot Meldungen einsehen, bitte poste die ebenfalls hier

P.S. damit es leserlich ist vor dem Text 3 solche Zeichen ``` angeben und am Ende ebenfalls, dann wird das als Code interpretiert

**Comment by prusede** [comment]
Was muss ich bei Putty eingeben das ich den Log einsehen kann.

**Comment by leonsio** [comment]
Du musst dich per SSH auf den Host(=Debian) verbinden 

und dann cat /var/log/yahm/yahm_console.log angeben

Gruß

Leo

**Comment by prusede** [comment]
Bekomme es nicht hin

**Comment by leonsio** [comment]
lag wohl am gleichen Problem wie davor, bitte lade dir die aktuelle Version runter (yahm-ctl update) und mach Update auf 2.19.9 damit sollte nun alles gehen
