### ISSUE TITLE
Kein SSH Zugriff über Putty nach Installation

### ISSUE THREAD

**Issue by DaHmM** [leonsio/YAHM#70]
Moin, 
erstmal vorweg spitzen Projekt und vielen Dank für deine Mühen!

Ich habe jetzt folgendes Problem nach der Installation über Putty und der develop UI Oberfläche. 
Homematic läuft und ich kann über die neue IP zugreifen.

Ich kann mich aber nicht mehr über die zweite IP auf das Raspberry Jessie einklinken. Der Netzwerkscanner zeigt mir aber beide IP´s an. 

Ich bin ein ziemlicher Neuling im Umgang mit Linux und das ist mein erstes Projekt.

Viele Grüße

**Comment by fisart** [comment]
Ich hatte das gleiche Problem. Für mich bestand die Lösung darin die Jessie Light installation nicht auf den neuesten Stand zu bringen (update/upgrade)

**Comment by DaHmM** [comment]
Also ich habe jetzt die aktuelle Version White Pixel drauf. Wollte auf die UI nicht ganz verzichten. 
Also System nochmal neu aufsetzen mit einen älteren Light Version?

**Comment by DaHmM** [comment]
Moin, 

bin jetzt endlich dazu gekommen, alles nochmal neu aufzusetzen. 

Aktuelle Version mit Raspberry Light. 

Alles Funktioniert jetzt wie es soll. SSH und Homematic sind über zwei verschiedene IP`s aufrufbar.
