### ISSUE TITLE
Update mit installiertem homebridge Modul.

### ISSUE THREAD

**Issue by bpohvoodoo** [leonsio/YAHM#73]
Wenn man das Homebridge Modul installiert hat schlägt das Update fehl.
Er meckert über das vorhandene /home/pi/.homebridge Verzeichnis

**Comment by Venni27** [comment]
Hängt das vielleicht mit #76 zusammen?
In welchem log steht der Hinweis denn? 
Oder kommt der beim Update in der Konsole?

**Comment by leonsio** [comment]
machst du update über die CCU2-GUI?
falls ja dann müsstest du den Maintainer fragen, ob er eine Prüfung in sein Skript einbaut
