### ISSUE TITLE
Geräte abmelden nicht möglich (YAHM-CCU2 Ubuntu 16.04)

### ISSUE THREAD

**Issue by easyhoo** [leonsio/YAHM#74]
Ubuntu Server 16.04.1 LTS auf ESXi 6.5
YAHM
CCU2 Firmware Version:  	2.25.15

Ich möchte ein Gerät ablernen.
Dazu gehe ich auf dem Webinterface der YAHM-CCU2 wie folgt vor:
1. Einstellungen --> Geräte --> Button unter Aktionen "Löschen"
Es erscheint ein Popup indem die Löschoption "Gerät ablernen" ausgewählt wird
2. Bei Klick auf Löschen erscheint ein neus Fenster:
"Das Gerät 'Türkontakt Kellertür" konnte nicht gelöscht werden. Stellen Sie sicher, das das Gerät sin in Funk-Recihweite befindet...."
3. In diesem Fenster wähle ich "Aus HomeMatic Zentrale löschen" und betätige den Button "Erneut löschen"
4. Das Fenster schließt sich, das Gerät bleibt angelernt

Mit YAHM-CCU2 auf einem RPI3 und der selben CCU2 Konfig sind die Stepts 1 und 2 identisch, ab Punkt 3 funktioniert es da aber einwandfrei, also "Aus HomeMatic Zentrale löschen" klappt.

Viele Grüße,
easyhoo

**Comment by leonsio** [comment]
sorry aber x86 ist experimentell, es kann schon sein dass es nicht alles funktioniert, ich werde aber dem Problem nicht nachgehen, da ich einen Einsatz von YAHM unter x86 für unsinnig halte
