### ISSUE TITLE
Nach Installation Netzwerk nicht erreichbar

### ISSUE THREAD

**Issue by andreheuer** [leonsio/YAHM#75]
Hallo zusammen,

ich versuche seit einigen Stunden auf einem ganz frischen Raspbian (lite und full ausprobiert) YAHM zu installieren. Vor der Installation habe ich lediglich per apt-get update und apt-get upgrade die Pakete aktualisiert.

Die Installation verläuft auch soweit erfolgreich durch, alles wird neu gestartet etc.

Nach der Installation habe ich jedoch Probleme mit dem Netzwerk bzw. der Bridge. Ich kann mich zwar per SSH auf dem RPi anmelden, jedoch keine Adressen oder IPs anpingen, nichtmals den Router:
`pi@raspberrypi:~ $ ping 192.168.2.1`
`PING 192.168.2.1 (192.168.2.1) 56(84) bytes of data.`
`From 192.168.2.150 icmp_seq=1 Destination Host Unreachable`

Die IP für meinen RPi wird per DHCP verteilt und ist in der Fritzbox fest auf die MAC zugewiesen. Die Verbindung funktioniert über das LAN. So sieht es bei mir aus:
```
pi@raspberrypi:~ $ ifconfig
eth0      Link encap:Ethernet  HWaddr b8:27:eb:aa:ec:91  
          inet addr:192.168.2.150  Bcast:192.168.2.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:678 errors:0 dropped:0 overruns:0 frame:0
          TX packets:180 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:153583 (149.9 KiB)  TX bytes:21706 (21.1 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:32 errors:0 dropped:0 overruns:0 frame:0
          TX packets:32 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:2996 (2.9 KiB)  TX bytes:2996 (2.9 KiB)

vethUH0ISC Link encap:Ethernet  HWaddr fe:22:06:b4:dc:2c  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:30 errors:0 dropped:0 overruns:0 frame:0
          TX packets:356 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4321 (4.2 KiB)  TX bytes:89712 (87.6 KiB)

wlan0     Link encap:Ethernet  HWaddr b8:27:eb:ff:b9:c4  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:1 errors:0 dropped:1 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:63 (63.0 B)  TX bytes:0 (0.0 B)

yahmbr0   Link encap:Ethernet  HWaddr b8:27:eb:aa:ec:91  
          inet addr:192.168.2.150  Bcast:192.168.2.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:534 errors:0 dropped:0 overruns:0 frame:0
          TX packets:20 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:109839 (107.2 KiB)  TX bytes:3134 (3.0 KiB)
```
und
```
pi@raspberrypi:~ $ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.2.1     0.0.0.0         UG    0      0        0 eth0
192.168.2.0     *               255.255.255.0   U     0      0        0 eth0
192.168.2.0     *               255.255.255.0   U     0      0        0 yahmbr0
pi@raspberrypi:~ $ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.2.1     0.0.0.0         UG    0      0        0 eth0
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 yahmbr0
```

Ich hatte zuvor YAHM schon erfolgreich genutzt. Ich kann mir dieses Problem hier echt nicht erklären.

Viele Grüße
André

**Comment by Spont** [comment]
Hallo,

ich hab das selbe Problem. Hab das schon mehrfach beobachtet. hast du schon eine lösung gefunden?

hast du deinen raspi mal direkt angeschlossen? und geguckt ob ssh noch aktiviert ist?

**Comment by andreheuer** [comment]
Hallo,

ich habe tatsächlich eine Lösung gefunden.
Ich vermute das Problem im liegt bei Raspbian Jessie im Systemd Subsystem in Kombination mit dem dhclient. Warum auch immer wird das Routing durch die Bridge falsch eingerichtet bei der Initialisierung (default gateway ist durch eth0 und nicht durch die bridge).

Abhilfe schaffte bei mir die Nutzung von dhcpcd anstatt von dhclient. Dazu habe ich zunächst den Dienst dhclient "disabled" und anschließend dhcpcd "enabled". Nach einem Neustart war dann alles soweit funktionstüchtig (wenn auch nicht optimal vom Routing).

Du kannst das auch testen indem Du dhcpcd mal manuell startest (einfach über die Kommandozeile). Dann hat der bei mir das Routing sofort automatisch richtig eingestellt.

Daher liegt hier scheinbar aber kein Problem mit YAHM vor, sondern wohl eher bei Raspbian.
