### ISSUE TITLE
Cuxd 

### ISSUE THREAD

**Issue by Luftloch80** [leonsio/YAHM#76]
Das cuxd Modul lädt die Datei nicht mehr runter

**Comment by dennisausbremen** [comment]
Es wird schon irgendetwas installiert wenn man den FORCE parameter benutzt. Nur wird dann nichts angezeigt.

Mein Problem ist etwas anders. Wenn ich die aktuellste Version von CUXd installiere (1.8a) dann wird mir andauernd:
```
Nicht mit HomeMatic-CCU 127.0.0.1:8181 verbunden!
```
angezeigt. Dadurch kann ich weder Geräte noch sonst irgendetwas anlegen.

**Das Update von YAHM an sich ist auch wonky.**

"_sudo yahm-ctl update_" zeigt an:

```
$ sudo yahm-ctl update
Updating YAHM installation, for updatate CCU2 please use 'yahm-lxc update'
Already up-to-date.
Updating all YAHM modules
Entering 'share/tools/Network-Interfaces-Script'
Von https://github.com/leonsio/Network-Interfaces-Script
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Entering 'share/tools/arm-board-detect'
Von https://github.com/leonsio/arm-board-detect
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Entering 'share/tools/rpi-source'
Von https://github.com/notro/rpi-source
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Updating CCU2-FW archive
YAHM version 1.5 found
New YAHM version 1.6 found, updating
```

Passieren tut genau nichts.
Kann es sein das YAHM generell in der letzten Version Probleme hat?

**Comment by Venni27** [comment]
Genau das Gleiche bei mir. Kein Update mehr möglich trotz neuer Version 1.6.

**Comment by leonsio** [comment]
das YAHM Update macht kein Update von CUXd
es ist ein Anzeigeproblem mit Vorhanden/new ich werde dies in der nächsten Version korrigieren
die jeweils aktuelle Version findet ihr unter /opt/YAHM/VERSION 

falls ihr wollt könnt ihr unter /opt/YAHM/share/include.sh die Version von YAHM_VERSION="1.5"
auf 1.6 hochsetzen
