### ISSUE TITLE
CCU informiert über neuere FW obwohl diese schon installiert ist.

### ISSUE THREAD

**Issue by dennisausbremen** [leonsio/YAHM#78]
Hallo,
ich bekomme in meiner CCU2 mit der aktuellsten YAHM Version (Installiert vor ca. einer Stunde) die Meldung das meine FW veraltet sei.

Die neueste Version soll die ```2.25.15.20161220``` sein obwohl die 2.25.15 ja schon installiert ist.
Gibt es da Probleme mit der FW Liste?

**Comment by leonsio** [comment]
sorry kann dies nicht nachvollziehen, bei mir wird keine neue Version angezeigt außer 2.25.15
die Daten kommen von EQ3 bzw. Homematic und ich kann die nicht beinflüßen, war wohl ein Problem bei denen
