### ISSUE TITLE
BidCos-RF fehler. Anlernen nicht möglich

### ISSUE THREAD

**Issue by NCC1701M** [leonsio/YAHM#79]
Ich habe heute alle Schritte durchgeführt, die [hier](https://github.com/leonsio/YAHM) beschrieben wurden (automatische Installation) Ich habe auch das Rapsberry Pi Funkmodul aktiviert. Allerdings bekomme ich die Fehlermeldung, dass das Anlernen nicht möglich ist.

Ich habe vorher RaspMatic verwendet. Damit funktionierte es ohne Probleme.

Verwendet wurde Raspberry PI 2 ein neue Raspbian-Installation mit aktiviertem SSH und die automatische Installation.

**Comment by Spont** [comment]
Installiere bzw aktiviere das hm-mod-rpi-pcb modul nochmal per Konsole.

**Comment by NCC1701M** [comment]
Hab ich versucht. Keine Änderung.

**Comment by Marv2190** [comment]
wird das Modul angezeigt? (dev/ttyAMA0)
Wenn ja versuch mal "yahm-ctl restart" .
Hatte das Problem auch, hab ich nur doch komplettes neu aufsetzten weg bekommen.
Außerdem hatte ich das Problem das er mal in der rfd.config der ccu # vor den entsprechenden interfaces gesetzt hat...

**Comment by NCC1701M** [comment]
Hallo,

ich habe das Problem gelöst. RaspberryMatic hat mir eine Firmware auf das Modul aufgespielt mit dem YAHM nichts anfangen konnte.

Um das Problem zu lösen habe ich den Raspberry mit einer alten Version von RaspberryMatic gestartet. Das hat wieder die alte Firmware auf dem Modul installiert. Nun funktionierte es auch mit YAHM.

**Comment by thkl** [comment]
Moin, ich hab da schon mal einen Patch für dieses Problem gebaut. Den teste ich gerade und dann schieb ich den in das Repo hier

**Comment by mjoppich** [comment]
@thkl hast du zufällig eine kurze Lösung zur Hand, die du hier hinschreiben kannst? Stehe vor dem gleichen Problem, und habe eigentlich nur mäßig Lust RaspberryMatic (welche Version wird denn benötigt?) zu installieren ...

Danke!

**Comment by thkl** [comment]
auf dem Host die /etc/init.d/hm-mod-rpi-pcb editieren

```
# hold reset until rfd starts
    echo 0 > /sys/class/gpio/gpio18/value
    sleep 0.1
    echo 1 > /sys/class/gpio/gpio18/value
    log_end_msg 0

```

suchen und vor log_end_msg 0 eine Zeile einfügen mit 

`    /opt/YAHM/share/tools/hmgw/hmlangw -f >/var/log/update_coprocessor.log
`

**Comment by mjoppich** [comment]
Danke für die Antwort!

Ich hatte mittlerweile auch den RaspberryMatic-Fix ausprobiert. Benötigt wird:
2.15.5.20151101 (beta2) (https://github.com/jens-maus/RaspberryMatic/releases)

sowie auf dem RPi3 die angepassten Boot-Files:
http://homematic-forum.de/forum/viewtopic.php?t=26917

**Comment by Xento** [comment]
@thkl Ist der Patch, das was du am 8. Januar geschrieben hast?
Das habe ich bereits eingebaut, bringt aber bei mir nichts.

EDIT: habs nun auch mit der alten Raspberrymatic Version hinbekommen.
Bei dem Befehl /opt/YAHM/share/tools/hmgw/hmlangw -f kam immer nur, dass die Seriennummer nicht gefunden werden kann.
Das Modul war komplett neu und hatte vorher Raspberrymatic noch nicht gesehen.

**Comment by F1r3ace** [comment]
Hallo zusammen, 
seit Tagen probiere ich meine System zum laufen zubringen und langsam kommt der Selbstzweifel.
Ich bin relativ neu in der Programmierung, von daher beziehe ich mich viel auf die Tutorials/How-to-Do hier.
Ich hab alle möglichen Varianten ausprobiert, mein PI zum laufen zu bringen. Krieg aber immer wieder ein uns den selben Fehler "BidCos-RF Anlernmodus konnte nicht aktiviert werden".
Ich hab es mit dem Pivccu und mit dem alten homematic ip treiber probiert. leider ohne erfolg. kann mir wer helfen?

viele grüße

**Comment by Marv2190** [comment]
Also du solltest Yahm nicht mehr nutzen. Denke mit Pivccu bist du besser bedient (weil noch aktuell updates kommen). Siehst du in Linux deinen Adapter? Welchen hast du da überhaupt?
