### ISSUE TITLE
Versuch auf FW 2.19.9 schlug fehl... Jetzt geht nichts mehr

### ISSUE THREAD

**Issue by TheRealTremes** [leonsio/YAHM#8]
Hallo,

ich wollte ein Update auf 2.19.9 machen, dort bekam ich jedoch die Meldung 

> `Create new YAHM Container version: 2.19.9
> ERROR: We dont have any patches for this version, please make git pull and try again`

darauf wollte ich manuell installieren:

> yahm-lxc -n CCU2_YAHM -f -v -d /tmp/HM-CCU-2.17.16.tar.gz install

Das lief soweit durch. Bei "yahm-ctl -n CCU2_YAHM start" bekam ich diese Meldung:

> yahm doesn't exist
> Starting CCU2_YAHM LXC container

**Comment by leonsio** [comment]
Hab den Bug gefunden und wird mit dem nächsten Commit gefixt

**Comment by TheRealTremes** [comment]
Vielen Dank!
