### ISSUE TITLE
Keine Installation möglich 

### ISSUE THREAD

**Issue by leiweke** [leonsio/YAHM#81]
System: RPI3 aktuelles Jessy lite up to date 09.01.

leider kann ich keine Installation starten:
root@pi3:/home/pi# wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
2017-01-09 21:11:43 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
An error occurred while processing quickinstall mode. Pleasy try manually installation
root@pi3:/home/pi# wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s ui -
2017-01-09 21:11:54 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
root@pi3:/home/pi# wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -
2017-01-09 21:12:01 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
root@pi3:/home/pi# 

Irgendeine Idee was falsch ist?
Danke Sebastian

**Comment by leonsio** [comment]
Schau bitte unter var/log/YAHM und poste mir den Output aller Dateien die du dort findest

Gruß 

Leo

**Comment by leiweke** [comment]
Hallo Leo,
root@raspberrypi:/home/pi# cd var/log/
bash: cd: var/log/: No such file or directory
root@raspberrypi:/home/pi# cd var/log/YAHM
bash: cd: var/log/YAHM: No such file or directory
root@raspberrypi:/home/pi# 

leider nichts drin.

Eine Sache muss ich erwähnen, ich habe den neuen USB Boot getestet und den RPI3 auf
sudo apt-get update; sudo apt-get install rpi-update
$ sudo BRANCH=next rpi-update
gemacht 
siehe:
https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md

ich habe noch eine neue SD karte mit einem ganz frischen Jessy mit Pixel gebrannt und das gleiche 
pi@raspberrypi:~$ sudo su
root@raspberrypi:/home/pi# wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s ui -
2017-01-09 23:02:32 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
root@raspberrypi:/home/pi# 

sieht immer so aus als ob nach der Plattform Erkennung Schluss ist.

Gruß
Sebastian

**Comment by leiweke** [comment]
ich bin wieder mit dem PI 3 auf per sudo BRANCH=master rpi-update wieder auf das aktuelle firmware release gegangen. Frisches Raspbian mit allen upgrades und dist-upgrade
Leider genau das gleiche:
pi@raspberrypi:~$ 
pi@raspberrypi:~$ wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
2017-01-11 18:08:33 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
An error occurred while processing quickinstall mode. Pleasy try manually installation
pi@raspberrypi:~$ wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s ui -
2017-01-11 18:39:28 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
pi@raspberrypi:~$ wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -
2017-01-11 18:40:40 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
pi@raspberrypi:~$ pwd
/home/pi
pi@raspberrypi:~$ 

ich weiß nicht mehr weiter.

Irgendeine Idee?
Gruß 
Sebastian

**Comment by leiweke** [comment]
Habe von meinem produktiven RPI2 (openhab und YAHM laufen) ein image gezogen und auf einen SD gespielt, ab in den RPI3 und gebootet und leider auch kein Erfolg:

pi@Openhab:~$ wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s ui -
2017-01-11 19:14:34 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
pi@Openhab:~$

**Comment by leiweke** [comment]
habe noch einen PI B+ gefunden und die o.g Produktions Image SD reingeschoben und gebootet. Wieder kein Erfolg:
pi@Openhab:~$ wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s ui -
2017-01-11 19:53:20 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
pi@Openhab:~$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 0010
Serial          : 
pi@Openhab:~$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@Openhab:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
pi@Openhab:~$

**Comment by leonsio** [comment]
Danke

es gibt ein Problem mit aktuellen Raspbian Image
probiere doch bitte die manuelle Installation, ob es damit geht

Gruß

Leo

**Comment by leiweke** [comment]
okay habe folgendes versucht:
pi@raspberrypi:~$ sudo wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -
2017-01-11 21:51:42 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
pi@raspberrypi:~$ 
Leider Nein :-(

oder was ich muss machen ?

**Comment by leonsio** [comment]
schau bitte unter /var/log nach
ich hab mir weiteren Raspi bestellt und werde mir die installation ansehen
alle aktuellen sind im Einsatz

**Comment by leiweke** [comment]
So habe gerade noch ein altes Image gefunden 2016-09-23-raspbian-jessie.zip und installiert. keine Updates gemacht und direkt
pi@raspberrypi:~$ wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
2017-01-14 21:34:24 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
An error occurred while processing quickinstall mode. Pleasy try manually installation
pi@raspberrypi:~$ wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -
2017-01-14 21:34:35 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
pi@raspberrypi:~$ cd /var/log
pi@raspberrypi:/var/log$ ls
alternatives.log  boot.log       daemon.log  dpkg.log        fsck      lightdm   regen_ssh_keys.log  user.log    yahm
apt               bootstrap.log  debug       faillog         kern.log  messages  samba               wtmp
auth.log          btmp           dmesg       fontconfig.log  lastlog   ntpstats  syslog              Xorg.0.log
pi@raspberrypi:/var/log$ cd yahm/
pi@raspberrypi:/var/log/yahm$ ls
pi@raspberrypi:/var/log/yahm$ 

wie du siehst ist kein Log im Directory.

**Comment by leonsio** [comment]
Da ist Ordner YAHM drin. 
Bitte die logs aus dem Posten

**Comment by leiweke** [comment]
da ist aber kein File drin, es ist nur der Ordner da
pi@raspberrypi:/var/log$ cd yahm/
pi@raspberrypi:/var/log/yahm$ ls
pi@raspberrypi:/var/log/yahm$

**Comment by bestguy62** [comment]
Das aktuelle Raspbian hatte bei mir Probleme mit der IP-Adresse. Deshalb wurde nichts heruntergeladen. Bitte auf der Konsole "ping www.heise.de" eingeben und prüfen, ob eine IP zurückgegeben wird. Bei mir hat die Ergänzung der /etc/dhcpcd.conf um die Einträge

eth0
static ip_adress=192.168.1.???
static routers=192.168.1.1 
static domain_name_servers=8.8.8.8

geholfen.

**Comment by leonsio** [comment]
Ich hab mir eine. Raspi bestellt. Sobald er kommt teste ich alles mit neuem raspbian

**Comment by bestguy62** [comment]
Bitte auch prüfen, warum nach automatischer Installation SSH nicht mehr geht.

Outlook for Android<https://aka.ms/ghei36> herunterladen



On Wed, Jan 18, 2017 at 12:45 PM +0100, "Leonid Kogan" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ich hab mir eine. Raspi bestellt. Sobald er kommt teste ich alles mit neuem raspbian

**Comment by leiweke** [comment]
IP Verbindung ist da und das Skript wird ja auch zum Teil ausgeführt, weil "Found ARM based distribution" ja eine Ausgabe vom Skript ist.
Das Skript bricht immer nach der Plattform Erkennung bei mir ab.

SSH ist seit dem letzten Jessie update ausgeschaltet, du muss ein file names ssh in die root legen dann wird ssh beim ersten booten (so wie früher) eingeschaltet.
Mal in den Release notes nachgelesen.
http://downloads.raspberrypi.org/raspbian/release_notes.txt
2016-11-25:
  * SSH disabled by default; can be enabled by creating a file with name "ssh" in boot partition
Gruß
Sebastian

**Comment by leonsio** [comment]
die bauen immer mehr und mehr scheiße mit dem Raspbian
warum können die es nicht einfach beim Debian Standard belassen

Gruß

Leo

**Comment by leiweke** [comment]
SSH ein beim start und default Passwort ist ein Sicherheitsrisiko daher. Und das ist auch gut so das sie es geändert haben. Mich persönlich hat das schon lange gestört das es automatisch an ist.

**Comment by leonsio** [comment]
man kann nicht immer den user bevormunden
bisschen Eigenverantwortung ist nicht viel verlangt

**Comment by leiweke** [comment]
ja das stimmt

Hoffe das du heraus bekommst was die Ursache ist, mit dem Skript und dem neuen Image.
Ich muss alles neu aufsetzen und komme leider nicht weiter.
VIELEN DANK für deine Arbeit hier.

Eigentlich würde ich auch gerne auf x86 VMware mit Ubuntu gehen. Funktioniert dein Skript dort?
Ich habe mir schon OCCU angeschaut, aber da traue ich mich mit meinen rudimentären Linux Kenntnissen nicht dran.
Wäre klasse wenn YAHM auf Ubuntu laufen würde.

**Comment by leonsio** [comment]
Es läuft auf debian 6 aber es macht technisch gesehen wenig sinn 


Von meinem iPad gesendet

**Comment by wjentner** [comment]
Hi also ich habe vor kurzem auf einem Raspi 3b und mit dem aktuellen Raspbian Jessie Lite probiert und bei mir ist die Installation ohne Probleme durchgelaufen.

**Comment by leiweke** [comment]
Ich habe Pi 2 und Pi 3 mit aktuellem Raspbian Jessie full und light und noch ein altes Raspbian Jessie full vom 23.09. in allen Kombinationen ausgeführt. Immer der gleiche Abbruch nach der Platform Erkennung und auch keine Logs.

**Comment by leiweke** [comment]
@leonsio wäre es schwer das Skript auf Ubuntu 16 anzupassen?

**Comment by leonsio** [comment]
Sollte auch laufen. Einfach probieren

**Comment by leiweke** [comment]
Okay setze heute Abend mal ein VM mit Ubuntu Server 16.04.1 LTS auf und teste

**Comment by leiweke** [comment]
Hallo Leo, gibt es schon was neues? Ich muss mein System neu aufsetzen. Danke dir 
Gruß
Sebastian

**Comment by leonsio** [comment]
hi 

hab grad auf meinem raspi2 die installation durchlaufen lassen und es funktioniert alles einwandfrei

somit kann ich deine Probleme nicht nachvollziehen, ich werde die tage vielleicht noch auf einem pi3 testen, jedoch macht es an sich keinen Unterschied

```
wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
bash: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF-8)
2017-01-29 16:37:22 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
Disable new dhcpcd on Raspbian Jessie
Updating sources
Installing dependencies
install sendmail
....
```

was das SSH angeht, so werde ich da nichts machen, es hat nichts mit YAHM zu tun. abgesehen davon werdet Großteil aller User das System headless also ohne Display. Um YAHM zu installieren muss SSH sowieso laufen, sonst kommst du nicht auf das System

Somit schließe ich diese Baustelle, Probere ggf andere SD-Karte, ggf. ist diese Defekt oder du hast ein anderes Problem.
Wenn ich mir ansehe wo dein System sich verabschiedet, so ist an der Stelle noch nichts aus dem eigentlichen YAHM in Verwendung

```bash
# check architecture
case `dpkg --print-architecture` in
    armhf|arm64)
        info "Found ARM based distribution"
        ;;
    i386|amd64)
        info "X86 CPU found, need to install QEMU"
        check_install_deb "qemu-user-static binfmt-support"
        ;;
    *)
        die "Unsupported CPU architecture, we support only ARM and x86"
        ;;
esac

# Check the distribution is in the supported list
case "$DIST_ID:$CODENAME" in
Raspbian:jessie) DIST="debian";;
Debian:jessie)	DIST="debian";;
Ubuntu:xenial)  DIST="ubuntu";; 
*)		die "Sorry, this script does not support your distribution/release ($DIST_ID $CODENAME)." ;;
esac

if [ "$DIST_ID" = "Raspbian" ] ;
then
  info "Disable new dhcpcd on Raspbian Jessie"
  systemctl disable dhcpcd.service 
  systemctl stop dhcpcd.service
  sed -i /etc/network/interfaces -e "s/iface eth0 inet manual/auto eth0\niface eth0 inet dhcp/"
fi

```
es wird nur geprüft ob es sich um ARM oder x86 handelt, alles Standard Linux abfragen
