### ISSUE TITLE
Bereits angelernte ( an eine andere Zentrale (FHEM)) Geräte lassen sich nicht an CCU2 anlernen 

### ISSUE THREAD

**Issue by besitzer** [leonsio/YAHM#83]
Hallo,

ich versuche den Wechsel von FHEM zu ioBroker und würde dafür gerne YAHM als CCU2 verwenden.
YAHM mit einer CCU2 Installation läuft auch eigentlich sehr gut.
Ich habe mir 5 neue HM Geräte (Lichtschalter) besorgt und konnte diese auch problemlos an die YAHM CCU2 anlernen.
Leider bekomme ich meine "alten" Geräte, die bereits über den LAN Adapter an FHEM angelernt wurden, nicht an die neue CCU2 anlernen. Diese werden schlichtweg nicht gefunden.
Ich habe es mit dem LAN Adapter mit und ohne Verschlüsselung versucht. Auch habe ich FHEM komplett ausgeschaltet, da die Geräte bereits nach ca. 5-10 Sekunden den Anlernmodus verlassen und ich zunächst die Vermutung hatte, dass FHEM sie erneut anlernt (obwohl FHEM nicht auf Anlernen gestellt).
Ein Update des LAN Adapters auf die aktuelle Firmware habe ich ebenfalls durchgeführt. Die "alten" Geräte sind ca. 1 Jahr alt. Ich bekomme keine Fehlermeldung. 
Meine Hardware ist ein Intel NUC x64 mit Ubuntu 16.04.1 und einer CCU2 Firmware 2.25.15.

Danke für die Hilfe.

Gruß Sven

**Comment by leonsio** [comment]
Du musst die vorher anlernen
Frag dazu sonst im homematic Forum nach. Es ist kein YAHM Problem;)

**Comment by besitzer** [comment]
Alles klar. Danke für die schnelle Antwort.

 

 

 

Von: Leonid Kogan [mailto:notifications@github.com] 
Gesendet: Dienstag, 24. Januar 2017 09:08
An: leonsio/YAHM <YAHM@noreply.github.com>
Cc: besitzer <besitzzzer@aol.com>; Author <author@noreply.github.com>
Betreff: Re: [leonsio/YAHM] Bereits angelernte ( an eine andere Zentrale (FHEM)) Geräte lassen sich nicht an CCU2 anlernen (#83)

 

Du musst die vorher anlernen
Frag dazu sonst im homematic Forum nach. Es ist kein YAHM Problem;)
