### ISSUE TITLE
YAHM / LXC bricht USB Verbindung ab

### ISSUE THREAD

**Issue by klarlichter** [leonsio/YAHM#84]
Hallo, ich benutze auch yahm.
Allerdings habe ich ein Problem, sobald der lxc Container läuft kann ich keinen ttl to usb Stick verwenden.
Der hängt sich regelrecht auf. Offensichtlich liegt es daran, dass der LXC Container UDEV benutzt und somit der Raspberry das nicht mehr steuert und sofort an den LXC Container weitergibt.

Ich würde jedoch gern den TTL to USB Stick auf dem Raspberry verwenden können. Kann mir jemand sagen, wo man welche Datei anpassen muss, damit der Stick am Raspberry verwendet werden kann und nicht direkt zum LXC Container von YAHM weitergereicht wird?

Viele Grüße
Sebastian

**Comment by leonsio** [comment]
siehe 

http://man7.org/linux/man-pages/man1/lxc-device.1.html

du musst dein Gerät aus dem Container entfernen, da alle USB Geräte an das Container durchgereicht werden

**Comment by klarlichter** [comment]
Hi, bescheidene Frage aber kannst mir genau sagen wie ich das mache ? Wie finde ich raus wie es heißt und wie kann ich dieses genau ausschließen?

**Comment by leonsio** [comment]
ok hab grad nachgesehen es werden alle Geräte pauschal an das LXC übergeben, du kannst kein gerät ausschließen, du müsstest diesen Authomatismus abschalten.

du müsstest ansehen welche "ID" es unter /dev benutzt und mit cgroups diese in der lxc-config ausschließen

siehe /var/lib/lxc/yahm/config 

ich nehme an es ist dieser Eintrag

lxc.cgroup.devices.allow = c 136:* rwm

da er alle gerate unter 136:XXXX an das Container durchreicht

**Comment by klarlichter** [comment]
Hi. 
Und wie kann ich dann ein bestimmtes an lxc weiterreichen wenn ich das andere deaktiviere ? Betrifft das dann nur USB? 
Denn die homematic Funk Platine sollte ja weiterhin gehen. Und mein CUL Stick auch.

**Comment by leonsio** [comment]
https://www.google.de/search?q=lxc+usb+passthrough

Pi-Funk-Adapter wird automatisch durchgereicht und ist nicht davon betroffen

**Comment by klarlichter** [comment]
Also muss ich das nun wie du oben geschrieben hast unterbrechen und den CUL Stick weitergeben??

**Comment by leonsio** [comment]
Im Prinzip ja
wie gesagt ich bin mir nicht ganz sicher ob es diese cgroup war, da musst du etwas experimentieren und unter /dev schauen

Gruß

Leo

**Comment by klarlichter** [comment]
hmmmm.....:( wäre super wenn du es genau wüsstest...:(

**Comment by klarlichter** [comment]
Hallo,
also ich habe nun den Eintrag:

lxc.cgroup.devices.allow = c 188:* rwm (188 statt 138) auf deny bzw disable gesetzt und es hilft nicht....
also konkret:
lxc.cgroup.devices.disable = c 188:* rwm
lxc.cgroup.devices.deny = c 188:* rwm

Es hilft aber nichts. Kannst du mir bitte sagen WIE ich dieses weiterreichen generll unterbinden kann... Ich bin echt verzweifelt das will einfach nicht gehen. Er reicht immer alles dennoch weiter....:/

**Comment by klarlichter** [comment]
Hi! Problem gefunden.
Es tritt nur auf wenn in der CCU2 das Programm cuxd installiert ist. Also alle die cuxd verwenden aber auf dem raspberry einen usb stick verwenden wollen ist zwangsweise in der cuxd ini eine Anpassung nötig!

Es muss in der ini - Datei der bzw die USB Port/s benannt werden welche vom cuxd zu benutzen sind.
