### ISSUE TITLE
java.io.IOException: Inappropriate ioctl for device in nativeavailable

### ISSUE THREAD

**Issue by wagner4u** [leonsio/YAHM#85]
Hi,
habe yahm frisch auf eine neue SD-Karte intsalliert (automatische Installation) mit einem eq3-Funkmodul.
Installation und Übernahme des Backups meiner CCU2 in den lxc-Container funktionierte.
Soweit alles ok. 
Aber im hmserver.log erhalte ich extrem schnell und extrem viele dieser Meldungen:

Jan 31 19:47:23 de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice ERROR [Thread-5] Error while reading from serial port:
java.io.IOException: Inappropriate ioctl for device in nativeavailable
        at gnu.io.RXTXPort.nativeavailable(Native Method)
        at gnu.io.RXTXPort$SerialInputStream.available(RXTXPort.java:1568)
        at de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice.serialEvent(SerialCommDevice.java:134)
        at gnu.io.RXTXPort.sendEvent(RXTXPort.java:780)
        at gnu.io.RXTXPort.eventLoop(Native Method)
        at gnu.io.RXTXPort$MonitorThread.run(RXTXPort.java:1611)

Irgendeine Idee ?
wagner4u

**Comment by leonsio** [comment]
Bitte nach dem einspielen des backups homamtic ip Modul entfernen

**Comment by wagner4u** [comment]
Hi,
homematic ip Modul ist entfernt (schon vor dem Backup) und ist nun immer noch entfernt.
So zumindest in yahm-ui (siehe screenshot).
![image](https://cloud.githubusercontent.com/assets/25456969/22480295/30f28270-e7f1-11e6-88ea-90abc1928cc9.png)

**Comment by leonsio** [comment]
Bitte über Clip mit Force Switch

**Comment by wagner4u** [comment]
Danke. Das hat jetzt funktioniert. Danach funktionierte aber das Funkmodul nicht mehr.
Habe dann das Modul disabled und enabled. Jetzt geht es wieder.
Aber im hmserver.log kommt nun regelmäßig:

Jan 31 20:48:44 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-4] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open])
Jan 31 20:48:44 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-3] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [connector.open])
Jan 31 20:48:51 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-4] SYSTEM ADVICE: pre-conditions for deployment of LocalServerFirmwareUpdateInitialization still not met - check deployment configuration  (still unfulfilled: [connector.open])
Jan 31 20:48:51 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-3] SYSTEM ADVICE: pre-conditions for deployment of LegacyInitializion still not met - check deployment configuration  (still unfulfilled: [connector.open])
Jan 31 20:48:58 de.eq3.cbcs.vertx.management.VertxManager WARN  [vert.x-eventloop-thread-0] SYSTEM ADVICE: long-lasting deployment, check deployment configuration - currently deployed 15 out of 17

wie bekomme ich das nun weg ?

**Comment by leonsio** [comment]
leider überhaupt nicht
