### ISSUE TITLE
HM-MOD-RPI-PCB ist nach Backupwiederherstellung weg 

### ISSUE THREAD

**Issue by tis-cs** [leonsio/YAHM#86]
Hallo,
ich versuche seit einigen Tagen das HM-MOD-RPI-PCB zum Laufen zu bekommen und habe es naiverweise einfach mal aufgestecket und via yahm-ui aktiviert.

Zum Hintergrund, ich arbeite auf nem Pi2, habe sowohl CuxD, ein original LAN Gateway und ein Wirde Gateway laufen. 

Da der neue Funkadapter nicht in der Geräteübersicht auftauchte und in der Systemsteuerung-->LAN Gateway Konfiguration auch nur mein originales Gateway zu sehen war habe ich lange mit den   config files etc. rumprobiert. Hat alles nicht geholfen. [Hier](http://homematic-forum.de/forum/viewtopic.php?f=56&t=35387) meine Versuche.

Nun habe ich den Container gelöscht und ein nacktes 2.25.15 installiert und via yahm-ui den Adapter aktiviert. Und siehe da, er taucht sofort in den Geräten auf. Somit ist ein Defekt auszuschließen. Danach habe ich nur meinen LAN Adapter hinzugefügt, welcher nach einem Reboot auch auftaucht, jedoch wird mir in der Geräteübersicht sowie und in der Systemsteuerung-->LAN Gateway Konfiguration weiterhin nur ein Adapter angezeigt. Meiner Vermutung nach nur der originale LAN Adapter.

Habe dann mal nach diesem [Issue](https://github.com/leonsio/YAHM/wiki/Problembehandlung#hs485-oder-hm-lan-gateway-zeigen-kein-status-an-ger%C3%A4te-einstellungen-seite-ist-leer) nachgegangen und habe die Dateien entsprechend erweitert.
Hat leider nichts gebracht, da sie nach einem Reboot immer wieder den ursprünglichen Inhalt haben...

Habe dann den LAN Adatper noch mal rausgeworfen und hab mir den aufgesteckten Adapter unter Systemsteuerung-->LAN Gateway Konfiguration angeschaut. Hier wird mir in der Spalte Gateway für ca. 5 Sekunden eine SN angezeigt, die dann auf "(Standard)" wechselt.

Ziel war es eigentlich mein Update wieder einzuspielen, was auch gelingt, nur da sehe ich überhaupt nichts mehr vom HM-MOD-RPI-PCB. Diesen wollte ich eigentlich fix zwei Aktoren zuordnen.

**Comment by thkl** [comment]
Wenn das Backup von einem System ohne installierten HM-MOD-RPI-PCB ist, dann ist dieser nach dem Einspielen des Backups weg, da dessen Konfiguration mit im Backup steht.
Nach Restore einfach das Modul wieder aktivieren

**Comment by tis-cs** [comment]
Ich habe gestern Abend den "Fehler" gefunden. Habe dazu einen komplett frischen CCU2 Container mittels yahm-ui erstellt. Diese war dann natürlich leer und unvorbelastet. Die Option für den  HM-MOD-RPI-PCB habe ich direkt beim erstellen des Containers aktiviert gelassen. Danach bootete die CCU und der Adapter tauchte auch in der Geräteverwaltung auf. Soweit so gut. 

Dann habe ich meinen originalen LAN Adapter  als Lan Gateway mittels SN und Sicherheitsschlüssel hinzugefügt. Nach einem Reboot tauchte er auch unter  Systemsteuerung-->LAN Gateway Konfiguration auf und war verbunden. 
Allerdings ist ab diesem Zeitpunkt nur noch ein Gateway in der Geräteübersicht. Es ist in der LAN Gateway Konfiguration kein zweites Gateway aufgeführt, sodass man eine Zuordnung zu anderen Aktoren machen kann.

Es muss wohl ein Problem geben, wenn man ein zum HM-MOD-RPI-PCB ein Lan Gateway einbinden will. Der HM-MOD-RPI-PCB taucht dann nicht mehr im System auf.

##  hw-fake-lan-gw nutzen
Ich habe es jetzt so gelöst, dass ich über das yahm-ui die HM-MOD-RPI-PCB Option deaktiviert habe, dann erneut in die yahm-ui, die hw-fake-lan-gw Option an, Reboot und anschließend in Systemsteuerung-->LAN Gateway Konfiguration ein neues Lan Gateway hinzugefügt.

## Hierbei gibt es zwei drei Sachen, die UNBEDINGT zu BEACHTEN sind!
### SN herausfinden
Man benötigt die SN des Adapters, welche entweder per QR auf dem Adapter aufgedruckt ist. 
Hier darauf achten, dass ihr den richtigen scannt. Es gibt zwei weitere Codes, von denen der untere im Bild den gleichen Aufbau wie ein HM Gerät hat (10 stellig, ABC1234567)

![img_4460](https://cloud.githubusercontent.com/assets/24519878/22584441/b1381c08-e9f2-11e6-8661-ac99a6d0dd3f.jpg)

Sicherer ist es, wenn man die von hmgwlan ausgelesene nimmt, die man mit `cat /opt/YAHM/share/tools/hmgw/serialnumber.txt` anzeigen lassen kann.

Falls diese Datei nicht da ist, was bei mir auch lange so war, kann es unter anderem daran liegen, dass im yahm-ui die Option für hm-mod-rpi-pcb noch an ist. 

Ansonsten kann man auch den Container stoppen und mit `/opt/YAHM/share/tools/hmgw/./hmlangw -n show` sich die SN auslesen und anzeigen lassen.

### IP eintragen
Man muss zuletzt die IP des Gateways eintragen. Hier bitte unbedingt die IP des Hosts (vom Pi) und **nicht** die vom yahm Container/CCU2 oder 127.0.0.1 nutzen! Nach einem Reboot ist dann das Gateway mit aufgeführt und verbunden. 
![bildschirmfoto 2017-02-03 um 09 41 52](https://cloud.githubusercontent.com/assets/24519878/22584996/cb9261a0-e9f5-11e6-989f-c2033326ad57.png)

Nun können auch direkte Zuordnungen zu einzelnen Aktoren gesetzt werden
![bildschirmfoto 2017-02-03 um 09 41 32](https://cloud.githubusercontent.com/assets/24519878/22584999/cf31646e-e9f5-11e6-91b9-fca71326225d.png)

Allerdings taucht das Fake GW nicht in der Geräteübersicht auf, was meiner Meinung nach auch noch ein Fehler sein müsste.

**Comment by tis-cs** [comment]
Ich habe es noch mal eben als internes Modul getestet. Habe im ui den Fake-Adapter rausgenommen, Reboot, den Adapter als internen aktiviert und ebenfalls gerebootet. Der Adapter taucht definitiv nicht im System auf. Auch unter der Lan Gateway Konfiguration wird er mir nicht als Möglichkeit bei der  Interface-Zuordnung angezeigt.

Habe die Schritte rückwärts gemacht, sodass er nun wieder als Fake Lan Gateway verbunden wird.

**Comment by leonsio** [comment]
Interner Modul taucht nie unter Gatrways auf, er ist nur unter Geräte zu finden

Gruß

Leo
