### ISSUE TITLE
Erste Homematic über ESXI 6.5 - Ubuntu 16.04 Server (x64) - LAN Gateway (1.1.3) Kommunikationsprobleme

### ISSUE THREAD

**Issue by csice** [leonsio/YAHM#88]
Hallo zusammen,
ich habe auf meinem Homeserver begonnen Homematic zu installieren und soweit auch alles zum laufen bekommen... Aktuell stecke ich aber so fest, dass ich nicht mehr weiter weiß.
Damit ihr den Zusammenhang versteht muss ich etwas ausholen:
Aktoren:
2x HM-LGW-O-TW-W-EU-2 (da ich hier zuerst an einen defekt dachte hab ich mir 2 organisiert)
1x HM-ES-PMSw1-PI
1x HM-TC-IT-WM-W-EU
FW 2.25.15 -> Install Problemlos -> Gateway gefunden & verbunden -> Anlernen nicht möglich.
FW 2.7.17 -> Anlernen und schalten möglich -> kein Zugriff auf  Zentralen-Wartung (Workaround aus Wiki hilft nicht)
Update von 2.7.17 -> 2.25.15 läuft durch, danach wieder keine Kommunikation möglich.
Aktivieren/Deaktivieren von HMip ändert nichts.

Interessant dabei ist, das es wohl überwiegend nur die ausgehende Kommunikation ist da änderungen am Thermostat fast augenblicklich in der WEBui angezeigt werden. Hat jemand eine Idee woran das liegen könnte?

Im voraus vielen Dank für eure Unterstützung

**Comment by leonsio** [comment]
Sorry aber ich kann dir da nicht helfen. 
Ich unterstütze x86 platform nicht. 
Probier doch lieber die docker Version aus, die gibt es native auf x86

Gruß 

Leo
