### ISSUE TITLE
YAHM auf akutellen Raspbian Jessie Lite ohne Fehlermeldung installiert, Anlernenmodus aktivierbar, jedoch keine Geräte sichtbar.

### ISSUE THREAD

**Issue by c280driver** [leonsio/YAHM#89]
Hallo und danke für dein tolles Projekt.

Ich kämpfe schon mehrere Abende YAHM bzw. das Funkmodul zum laufen zu bringen. Einen Hardware Defekt schließe ich aus. Der Servie läuft und wirft auch keine Fehlermeldungen auf der UI nur es werden halt keine Geräte gefunden.

**Siehe das Boot Log des YAHM Containers** [yahm boot log.txt](https://github.com/leonsio/YAHM/files/752870/yahm.boot.log.txt)

Wenn ich den Service mit yahm-ctl beende und dann ./start-hmlan.sh -v ausführe erhalte ich erfreuliche Weise positive Lebenszeichen des Modules.

hmlangw: no process found
Read serial number NEQ1329111 from /opt/YAHM/share/tools/hmgw/serialnumber.txt
serial fd 3 name /dev/ttyAMA0
reset fd 4 gpio port 18
bidcosThread started!
keepAliveThread started!
Received 17 bytes from serial
0000: fd 00 0c 00 00 00 43 6f 5f 43 50 55 5f 42 4c 72  ......Co_CPU_BLr
0010: 51  Q

Ich würde dich wirklich nicht nerven wenn ich nicht schon alles Probiert hätte, auch alle Tips aus dem Wiki habe ich probiert.  Vermutlich ist es auch nur eine Kleinigkeit.

**Comment by leonsio** [comment]
Schau wie deine 
InterfacesList.xml aussieht. 
Gruß 
Leo

**Comment by c280driver** [comment]
herzlichen dank die xmls im container waren komplett leer.

ich habe nun den dev branch wie im forum beschrieben gezogen und ich konnte nun den schalter anlernen.

vielen dank dir und schönes we

heinz
