### ISSUE TITLE
Quickinstall funktioniert nicht

### ISSUE THREAD

**Issue by TheRealTremes** [leonsio/YAHM#9]
Hallo, ich wollte gerade YAHM auf einem frischen Jessie (Raspi2) installieren. 
Bekomme aber diese Meldung:

> root@raspberrypi:~# wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
> 2016-05-18 18:15:48 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [4405/4405] -> "-" [1]
> Found ARM based distribution
> Updating sources
> Installing dependencies
> Installing dependencies
> install sendmail
> Die E-Mail-Oberfläche benötigt ein installiertes »sendmail«, verwende Pager
> wget is installed
> install dos2unix
> python is installed
> git is installed
> install lxc
> install liblzo2-dev
> install bridge-utils
> install python-lzo
> patch is installed
> gzip is installed
> openssl is installed
> Downloading actual version from git repository
> Including YAHM into PATH

```
Enter quick install mode

Installing LXC container
YAHM LXC container was installed successfully

Creating Bridge for networking
Bridge yahmbr0 with interface eth0 was created

Attaching network configuration to LXC container
```

An error occurred while processing quickinstall mode. Pleasy try manually installation

**Comment by leonsio** [comment]
Liegt am nicht vorhandenen Patch für 2.19.9 welche heute rauskam, bin gerade dabei den Patch anzupassen

**Comment by TheRealTremes** [comment]
Ah, sehr cool! Also liegt diese Meldung auch daran?:

> root@raspberrypi:~# wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
> wget: kann die Host-Adresse »raw.githubusercontent.com« nicht auflösen

**Comment by leonsio** [comment]
nee das sollte eigentlich nicht passieren, ab und zu ist wohl Github seine nicht erreichbar, würde auch die Probleme mit HMServer.jar erklären

**Comment by TheRealTremes** [comment]
Okay. Ich schmeisse jetzt noch mal Jessie frisch auf die SD-Karte, und dann warte ich auf den Patch. Danke!
