### ISSUE TITLE
Nach Update kann man keine neuen Direktverknüpfungen anlegen

### ISSUE THREAD

**Issue by coyote1** [leonsio/YAHM#90]
Hallo,
ich habe ein Update von YAHM und CCU2 durchgeführt, nun kann ich keine Direktverknüpfungen mehr anlegen, Oberfläche bleibt leer. In der Direktverknüpfungs Übersicht sind die Softkeys mit ${btnRemove} und ${btnEdit} beschriftet.

**Comment by leonsio** [comment]
schau dir die interfaceslist.xml an
ob diese leer ist

**Comment by coyote1** [comment]
Nein ist nicht leer. Meine Direktverknüpfungen sind auch da, editieren geht auch. Nur neue anlegen geht nicht mehr

**Comment by coyote1** [comment]
Sonst keine Idee woran es liegen könnte oder was ich tun kann?

**Comment by Blackei** [comment]
Hi,
Bei mir lag es am Funkmodul. Haben es einmal neu aktiviert und dann war es gut. Habe allerdings seit dem Update ein Problem mit einem Türsensor einer Gruppe bzw Direktverknüpfung.

**Comment by coyote1** [comment]
Welches Funkmodul? Ich habe nur einen HM LAN Gateway, aber kann ich mal testen

**Comment by coyote1** [comment]
Habe jetzt heute über die yahm-ui den CCU Container komplett neu installiert mit Firmware 2.25.15, leider ohne Erfolg.
Nochmal neu installiert mit Firmware 2.21.10 auch kein Erfolg, danach update auf 2.25.15 brachte auch keine Besserung.
Kann einfach keine neuen Verknüpfungen mehr anlegen, das Feld in dem normalerweise die Verknüpfungspartner stehen, bleibt leer.
Keine Ahnung was ich noch machen soll...

**Comment by coyote1** [comment]
So, Problem hat sich erledigt. Man man man, es lag am Browser. Nach löschen des Caches funktioniert alles wie gewohnt. Hab ich heute durch Zufall rausgefunden, da auf dem Smartphone alles vorhanden war und korrekt dargestellt wurde....
