### ISSUE TITLE
Fehlermeldung 'BidCos-RF Anlernmodus konnte nicht aktiviert werden'

### ISSUE THREAD

**Issue by olisim** [leonsio/YAHM#94]
Nach der Installation von YAHM auf einem Raspberry Pi 3 mit einem frischen Raspbian und dem Aktivieren des Moduls wie im README beschrieben erhalte ich beim Aufruf der Anlernfunktion in der Homematic WebUI die Fehlermeldung 'BidCos-RF Anlernmodus konnte nicht aktiviert werden'. Ein Fehler am Funkmodul kann sehr wahrscheinlich ausgeschlossen werden, da das Modul auf gleicher Hardware mit RaspberryMatic funktioniert. Sind hier ggf. noch weitere Schritte nötig? Danke!

**Comment by leonsio** [comment]
schau bitte im Wiki nach
Aktuelle RaspberryMatic setzt eine andere FW für das Modul, ggf brauchst du vorher ein Downgrade
