### ISSUE TITLE
RaspBee Unterstützung?

### ISSUE THREAD

**Issue by mariusmuntean** [leonsio/YAHM#95]
Hallo,

Wird der RaspBee unterstützt? Link: https://www.dresden-elektronik.de/raspbee/

Wenn nicht, ist es geplant diesen zu unterstützen?

**Comment by leonsio** [comment]
Inwieweit soll das Ding unterstützt werden?
Hat ja nix mit ccu zu tun

Es nützt die selben pins wie hm funk Adapter. Somit wird es an den Container durchgereicht
