### ISSUE TITLE
Module rfdwatchdog kann nicht installiert werden

### ISSUE THREAD

**Issue by xfjx** [leonsio/YAHM#96]
Hallo, scheinbar muss das Verzeichnis /usr/local/addons erst im LXC Filesystem angelegt werden... dann klappt es 

root@pi2:/opt/YAHM/share/modules# yahm-module -f -m rfdwatchdog enable
Executing rfdwatchdog module_install()
mkdir: cannot create directory '/var/lib/lxc/yahm/root/usr/local/addons/watchdog': No such file or directory
Install TCL File
/opt/YAHM/share/modules/rfdwatchdog: line 17: /var/lib/lxc/yahm/root/usr/local/addons/watchdog/watchdog.tcl: No such file or directory
Install CRON
/opt/YAHM/share/modules/rfdwatchdog: line 47: /var/lib/lxc/yahm/root/usr/local/addons/watchdog/install.sh: No such file or directory
/bin/sh: can't open '/usr/local/addons/watchdog/install.sh'
rm: cannot remove '/var/lib/lxc/yahm/root/usr/local/addons/watchdog/install.sh': No such file or directory
STATUS: Module rfdwatchdog was successfully installed

**Comment by leonsio** [comment]
danke ich schau es mir an und werde bei der nächsten Version fixen

**Comment by xfjx** [comment]
Ach ja, der Download Link für die CUxD Installation ist auch nicht mehr aktuell. Er findet daher die Datei nicht mehr und kann CUxD nicht installieren.

Der neue Link ist: https://homematic-forum.de/forum/download/file.php?id=34677

**Comment by leonsio** [comment]
habe Download Link zu Cuxd angepasst und watchdog gefixt
beides ist mit der kommenden Version online (aktuell Develop branch)
