### ISSUE TITLE
RP3 und aktuelles Jessie, keine Installation möglich

### ISSUE THREAD

**Issue by leiweke** [leonsio/YAHM#97]
Hallo Leo,

ich habe jetzt noch einen neuen PI3 bekommen und mit einem Netinstall Image aufgesetzt.
http://docs.openhab.org/installation/openhabian.html
Leider wieder das gleiche Problem:

openhabian@openHABianPi:~$ wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
2017-02-26 22:17:31 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
An error occurred while processing quickinstall mode. Pleasy try manually installation
openhabian@openHABianPi:~$ wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -
2017-02-26 22:17:47 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
openhabian@openHABianPi:~$ 
openhabian@openHABianPi:~$ 
openhabian@openHABianPi:~$ sudo su
[22:20:23] root@openHABianPi:/home/openhabian# wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -
2017-02-26 22:20:25 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
[22:20:25] root@openHABianPi:/home/openhabian# wget -nv -O- https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init | sudo -E  bash -s quickinstall -
2017-02-26 22:20:39 URL:https://raw.githubusercontent.com/leonsio/YAHM/master/yahm-init [5176/5176] -> "-" [1]
Found ARM based distribution
An error occurred while processing quickinstall mode. Pleasy try manually installation

Dann habe ich die packages nach installieren wollen:
[22:24:23] root@openHABianPi:/home/openhabian# apt-get install sendmail bash-completion wget dos2unix python git lxc liblzo2-dev bridge-utils python-lzo patch gzip openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bash-completion is already the newest version.
git is already the newest version.
gzip is already the newest version.
openssl is already the newest version.
patch is already the newest version.
patch set to manually installed.
python is already the newest version.
python set to manually installed.
wget is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sendmail : Depends: sendmail-bin but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
[22:24:33] root@openHABianPi:/home/openhabian# 

unter /var/log/yahm liegt leider kein file.

ich verstehe es nicht mehr.

**Comment by leonsio** [comment]
Hi

Ich unterstütze nur Raspbian 

Mit freundlichen Grüßen

Leo

**Comment by leiweke** [comment]
und was ist das:
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Feb 26 20:46:56 2017 from sleiweke-m-11qa.fritz.box

###################################################################################
###################### openHABianPi #################### 6.12.170220 ####
###################################################################################
##          Ip = 192.168.178.24
##     **Release = Raspbian GNU/Linux 8 (jessie)**
##      Kernel = Linux 4.4.0-1-rpi2
##    Platform = Raspberry Pi 3 Model B Rev 1.2
##      Uptime = 0 day(s). 5:46:44
##   CPU Usage = 0 % average CPU usage over 4 core(s)
##    CPU Load = 1m: 0.23, 5m: 0.87, 15m: 0.57
##      Memory = Free: 0.46 GB (49%), Used: 0.48 GB (51%), Total: 0.94 GB
##        Swap = Free: 0.00 GB (0%), Used: 0.00 GB (100%), Total: 0.00 GB
##        Root = Free: 12.00 GB (90%), Used: 1.24 GB (10%), Total: 13.97 GB
##     Updates = 0 apt-get updates available.
##    Sessions = openhabian@sleiweke-m-11qa.fritz.box,openhabian@sleiweke-m-11qa.fritz.box,openhabian@sleiweke-m-11qa.fritz.box,openhabian@sleiweke-m-11qa.fritz.box
##   Processes = 126 running processes of 32768 maximum processes
##############################################################################

              Welcome to            __  _____    ____  _
            ____  ____  ___  ____  / / / /   |  / __ )(_)___ _____
           / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  / / __ `/ __ \
          / /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ / / /_/ / / / /
          \____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/_/\__,_/_/ /_/
              /_/
                  openHAB 2.0.0-1 (Release Build)


Looking for a place to get started? Check out 'sudo openhabian-config' and the
documentation at http://docs.openhab.org/installation/openhabian.html


mir ist noch aufgefallen das es mit sendmail ein problem gibt:

[23:11:39] root@openHABianPi:/opt# apt install sendmail
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sendmail : Depends: sendmail-bin but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
[23:11:47] root@openHABianPi:/opt# apt install sendmail-bin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libsigsegv2 m4 make sendmail-base sendmail-cf
Suggested packages:
  make-doc sendmail-doc logcheck resolvconf sasl2-bin
**The following packages will be REMOVED:
  exim4-base exim4-config exim4-daemon-light**
The following NEW packages will be installed:
  libsigsegv2 m4 make sendmail-base sendmail-bin sendmail-cf
0 upgraded, 6 newly installed, 3 to remove and 0 not upgraded.
Need to get 1,854 kB of archives.
After this operation, 552 kB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.

Gruß
Sebastian

**Comment by leonsio** [comment]
ich weiß nicht was du mir mit diesem post sagen möchtest, aber openhab nutzt eine modifizierte rasbian Version und ich unterstütze nur die original
Somit kann ich dir leider keinen Support geben
