### ISSUE TITLE
RP3 mit WLAN Bridge nicht konfigurierbar ?

### ISSUE THREAD

**Issue by fjjat** [leonsio/YAHM#98]
Nach der automatischen Installation konnte ich mich nicht mehr auf dem Pi3 via SSH anmelden, also das ganze noch einmal manuell durchgeführt. Gleicher Effekt nachdem die Bridge eingerichtet wurde. Bridge entfernt, SSH funktioniert wieder. 

Leider verstehen die Installationesroutinen bzw yahm-ui nur interface eth0 ("Netzwerkinterface wlan0 ist nicht vorhanden") obwohl ich via SSH bzw Xterm auf den Pi3 zugreifen kann.

Also habe ich versucht  wlan0 ->Bridge eth0 -> Bridge yahmbr0 -> YAHM
br0                  8000.b827eb83d26a       no              eth0
yahmbr0         8000.fe79f7940784         no              vethN8438B

Pi startet und ich kann zugreifen. Kein Zugriff auf die WebUI und warum ändert sich bei jedem reboot das CCU-Interface (vethN8438B == veth9TAWTI) 

Mein Netzwerk hat eine ganz andere IP Range 192.168.10.x mit MAC-Auflösung über Secure-Gateway.

GIT Branch .....: master
YAHM Version ...: 1.5

CCU2 Container Status:
CCU Container ..: yahm
CCU Status .....: RUNNING

CCU2 Netzwerk Status:
CCU IP Adresse .: 192.168.1.225   <- woher kommt diese IP ?
CCU Interface ..: veth9TAWTI
CCU Bridge .....: yahmbr0     

Raspberry 3 B V1.2 / Raspberry Jessie Light

**Comment by leonsio** [comment]
WLAN Bridge wird nicht unterstützt, deswegen zeigt die UI auch nur eth0 an
hier gibt bzw. im homematic Forum gibt es bereits posts zur WLAN Bridge

es müssen einige Sachen angepasst werden, frag am besten im HM Forum nach
