### ISSUE TITLE
Update zu den Installations Problemen

### ISSUE THREAD

**Issue by leiweke** [leonsio/YAHM#99]
Hallo Leo,

habe heute einige Zeit investiert und alle möglichen Kombinationen aus probiert.
Also RPI3 (mit Tastatur, Monitor und Maus (wichtig)) mit 2017-01-11-raspbian-jessie in Pixel gebootet, SDcard vergrößert, password geändert und gebootet. 
Dann die direkt per Tastatur die automatische Installation aufgerufen und sie läuft durch ohne Fehlermeldung.
ABER mache ich das ganze per SSH dann bleibt die installation nach der Plattform Erkennung stehen, so wie ich es die ganze Zeit gepostet habe.
Das gleiche gilt für den Befehl 
pi@raspberrypi3:~$ sudo yahm-ctl info
LXC container information
pi@raspberrypi3:~$ 
Wenn ich den direkt aus der Tastatur ausführe dann sieht er so aus:
pi@raspberrypi3:~ $ sudo yahm-ctl info
LXC container information
Name:           yahm
State:          RUNNING
PID:            827
IP:             192.168.1.225
CPU use:        0.63 seconds
BlkIO use:      3.83 MiB
Memory use:     5.23 MiB
Link:           veth0S0K0F
 TX bytes:      2.84 KiB
 RX bytes:      18.49 KiB
 Total bytes:   21.33 KiB
pi@raspberrypi3:~ $ 

so das ist das erste Problem.
Das 2. ist das ich keine HM Webseite angezeigt bekommen.

pi@raspberrypi3:~ $ ifconfig
eth0      Link encap:Ethernet  HWaddr b8:27:eb:30:72:8e  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:104 errors:0 dropped:0 overruns:0 frame:0
          TX packets:81 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:11820 (11.5 KiB)  TX bytes:14151 (13.8 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:520 (520.0 B)  TX bytes:520 (520.0 B)

veth0S0K0F Link encap:Ethernet  HWaddr fe:92:77:d3:49:a1  
          inet6 addr: fe80::fc92:77ff:fed3:49a1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:20 errors:0 dropped:0 overruns:0 frame:0
          TX packets:107 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2904 (2.8 KiB)  TX bytes:17453 (17.0 KiB)

wlan0     Link encap:Ethernet  HWaddr b8:27:eb:65:27:db  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:2 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:123 (123.0 B)  TX bytes:0 (0.0 B)

yahmbr0   Link encap:Ethernet  HWaddr b8:27:eb:30:72:8e  
          **inet addr:192.168.178.21**  Bcast:192.168.178.255  Mask:255.255.255.0
          inet6 addr: 2003:4e:a906:9a00:ba27:ebff:fe30:728e/64 Scope:Global
          inet6 addr: fe80::ba27:ebff:fe30:728e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:120 errors:0 dropped:0 overruns:0 frame:0
          TX packets:61 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:14260 (13.9 KiB)  TX bytes:10419 (10.1 KiB)

pi@raspberrypi3:~ $ sudo yahm-ctl info
LXC container information
Name:           yahm
State:          RUNNING
PID:            827
IP:             **192.168.1.225**
CPU use:        0.63 seconds
BlkIO use:      3.83 MiB
Memory use:     5.23 MiB
Link:           veth0S0K0F
 TX bytes:      2.84 KiB
 RX bytes:      18.49 KiB
 Total bytes:   21.33 KiB
pi@raspberrypi3:~ $ 

IP 192.168.178.21 ist erreichbar und liegt auf yahmbr0, aber yahm-ctl info sagt mir 192.168.1.225.
http://192.168.178.21/pages/index.htm
kein erfolg.

Warum hat der Container denn 192.168.1.225 und nicht eine IP aus meinem Netz 192.168.178.21??

Danke dir
Sebastian

**Comment by leiweke** [comment]
Hallo Leo, Problem 2 mit der IP Adresse ist gelöst, war die Port Security auf meinem Switch.

**Comment by leiweke** [comment]
Hallo Leo, Problem 1 besteht immer noch.
Sprich der unterschied es direkt auf der Tastatur zu machen oder per SSH.
Irgendeine Idee, da der PI3 in den Keller soll headless.

**Comment by leonsio** [comment]
Funktioniert alle anderen Befehle über console? Bzw andere Anwendungen? (top/wc/Echo/usw)?

**Comment by leiweke** [comment]
ja ich habe die ganzen apt-get usw. alles über ssh gemacht. top geht 
jetzt ist ja yahm installiert und wenn ich z.bsp. sudo yahm-ui lokal aufrufe, geht alles.

**lokal:**
pi@raspberrypi3:~ $ sudo yahm-ui
Welcome to YAHM-UI 
Update Check
Entering main loop
Menü erscheint und Informationen werden angezeigt, dann Menü 0 für beenden
Finishing
pi@raspberrypi3:~ $ 

**über SSH:**
pi@raspberrypi3:~$ sudo yahm-ui 
Welcome to YAHM-UI 
pi@raspberrypi3:~$

**Comment by leiweke** [comment]
OMG Asche auf mein Haupt.
ich habe ein neues Terminal Programm SecureCRT und habe mit dort alle Maschinen angelegt. dort ist default VT100 Emulation eingestellt. Wenn ich es auf Linux umstelle dann geht alles.
Von meinem Mac OSX Terminal geht es auch.
Verstehe es zwar nicht warum alles andere funktioniert und yahm Befehle nicht.
Danke für deine Geduld, dann werde ich jetzt mal den Pi2 umziehen.
